Repository grouparoo/grouparoo, pull requests merged in 2020-12, with the labels that each got.

#1039 `model.locked` is a string indicating why the model is locked
  core/api/__tests__/actions/sessions.ts
  core/api/__tests__/actions/teams.ts
  core/api/__tests__/models/group/group.ts
  core/api/__tests__/models/log.ts
  core/api/__tests__/models/profileProperty.ts
  core/api/__tests__/models/team.ts
  core/api/__tests__/modules/codeConfig.ts
  core/api/__tests__/modules/lockableHelper.ts
  core/api/src/actions/teams.ts
  core/api/src/classes/codeConfig.ts
  core/api/src/migrations/000053-removeCompoundindex.ts
  core/api/src/migrations/000054-lockedString.ts
  core/api/src/models/ApiKey.ts
  core/api/src/models/App.ts
  core/api/src/models/Destination.ts
  core/api/src/models/DestinationGroupMembership.ts
  core/api/src/models/Group.ts
  core/api/src/models/GroupMember.ts
  core/api/src/models/Mapping.ts
  core/api/src/models/Option.ts
  core/api/src/models/Permission.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Schedule.ts
  core/api/src/models/Setting.ts
  core/api/src/models/Source.ts
  core/api/src/models/Team.ts
  core/api/src/models/TeamMember.ts
  core/api/src/modules/configLoaders/apiKey.ts
  core/api/src/modules/configLoaders/app.ts
  core/api/src/modules/configLoaders/destination.ts
  core/api/src/modules/configLoaders/group.ts
  core/api/src/modules/configLoaders/profilePropertyRule.ts
  core/api/src/modules/configLoaders/schedule.ts
  core/api/src/modules/configLoaders/setting.ts
  core/api/src/modules/configLoaders/source.ts
  core/api/src/modules/configLoaders/team.ts
  core/api/src/modules/configLoaders/teamMember.ts
  core/api/src/modules/lockableHelper.ts
  core/api/src/modules/ops/group.ts
  core/web/components/permissions.tsx
  core/web/pages/apiKey/[guid]/edit.tsx
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/group/[guid]/edit.tsx
  core/web/pages/group/[guid]/rules.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/settings/[tab].tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
  core/web/pages/source/[guid]/schedule.tsx
  core/web/pages/team/[guid]/edit.tsx
  core/web/pages/teamMember/[guid]/edit.tsx
  core/web/pages/teams.tsx
  plugins/@grouparoo/demo/src/configFiles.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: bug, enhancement

#1044 Import from dist
  plugins/@grouparoo/bigquery/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/marketo/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/mysql/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/postgres/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/salesforce/src/lib/export-objects/exportProfiles.ts
  plugins/@grouparoo/salesforce/src/lib/export/salesforceExporter.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/get-changed-row-count.ts
Labels: internal

#1040 Code Config for the events App & The Events App is No Longer Created Automatically
  core/api/__tests__/actions/apps.ts
  core/api/__tests__/actions/cluster.ts
  core/api/__tests__/fixtures/codeConfig/changes/config.js
  core/api/__tests__/fixtures/codeConfig/initial/config.js
  core/api/__tests__/integration/events.ts
  core/api/__tests__/models/app/app.ts
  core/api/__tests__/models/app/eventsApp.ts
  core/api/__tests__/modules/codeConfig.ts
  core/api/__tests__/tasks/event/associateProfile.ts
  core/api/src/actions/apps.ts
  core/api/src/actions/cluster.ts
  core/api/src/classes/codeConfig.ts
  core/api/src/classes/plugin.ts
  core/api/src/initializers/events.ts
  core/api/src/models/App.ts
  core/api/src/models/DestinationGroupMembership.ts
  core/api/src/models/GroupMember.ts
  core/api/src/models/Mapping.ts
  core/api/src/models/Option.ts
  core/api/src/models/Permission.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/Setting.ts
  core/api/src/modules/configLoaders/all.ts
  plugins/@grouparoo/demo/config/events/pageviews.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/demo/src/events.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement

#1045 Log when a code-config model is deleted
  core/api/src/classes/codeConfig.ts
  core/api/src/initializers/codeConfig.ts
  core/api/src/modules/configLoaders/apiKey.ts
  core/api/src/modules/configLoaders/app.ts
  core/api/src/modules/configLoaders/destination.ts
  core/api/src/modules/configLoaders/group.ts
  core/api/src/modules/configLoaders/index.ts
  core/api/src/modules/configLoaders/profilePropertyRule.ts
  core/api/src/modules/configLoaders/schedule.ts
  core/api/src/modules/configLoaders/setting.ts
  core/api/src/modules/configLoaders/source.ts
  core/api/src/modules/configLoaders/team.ts
  core/api/src/modules/configLoaders/teamMember.ts
  plugins/@grouparoo/demo/src/configFiles.ts
Labels: enhancement

#1047 Test the Staging App's API (and that the build boots)
  .circleci/config.yml
  apps/staging-public/__tests__/integration
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/apps/workflow.yml.template
  tools/merger/src/ci_generate.js
Labels: internal

#1048 Fix Locked string migration (#000054)
  core/api/src/migrations/000054-lockedString.ts
Labels: bug

#1049 Code config ui
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/group/[guid]/rules.tsx
Labels: enhancement

#1058 Remove Sample UI Plugin
  .circleci/config.yml
  apps/staging-public/package.json
  cli/templates/package.json
  plugins/@grouparoo/sample-ui-plugin/LICENSE.txt
  plugins/@grouparoo/sample-ui-plugin/README.md
  plugins/@grouparoo/sample-ui-plugin/jest.config.js
  plugins/@grouparoo/sample-ui-plugin/jest.setup.js
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/sample-ui-plugin/src/components/sample.plugin.tsx
  plugins/@grouparoo/sample-ui-plugin/src/initializers/sample-ui-plugin.ts
  plugins/@grouparoo/sample-ui-plugin/tsconfig.json
  pnpm-lock.yaml
Labels: internal

#1059 Update to Actionhero v25.0.0-alpha.2 and Node Resque v8.2.0
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1073 Test that Group Rule comparisons are valid SQL before saving
  core/__tests__/models/group/calculatedGroup.ts
  core/src/models/Group.ts
Labels: bug

#1074 Fix logic to show 0 pending profiles on dashboard
  ui/components/visualizations/homepageWidgets.tsx
Labels: bug

#1070 Grouparoo CLI Commands
  Procfile
  apps/staging-public/package.json
  apps/ui-test/package.json
  cli/README.md
  cli/__tests__/test.sh
  cli/package.json
  cli/src/grouparoo.ts
  cli/src/lib/generate.ts
  cli/src/lib/logger.ts
  cli/src/lib/spawnCommand.ts
  cli/src/lib/upgrade.ts
  cli/src/utils/ensurePath.ts
  cli/src/utils/loadLocalCommands.ts
  cli/src/utils/logger.ts
  cli/src/utils/spawnCommand.ts
  cli/src/utils/templates.ts
  core/__tests__/bin/statuts.ts
  core/package.json
  core/src/actions/groups.ts
  core/src/bin/console.ts
  core/src/bin/start.ts
  core/src/bin/status.ts
  core/src/config/api.ts
  core/src/config/environment.ts
  core/src/config/plugins.ts
  core/src/initializers/environment.ts
  core/src/initializers/plugins.ts
  core/src/modules/ops/group.ts
  core/src/utils/pluginDetails.js
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/config.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/eventStream.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/setup.ts
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/newrelic/src/serverInjection.ts
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/__tests__/utils/specHelper.ts
Labels: enhancement

#1075 Support CLI commands when Grouparoo is at the same level as Actionhero
  cli/src/utils/loadLocalCommands.ts
Labels: bug

#1076 Consider more module resolution strategies in CLI
  cli/src/utils/loadLocalCommands.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: bug

#1077 CLI checks for valid node.js version
  cli/package.json
  cli/src/grouparoo.ts
  cli/src/utils/checkNodeVersion.ts
  cli/src/utils/ensureNoTsHeaderFiles.ts
  cli/src/utils/loadLocalCommands.ts
  cli/src/utils/readPackageJSON.ts
  pnpm-lock.yaml
Labels: enhancement

#1078 Showing the ui plugin in the boot logs
  core/src/initializers/plugins.ts
  core/src/initializers/ui.ts
Labels: enhancement

#1080 UI headers are the same Size regardless of browser width
  ui/components/badges/destinationBadge.tsx
  ui/components/badges/lockedBadge.tsx
  ui/components/badges/sourceBadge.tsx
  ui/components/badges/stateBadge.tsx
  ui/components/pageHeader.tsx
  ui/components/profile/list.tsx
  ui/pages/apiKey/[guid]/edit.tsx
  ui/pages/app/[guid]/edit.tsx
  ui/pages/apps.tsx
  ui/pages/destination/[guid]/data.tsx
  ui/pages/destination/[guid]/edit.tsx
  ui/pages/destination/[guid]/exports.tsx
  ui/pages/destinations.tsx
  ui/pages/group/[guid]/edit.tsx
  ui/pages/group/[guid]/members.tsx
  ui/pages/group/[guid]/rules.tsx
  ui/pages/groups.tsx
  ui/pages/profile/[guid]/edit.tsx
  ui/pages/profile/[guid]/events.tsx
  ui/pages/profile/[guid]/exports.tsx
  ui/pages/profile/[guid]/imports.tsx
  ui/pages/profile/[guid]/logs.tsx
  ui/pages/profilePropertyRule/[guid]/[plugin].tsx
  ui/pages/profilePropertyRule/[guid]/edit.tsx
  ui/pages/profilePropertyRule/[guid]/groups.tsx
  ui/pages/profilePropertyRule/[guid]/logs.tsx
  ui/pages/profilePropertyRule/[guid]/profiles.tsx
  ui/pages/profilePropertyRule/[guid]/runs.tsx
  ui/pages/profilePropertyRules.tsx
  ui/pages/settings/[tab].tsx
  ui/pages/source/[guid]/edit.tsx
  ui/pages/source/[guid]/mapping.tsx
  ui/pages/source/[guid]/overview.tsx
  ui/pages/source/[guid]/runs.tsx
  ui/pages/source/[guid]/schedule.tsx
  ui/pages/sources.tsx
  ui/pages/team/[guid]/edit.tsx
Labels: bug

#1079 SQLite default path within project root
  cli/src/lib/generate.ts
  cli/src/lib/upgrade.ts
  cli/templates/.env
  core/.npmignore
  core/src/config/sequelize.ts
  core/src/initializers/environment.ts
Labels: enhancement

#1083 Sql dialect bug
  core/src/config/sequelize.ts
  ui/next.config.js
Labels: bug

#1099 Actionhero v25.0.1
  core/package.json
  core/src/config/servers/web.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1100 CLI Commands Update
  cli/__tests__/test.sh
  cli/package.json
  cli/src/grouparoo.ts
  cli/src/lib/initialize.ts
  cli/src/lib/install.ts
  cli/src/lib/update.ts
  cli/src/utils/ensurePackageJSON.ts
  cli/src/utils/ensurePath.ts
  cli/src/utils/loadLocalCommands.ts
  cli/src/utils/npm.ts
  cli/src/utils/spawnCommand.ts
  cli/templates/package.json
  pnpm-lock.yaml
Labels: enhancement

#1101 Destroying Destinations happens via task
  .gitignore
  core/__tests__/actions/destinations.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/models/group/group.ts
  core/__tests__/models/properties/property.ts
  core/__tests__/modules/codeConfig.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/group/run.ts
  core/__tests__/tasks/group/updateCalculatedGroups.ts
  core/bin/dev
  core/src/actions/destinations.ts
  core/src/config/sequelize.ts
  core/src/initializers/environment.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/property.ts
  core/src/tasks/destination/destroy.ts
  core/src/tasks/export/enqueue.ts
  core/src/tasks/group/run.ts
  core/src/tasks/group/updateCalculatedGroups.ts
  core/src/tasks/profile/export.ts
  plugins/@grouparoo/logger/src/initializers/plugin.ts
  plugins/@grouparoo/logger/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/logger/src/lib/test.ts
  plugins/@grouparoo/logger/src/lib/utils/getFilePath.ts
  ui/components/visualizations/homepageWidgets.tsx
Labels: enhancement

#1102 Files UI Fixes
  .gitignore
  plugins/@grouparoo/files-s3/src/classes/s3.ts
  ui/components/filePreview.tsx
  ui/pages/file/[guid]/edit.tsx
  ui/pages/files.tsx
Labels: bug

#1104 Cli fixes
  cli/src/lib/install.ts
  core/package.json
  core/src/modules/ops/teamMember.ts
  pnpm-lock.yaml
Labels: bug

#1103 Use Task to delete code config Destionations
  core/__tests__/modules/codeConfig.ts
  core/__tests__/tasks/destination/destroy.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/tasks/destination/destroy.ts
Labels: enhancement

#1105 Plugin Logging
  core/__tests__/modules/codeConfig.ts
  core/src/initializers/codeConfig.ts
  core/src/initializers/plugins.ts
  core/src/initializers/ui.ts
Labels: internal

#1109 Add spec for validate command
  core/__tests__/bin/validate.ts
  core/src/bin/validate.ts
  core/src/modules/configLoaders/index.ts
Labels: internal

#1110 Recurring Internal Run
  core/__tests__/tasks/run/recurringInternalRun.ts
  core/src/initializers/settings.ts
  core/src/models/Run.ts
  core/src/tasks/run/recurringInternalRun.ts
  ui/components/settings/importAndUpdate.tsx
  ui/components/settings/settingCard.tsx
  ui/pages/settings/[tab].tsx
Labels: enhancement

#1111 Fix bug with Profile Details page not showing properties
  core/src/modules/ops/property.ts
  ui/pages/profile/[guid]/edit.tsx
Labels: bug

#1112 Properties with no Options or Filers create a run when they go ready
  core/__tests__/models/property/dependsOn.ts
  core/__tests__/models/property/property.ts
  core/src/models/Property.ts
Labels: bug

#1108 Facebook Custom Audiences Destination
  .circleci/config.yml
  apps/staging-public/package.json
  plugins/@grouparoo/app-templates/src/destination/batch/exportProfiles.ts
  plugins/@grouparoo/app-templates/src/destination/group/exportProfiles.ts
  plugins/@grouparoo/app-templates/src/destination/group/index.ts
  plugins/@grouparoo/app-templates/src/destination/group/types.ts
  plugins/@grouparoo/app-templates/src/destination/shared/batch.ts
  plugins/@grouparoo/facebook/.npmignore
  plugins/@grouparoo/facebook/LICENSE.txt
  plugins/@grouparoo/facebook/README.md
  plugins/@grouparoo/facebook/__tests__/.env.example
  plugins/@grouparoo/facebook/__tests__/fixtures/export-profiles-custom.js
  plugins/@grouparoo/facebook/__tests__/integration/destination-mapping-custom.ts
  plugins/@grouparoo/facebook/__tests__/integration/export-profiles-custom.ts
  plugins/@grouparoo/facebook/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/facebook/jest.config.js
  plugins/@grouparoo/facebook/jest.setup.js
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/facebook/public/@grouparoo/facebook/facebook.png
  plugins/@grouparoo/facebook/src/initializers/plugin.ts
  plugins/@grouparoo/facebook/src/lib/connect.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/connection.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/destinationMappingOptions.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/destinationOptions.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/exportArrayProperties.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/exportProfiles.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/model.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/connection.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/destinationMappingOptions.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/destinationOptions.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/exportArrayProperties.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/exportProfiles.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/model.ts
  plugins/@grouparoo/facebook/src/lib/export/audienceMethods.ts
  plugins/@grouparoo/facebook/src/lib/export/data.ts
  plugins/@grouparoo/facebook/src/lib/export/facebookExporter.ts
  plugins/@grouparoo/facebook/src/lib/export/fields.ts
  plugins/@grouparoo/facebook/src/lib/export/mapping.ts
  plugins/@grouparoo/facebook/src/lib/export/model.ts
  plugins/@grouparoo/facebook/src/lib/export/utils.ts
  plugins/@grouparoo/facebook/src/lib/test.ts
  plugins/@grouparoo/facebook/tsconfig.json
  pnpm-lock.yaml
  tools/license-checker/check
Labels: enhancement

#1121 Move prepare command into bin/publish
  .circleci/config.yml
  bin/publish
  tools/merger/data/ci/publish/core.yml.template
Labels: internal

#1133 Update to Typedoc v0.20.x
  core/package.json
  pnpm-lock.yaml
Labels: dependencies
