Repository grouparoo/grouparoo, pull requests merged in 2020-08, with the labels that each got.

#574 Use dependabot.yml rather than web config
  .github/dependabot.yml
Labels: dependencies, internal

#575 Update Dependencies
  clients/@grouparoo/web/package-lock.json
  clients/@grouparoo/web/package.json
  core/package-lock.json
  core/package.json
  package.json
  plugins/@grouparoo/bigquery/package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package-lock.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package-lock.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package-lock.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package-lock.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package-lock.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package-lock.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package-lock.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/package-lock.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package-lock.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package-lock.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package-lock.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package-lock.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: dependencies

#577 Update dependency: jest@26.2.2
  package-lock.json
Labels: dependencies

#578 update @types/react
  core/package-lock.json
  core/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/redshift/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: dependencies

#584 Reduce restrictions on newrelic license exemptions
  tools/license-checker/check
Labels: dependencies

#522 Runs UI Updates
  core/api/__tests__/actions/runs.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/models/schedule.ts
  core/api/src/actions/runs.ts
  core/api/src/classes/plugin.ts
  core/api/src/config/routes.ts
  core/api/src/migrations/000034-runPercentComplete.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/modules/ops/runs.ts
  core/api/src/modules/ops/schedule.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/runs/determineState.ts
  core/api/src/tasks/runs/internalRun.ts
  core/api/src/tasks/schedule/run.ts
  core/web/components/events/list.tsx
  core/web/components/events/types.tsx
  core/web/components/export/list.tsx
  core/web/components/import/list.tsx
  core/web/components/log/list.tsx
  core/web/components/navigation.tsx
  core/web/components/profile/list.tsx
  core/web/components/resque/delayed.tsx
  core/web/components/resque/failed.tsx
  core/web/components/resque/locks.tsx
  core/web/components/resque/queue.tsx
  core/web/components/runs/list.tsx
  core/web/pages/apiKeys.tsx
  core/web/pages/apps.tsx
  core/web/pages/destinations.tsx
  core/web/pages/files.tsx
  core/web/pages/groups.tsx
  core/web/pages/profilePropertyRules.tsx
  core/web/pages/run/[guid]/edit.tsx
  core/web/pages/sources.tsx
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/sourceRunPercentComplete.ts
  plugins/@grouparoo/csv/__tests__/integration/csv.ts
  plugins/@grouparoo/csv/src/initializers/plugin.ts
  plugins/@grouparoo/csv/src/lib/file-import/sourceRunPercentComplete.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/google-sheets-import.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/sourceRunPercentComplete.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/src/lib/connect.ts
  plugins/@grouparoo/mysql/src/lib/table-import/sourceRunPercentComplete.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/table-import/sourceRunPercentComplete.ts
Labels: bug, enhancement

#587 When there are no profiles, return 0% complete for runs
  core/api/src/modules/ops/runs.ts
  core/web/components/visualizations/totals.tsx
Labels: bug

#588 Display and import updates for manual profile properties
  core/api/__tests__/models/profilePropertyRule.ts
  core/api/src/initializers/plugins.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/web/components/profile/arrayProfilePropertyList.tsx
  core/web/pages/profile/[guid]/edit.tsx
Labels: bug

#589 Display UI Errors in custom error component
  core/package-lock.json
  core/package.json
  core/web/next.config.js
  core/web/pages/_app.tsx
  core/web/pages/_error.tsx
  package-lock.json
Labels: enhancement

#590 If there's a CSRF token error, destroy the session
  core/api/__tests__/actions/sessions.ts
  core/api/src/initializers/session.ts
Labels: bug

#591 Identifying Profile Property
  core/api/__tests__/actions/profiles.ts
  core/api/__tests__/models/profilePropertyRule.ts
  core/api/__tests__/models/source.ts
  core/api/src/actions/profilePropertyRules.ts
  core/api/src/actions/profiles.ts
  core/api/src/migrations/000035-identifyingProfilePropertyRule.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/modules/ops/source.ts
  core/web/components/profile/getProfileDisplayName.ts
  core/web/components/profile/list.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/profilePropertyRules.tsx
Labels: bug, enhancement

#595 Destination draining
  core/api/__tests__/models/destination.ts
  core/api/src/actions/runs.ts
  core/api/src/migrations/000036-createExportRuns.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Export.ts
  core/api/src/models/ExportRun.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/runs.ts
  core/api/src/modules/telemetryReporters.ts
  core/web/components/tabs/destination.tsx
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/runs.tsx
Labels: enhancement

#596 Do not export Profiles to Destinations if there are no changes (unless we are forcing the run)
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/models/destination.ts
  core/api/__tests__/models/export.ts
  core/api/__tests__/tasks/exports/send.ts
  core/api/__tests__/tasks/groups/run.ts
  core/api/__tests__/tasks/profiles/importAndUpdate.ts
  core/api/__tests__/utils/specHelper.ts
  core/api/src/actions/destinations.ts
  core/api/src/migrations/000037-exportHasChanges.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Export.ts
  core/api/src/models/Run.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/profile/export.ts
  core/api/src/tasks/profile/importAndUpdate.ts
  core/web/components/export/list.tsx
  core/web/components/runs/list.tsx
  core/web/pages/profile/[guid]/edit.tsx
Labels: enhancement

#597 Update dependency: actionhero@23.0.6
  core/package-lock.json
  core/package.json
  plugins/@grouparoo/bigquery/package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package-lock.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package-lock.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package-lock.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package-lock.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package-lock.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package-lock.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package-lock.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/package-lock.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package-lock.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package-lock.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package-lock.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package-lock.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: dependencies

#599 Choose oldest unique profile property rule to be identifying
  core/api/src/migrations/000035-identifyingProfilePropertyRule.ts
Labels: bug

#600 Destination UI Fixes
  core/web/pages/destination/[guid]/data.tsx
  plugins/@grouparoo/mysql/src/lib/connect.ts
  plugins/@grouparoo/mysql/src/lib/export/exportProfile.ts
  plugins/@grouparoo/postgres/src/lib/export/exportProfile.ts
Labels: bug

#598 Destination Batch Exports
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/models/destination.ts
  core/api/__tests__/models/group/group.ts
  core/api/__tests__/models/group/rules/booleans.ts
  core/api/__tests__/models/group/rules/dates.ts
  core/api/__tests__/models/group/rules/floats.ts
  core/api/__tests__/models/group/rules/integers.ts
  core/api/__tests__/models/group/rules/strings.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/tasks/destination/destroyExports.ts
  core/api/__tests__/tasks/event/associateProfile.ts
  core/api/__tests__/tasks/event/associateProfiles.ts
  core/api/__tests__/tasks/export/send.ts
  core/api/__tests__/tasks/export/sendBatch.ts
  core/api/__tests__/tasks/exports/send.ts
  core/api/__tests__/tasks/group/destroy.ts
  core/api/__tests__/tasks/group/exportToCSV.ts
  core/api/__tests__/tasks/group/run.ts
  core/api/__tests__/tasks/group/updateCalculatedGroups.ts
  core/api/__tests__/tasks/profile/destroyEvents.ts
  core/api/__tests__/tasks/profile/export.ts
  core/api/__tests__/tasks/profile/importAndUpdate.ts
  core/api/__tests__/tasks/run/internalRun.ts
  core/api/__tests__/tasks/schedule/run.ts
  core/api/__tests__/utils/prepareSharedGroupTest.ts
  core/api/__tests__/utils/specHelper.ts
  core/api/src/classes/plugin.ts
  core/api/src/initializers/settings.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Run.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/modules/ops/runs.ts
  core/api/src/modules/ops/source.ts
  core/api/src/tasks/destination/destroyExports.ts
  core/api/src/tasks/event/associateProfile.ts
  core/api/src/tasks/event/associateProfiles.ts
  core/api/src/tasks/export/send.ts
  core/api/src/tasks/export/sendBatch.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/import/associateProfile.ts
  core/api/src/tasks/run/determineState.ts
  core/api/src/tasks/run/internalRun.ts
  core/api/src/tasks/schedule/run.ts
  plugins/@grouparoo/hubspot/src/lib/export/exportProfile.ts
  plugins/@grouparoo/logger/src/initializers/plugin.ts
  plugins/@grouparoo/logger/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/mailchimp/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mysql/src/lib/export/exportProfile.ts
  plugins/@grouparoo/postgres/src/lib/export/exportProfile.ts
  plugins/@grouparoo/sailthru/__tests__/export/export-profile.ts
  plugins/@grouparoo/sailthru/src/lib/export/exportProfile.ts
Labels: enhancement

#602 Updated settings page
  core/api/src/actions/navigation.ts
  core/web/components/tabs.tsx
  core/web/pages/settings.tsx
  core/web/pages/settings/[tab].tsx
Labels: enhancement

#603 Phone Number Profile Property Type
  core/api/__tests__/actions/groups.ts
  core/api/__tests__/actions/profilePropertyRules.ts
  core/api/__tests__/models/group/rules/booleans.ts
  core/api/__tests__/models/group/rules/dates.ts
  core/api/__tests__/models/group/rules/emails.ts
  core/api/__tests__/models/group/rules/floats.ts
  core/api/__tests__/models/group/rules/integers.ts
  core/api/__tests__/models/group/rules/phoneNumbers.ts
  core/api/__tests__/models/group/rules/strings.ts
  core/api/__tests__/models/profileProperty.ts
  core/api/__tests__/utils/prepareSharedGroupTest.ts
  core/api/src/initializers/settings.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/RuleOpsDictionary.ts
  core/package-lock.json
  core/package.json
Labels: enhancement

#609 Require that phoneNumber and email Profile Properties be valid
  core/api/__tests__/models/group/rules/phoneNumbers.ts
  core/api/__tests__/models/profileProperty.ts
  core/api/src/models/ProfileProperty.ts
Labels: enhancement

#608 Use count of imports and exports directly to determine run state
  core/api/__tests__/models/run.ts
  core/api/src/models/Run.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/tasks/run/determineState.ts
Labels: bug

#607 The Identifying Profile Property Rule is configured via Settings
  core/api/src/modules/plugin.ts
  core/web/components/import/list.tsx
  core/web/components/profile/importAndUpdate.tsx
  core/web/components/profile/list.tsx
  core/web/components/settings/identifyingProfilePropertyRule.tsx
  core/web/components/settings/importAndUpdate.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/profilePropertyRules.tsx
  core/web/pages/settings/[tab].tsx
Labels: bug, enhancement

#610 Only present Profile Property Rules in the 'ready' state to Destinations
  core/web/pages/destination/[guid]/data.tsx
Labels: bug

#611 Compare Destination group membership with previous export
  core/api/__tests__/models/destination.ts
  core/api/src/modules/ops/destination.ts
Labels: enhancement

#612 CLI tool to fork staging server
  bin/demo-fork
Labels: internal

#614 Move 'Export Profiles' button to Destination runs list
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/runs.tsx
Labels: enhancement

#613 Identifying Profile Property Settings
  core/web/components/settings/identifyingProfilePropertyRule.tsx
  core/web/pages/settings/[tab].tsx
Labels: enhancement

#616 URL Profile Property Rule Type
  core/api/__tests__/actions/groups.ts
  core/api/__tests__/actions/profilePropertyRules.ts
  core/api/__tests__/models/group/rules/urls.ts
  core/api/__tests__/models/profileProperty.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/RuleOpsDictionary.ts
Labels: enhancement

#615 Plugin Validation
  core/api/__tests__/models/destination.ts
  core/api/__tests__/modules/plugin.ts
  core/api/src/initializers/plugins.ts
  core/api/src/models/Destination.ts
  core/api/src/modules/plugin.ts
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/disconnect.ts
Labels: enhancement

#617 Don't clobber mailchimp properties that Grouparoo didn't set
  plugins/@grouparoo/mailchimp/__tests__/fixtures/nock.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export.ts
  plugins/@grouparoo/mailchimp/src/lib/export/exportProfile.ts
Labels: bug

#606 Zendesk Destination
  .circleci/config.yml
  apps/staging-public/package.json
  core/web/pages/app/[guid]/edit.tsx
  package-lock.json
  plugins/@grouparoo/sailthru/__tests__/export/export-profile.ts
  plugins/@grouparoo/zendesk/.npmignore
  plugins/@grouparoo/zendesk/LICENSE.txt
  plugins/@grouparoo/zendesk/README.md
  plugins/@grouparoo/zendesk/__tests__/.env.example
  plugins/@grouparoo/zendesk/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/zendesk/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/zendesk/__tests__/integration/destination-mapping-optons.ts
  plugins/@grouparoo/zendesk/__tests__/integration/export-profile.ts
  plugins/@grouparoo/zendesk/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/zendesk/jest.config.js
  plugins/@grouparoo/zendesk/jest.setup.js
  plugins/@grouparoo/zendesk/package-lock.json
  plugins/@grouparoo/zendesk/package.json
  plugins/@grouparoo/zendesk/public/@grouparoo/zendesk/zendesk.svg
  plugins/@grouparoo/zendesk/src/initializers/plugin.ts
  plugins/@grouparoo/zendesk/src/lib/cache.ts
  plugins/@grouparoo/zendesk/src/lib/connect.ts
  plugins/@grouparoo/zendesk/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/zendesk/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/zendesk/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/zendesk/src/lib/export/exportProfile.ts
  plugins/@grouparoo/zendesk/src/lib/test.ts
  plugins/@grouparoo/zendesk/tsconfig.json
Labels: enhancement

#618 Export serialization
  core/api/__tests__/models/export.ts
  core/api/src/models/Export.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/export.ts
  core/api/src/modules/ops/profileProperty.ts
Labels: enhancement

#621 Support Export serialization when there is a null value
  core/api/__tests__/models/export.ts
  core/api/src/modules/ops/export.ts
Labels: bug

#620 Exports are enqueued by a period task and decoupled from importing
  core/api/__tests__/actions/exports.ts
  core/api/__tests__/models/destination.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/tasks/export/enqueue.ts
  core/api/__tests__/tasks/export/send.ts
  core/api/__tests__/tasks/export/sendBatch.ts
  core/api/__tests__/tasks/group/destroy.ts
  core/api/__tests__/tasks/profile/export.ts
  core/api/__tests__/tasks/run/internalRun.ts
  core/api/__tests__/tasks/schedule/run.ts
  core/api/src/actions/exports.ts
  core/api/src/config/routes.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Run.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/export.ts
  core/api/src/modules/ops/runs.ts
  core/api/src/tasks/export/enqueue.ts
  core/api/src/tasks/export/send.ts
  core/api/src/tasks/export/sendBatch.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/run/determineState.ts
  core/api/src/tasks/run/internalRun.ts
  core/api/src/tasks/schedule/run.ts
  core/web/components/export/list.tsx
  core/web/components/visualizations/totals.tsx
  core/web/pages/destinations.tsx
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
Labels: enhancement

#626 Update dependencies and remove packge-lock.json files
  apps/local-public/package-lock.json
  cli/package-lock.json
  cli/package.json
  clients/@grouparoo/web/package-lock.json
  clients/@grouparoo/web/package.json
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
  plugins/@grouparoo/bigquery/package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package-lock.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package-lock.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package-lock.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package-lock.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package-lock.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package-lock.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package-lock.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/package-lock.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package-lock.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package-lock.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package-lock.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package-lock.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/zendesk/package-lock.json
  plugins/@grouparoo/zendesk/package.json
  tools/merger/package-lock.json
Labels: bug, dependencies

#628 Explicitly type Destination#getRuns
  core/api/src/models/Destination.ts
Labels: bug

#634 Redirect to sign in page with 302 (temporary)
  core/web/client/client.ts
Labels: bug

#635 When times are null Export for start and end don't show any timestamps
  core/api/__tests__/actions/exports.ts
  core/api/src/models/Export.ts
  core/web/components/export/list.tsx
  core/web/pages/export/[guid]/edit.tsx
Labels: bug, enhancement

#625 Destination Export Types and Export Typecasting
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/models/destination.ts
  core/api/__tests__/models/destination/destination.ts
  core/api/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/api/__tests__/models/destination/plugins/exportProfile.ts
  core/api/__tests__/models/destination/plugins/exportProfiles.ts
  core/api/__tests__/models/destination/plugins/noExportMethods.ts
  core/api/src/actions/destinations.ts
  core/api/src/classes/plugin.ts
  core/api/src/models/Destination.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/ops/destination.ts
  core/web/pages/destination/[guid]/data.tsx
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export.ts
  plugins/@grouparoo/mailchimp/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/mysql/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/zendesk/src/lib/export/destinationMappingOptions.ts
Labels: enhancement

#636 Fix adding a team member from a team's page
  core/api/__tests__/actions/teamMembers.ts
  core/api/src/actions/teamMembers.ts
  core/web/pages/team/[guid]/teamMember/new.tsx
  core/web/pages/teamMember/new.tsx
Labels: bug

#638 Better faker results in factories that are unique with a math.random()
  core/api/__tests__/factories/app.ts
  core/api/__tests__/factories/destination.ts
  core/api/__tests__/factories/export.ts
  core/api/__tests__/factories/group.ts
  core/api/__tests__/factories/profilePropertyRule.ts
  core/api/__tests__/factories/schedule.ts
  core/api/__tests__/factories/source.ts
  core/api/__tests__/factories/team.ts
Labels: internal

#637 Do not import Profile Properties when the Source's mapping key is missing
  core/api/src/modules/internalRun.ts
  core/web/components/profile/getProfileDisplayName.ts
  core/web/components/profile/list.tsx
  plugins/@grouparoo/bigquery/src/lib/table-import/profileProperty.ts
  plugins/@grouparoo/mysql/src/lib/query-import/profileProperty.ts
  plugins/@grouparoo/mysql/src/lib/table-import/profileProperty.ts
  plugins/@grouparoo/postgres/src/lib/table-import/profileProperty.ts
Labels: enhancement

#639 Use Actionhero CLI for complex cli tasks
  apps/local-public/package.json
  apps/staging-public/package.json
  cli/templates/package.json
  core/api/bin/dev
  core/api/bin/updateTeamPermissions
  core/api/src/bin/grouparoo/mockEvents.ts
  core/api/src/bin/grouparoo/updateTeamPermissions.ts
  core/api/src/config/api.ts
  core/api/src/config/environment.ts
  core/api/src/config/serverInjection.ts
  core/api/src/initializers/session.ts
  core/api/src/server.ts
Labels: enhancement

#640 Destination Typecasting should not try to convert null profile properties
  core/api/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/api/src/modules/ops/destination.ts
Labels: bug

#641 Group Rules can be built from Profile#guid or Profile#createdAt
  core/api/__tests__/models/group/rules/topLevelGroupRules.ts
  core/api/__tests__/models/profilePropertyRule.ts
  core/api/src/actions/groups.ts
  core/api/src/migrations/000038-groupRuleProfileColumn.ts
  core/api/src/models/Group.ts
  core/api/src/models/GroupRule.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/web/pages/group/[guid]/rules.tsx
Labels: enhancement

#660 Revert "Bump typedoc from 0.18.0 to 0.19.0"
  core/package.json
Labels: bug, dependencies

#659 Destinations can only track one Group
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/actions/groups.ts
  core/api/__tests__/models/destination/destination.ts
  core/api/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/api/__tests__/models/destination/plugins/exportProfile.ts
  core/api/__tests__/models/destination/plugins/exportProfiles.ts
  core/api/__tests__/models/destinationGroup.ts
  core/api/__tests__/models/export.ts
  core/api/__tests__/models/group/group.ts
  core/api/__tests__/utils/specHelper.ts
  core/api/src/actions/destinations.ts
  core/api/src/actions/groups.ts
  core/api/src/index.ts
  core/api/src/migrations/000039-removeDestinationTrackAllGroups.ts
  core/api/src/models/Destination.ts
  core/api/src/models/DestinationGroup.ts
  core/api/src/models/Group.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/plugin.ts
  core/web/components/destination/profilePreview.tsx
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destinations.tsx
  core/web/utils/apiData.ts
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
Labels: enhancement
