Repository grouparoo/grouparoo, pull requests merged in 2020-09, with the labels that each got.

#674 Ensure all transactions have a corresponding rollback try/catch
  core/api/src/actions/groups.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Event.ts
  core/api/src/models/Import.ts
  core/api/src/modules/ops/group.ts
  core/api/src/modules/optionHelper.ts
  core/api/src/modules/plugin.ts
  core/api/src/tasks/run/internalRun.ts
Labels: bug

#677 Update Marketo dependencies to match monorepo
  plugins/@grouparoo/marketo/package.json
Labels: dependencies

#678 Share and centralize `destinationTypeConversions`
  core/api/__tests__/actions/destinations.ts
  core/api/src/actions/destinations.ts
  core/api/src/models/Destination.ts
  core/api/src/modules/destinationTypeConversions.ts
  core/api/src/modules/ops/destination.ts
Labels: bug, internal

#680 Fixes for group rule changes
  core/web/pages/group/[guid]/rules.tsx
Labels: bug

#681 Destination Export Fixes
  core/api/__tests__/models/destination/destination.ts
  core/api/src/models/Destination.ts
  core/api/src/modules/ops/export.ts
  core/api/src/tasks/profile/export.ts
  core/web/pages/destination/[guid]/data.tsx
Labels: bug

#682 Replace ts-node-dev with nodemon and ts-node for dev mode
  core/api/bin/dev
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: dependencies, internal

#683 Consider operation.op when checking if group rules have changed
  core/web/pages/group/[guid]/rules.tsx
Labels: bug

#686 Return cluster name in status:private action
  core/api/__tests__/actions/status.ts
  core/api/src/actions/status.ts
Labels: enhancement

#685 Only show ready-state sources as options for new Profile Property Rules
  core/web/pages/profilePropertyRules.tsx
Labels: bug

#687 Adds phone to Zendesk mapping options
  plugins/@grouparoo/zendesk/src/lib/export/destinationMappingOptions.ts
Labels: enhancement

#689 Exports compute old and new Properties only from current state of the Profile and the most recent sent Export
  core/api/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/api/__tests__/models/destination/plugins/exportProfile.ts
  core/api/__tests__/models/destination/plugins/exportProfiles.ts
  core/api/__tests__/models/export.ts
  core/api/__tests__/tasks/profile/export.ts
  core/api/bin/dev
  core/api/src/models/Destination.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/tasks/profile/export.ts
  core/web/components/export/list.tsx
  core/web/pages/export/[guid]/edit.tsx
Labels: bug, enhancement

#690 Do not block Group deletion if DestinationGroupMemberships exist
  core/api/__tests__/models/group/group.ts
  core/api/src/models/Group.ts
Labels: bug

#691 When Destination Group Memberships are removed by deleting a Group, a run is started
  core/api/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/api/__tests__/models/group/group.ts
  core/api/bin/dev
  core/api/src/actions/profiles.ts
  core/api/src/models/Group.ts
  core/api/src/models/Profile.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/profile.ts
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/runs.tsx
Labels: enhancement

#692 Simplify mysql disconnection
  plugins/@grouparoo/mysql/src/lib/connect.ts
Labels: enhancement

#693 Check that the run still exists before incrementing after sending exports
  core/api/src/modules/ops/destination.ts
Labels: bug

#694 Move mock events to new demo plugin
  .circleci/config.yml
  apps/staging-public/package.json
  core/README.md
  plugins/@grouparoo/demo/__tests__/integration/events.ts
  plugins/@grouparoo/demo/jest.config.js
  plugins/@grouparoo/demo/jest.setup.js
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/eventStream.ts
  plugins/@grouparoo/demo/tsconfig.json
Labels: enhancement, internal

#695 Reset Cluster Action
  core/api/__tests__/actions/cluster.ts
  core/api/src/actions/cluster.ts
  core/api/src/config/routes.ts
  core/web/components/settings/resetCluster.tsx
  core/web/pages/settings/[tab].tsx
Labels: enhancement

#696 Rename main executable to grouparoo.ts/.js, better checking for orphan processes
  core/api/__tests__/actions/cluster.ts
  core/api/bin/dev
  core/api/bin/start
  core/api/src/actions/cluster.ts
  core/api/src/grouparoo.ts
  core/web/__tests__/utils/specHelper.ts
Labels: internal

#709 Store & Display export.force
  core/api/__tests__/models/destination/plugins/exportProfile.ts
  core/api/__tests__/models/destination/plugins/exportProfiles.ts
  core/api/src/migrations/000040-addExportForce.ts
  core/api/src/models/Export.ts
  core/api/src/modules/ops/destination.ts
  core/web/components/export/list.tsx
  core/web/components/import/list.tsx
  core/web/pages/export/[guid]/edit.tsx
  core/web/pages/import/[guid]/edit.tsx
  package-lock.json
Labels: enhancement

#708 Use Grouparoo's fork of `node-marketo`
  plugins/@grouparoo/marketo/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/marketo/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/marketo/package.json
Labels: dependencies

#710 Add a description to @grouparoo/logger
  plugins/@grouparoo/logger/README.md
  plugins/@grouparoo/logger/package.json
Labels: documentation

#711 Relax scopes in associated getters
  core/api/src/classes/loggedModel.ts
  core/api/src/models/Destination.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Source.ts
  core/api/src/modules/mappingHelper.ts
  core/api/src/modules/ops/profilePropertyRule.ts
  core/api/src/modules/ops/source.ts
  core/api/src/modules/optionHelper.ts
  core/web/pages/settings/[tab].tsx
Labels: bug

#712 Onboarding
  core/api/__tests__/actions/setupSteps.ts
  core/api/__tests__/models/setupStep.ts
  core/api/src/actions/setupSteps.ts
  core/api/src/config/routes.ts
  core/api/src/initializers/setupSteps.ts
  core/api/src/migrations/000041-createSetupSteps.ts
  core/api/src/models/Permission.ts
  core/api/src/models/SetupStep.ts
  core/api/src/modules/ops/setupSteps.ts
  core/web/__tests__/integration/happyPath.ts
  core/web/components/visualizations/totals.tsx
  core/web/pages/about.tsx
  core/web/pages/index.tsx
Labels: enhancement

#713 Settings have a Type
  core/api/__tests__/actions/settings.ts
  core/api/__tests__/models/setting.ts
  core/api/__tests__/modules/plugin.ts
  core/api/__tests__/utils/specHelper.ts
  core/api/src/classes/plugin.ts
  core/api/src/initializers/events.ts
  core/api/src/initializers/settings.ts
  core/api/src/initializers/telemetry.ts
  core/api/src/migrations/000042-addSettingType.ts
  core/api/src/models/App.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Group.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/models/Setting.ts
  core/api/src/models/Source.ts
  core/api/src/modules/plugin.ts
  core/web/pages/settings/[tab].tsx
  core/web/utils/apiData.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/sourceOptions.ts
  plugins/@grouparoo/csv/src/lib/file-import/sourceOptions.ts
  plugins/@grouparoo/mailchimp/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/mysql/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/mysql/src/lib/table-import/sourceOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/postgres/src/lib/table-import/sourceOptions.ts
Labels: enhancement

#714 Update Router and Link paths
  core/api/src/actions/navigation.ts
  core/web/components/runs/list.tsx
  core/web/next.config.js
  core/web/pages/settings/[tab].tsx
Labels: bug

#716 Do not sort by Random()
  core/api/src/actions/profilePropertyRules.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/modules/internalRun.ts
  core/api/src/tasks/schedule/updateSchedules.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/eventStream.ts
  plugins/@grouparoo/mysql/src/lib/table-import/sourcePreview.ts
  plugins/@grouparoo/postgres/src/lib/table-import/sourcePreview.ts
Labels: bug, enhancement

#717 Don’t use RAND to sample for bigquery
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-schedule-options.js
  plugins/@grouparoo/bigquery/src/lib/util.ts
Labels: bug

#715 Setup page
  core/api/__tests__/actions/cluster.ts
  core/api/__tests__/actions/setupSteps.ts
  core/api/__tests__/models/setupStep.ts
  core/api/src/actions/cluster.ts
  core/api/src/actions/setupSteps.ts
  core/api/src/index.ts
  core/api/src/initializers/settings.ts
  core/api/src/models/SetupStep.ts
  core/api/src/modules/ops/setupSteps.ts
  core/web/__tests__/components/setupSteps/setupStepCard.tsx
  core/web/__tests__/integration/happyPath.ts
  core/web/components/navigation.tsx
  core/web/components/session/signIn.tsx
  core/web/components/setupSteps/setupStepCard.tsx
  core/web/components/visualizations/welcome.tsx
  core/web/pages/dashboard.tsx
  core/web/pages/settings/[tab].tsx
  core/web/pages/setup.tsx
  core/web/utils/apiData.ts
Labels: enhancement

#722 Check team permissions at boot
  core/api/src/bin/grouparoo/updateTeamPermissions.ts
  core/api/src/initializers/teamPermissions.ts
Labels: enhancement

#721 /object can route schedule links to the proper page
  core/web/pages/object/[guid].tsx
Labels: bug

#720 Setup Updates
  core/web/__tests__/components/setupSteps/setupStepCard.tsx
  core/web/components/navigation.tsx
  core/web/components/navigation/highlightingNavLink.tsx
  core/web/components/navigation/resqueFailedBadgeCount.tsx
  core/web/components/navigation/runningRunsBadge.tsx
  core/web/components/navigation/setupStepsNavProgressBar.tsx
  core/web/components/setupSteps/setupStepCard.tsx
  core/web/pages/_app.tsx
  core/web/pages/profilePropertyRules.tsx
  core/web/pages/setup.tsx
  core/web/utils/setupStepsHandler.ts
Labels: enhancement

#724 Grouparoo can update the descriptions and default values of Settings
  core/api/__tests__/models/setting.ts
  core/api/src/modules/plugin.ts
Labels: enhancement

#725 Fix SetupStepsNavProgressBar reload check and Router warnings with dynamic pages
  core/web/components/navigation.tsx
  core/web/components/navigation/setupStepsNavProgressBar.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/destination/new.tsx
  core/web/pages/setup.tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
  core/web/pages/source/new.tsx
Labels: bug

#723 Cast all High Water Marks to Strings
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/bigquery/src/lib/table-import/profiles.ts
  plugins/@grouparoo/mysql/src/lib/table-import/profiles.ts
  plugins/@grouparoo/postgres/src/lib/table-import/profiles.ts
Labels: bug

#726 Make "name" in Breadcrumb links clickable
  core/web/components/import/list.tsx
  core/web/components/log/list.tsx
  core/web/components/tabs.tsx
  core/web/components/tabs/group.tsx
  core/web/pages/object/[guid].tsx
Labels: enhancement

#739 Do not freak out if unknown marketo type
  plugins/@grouparoo/marketo/src/lib/export/destinationMappingOptions.ts
Labels: bug

#740 Do not update Group#calculatedAt within transaction (SequelizeConnectionAcquireTimeoutError)
  core/api/src/models/Group.ts
  core/api/src/modules/ops/group.ts
Labels: bug

#741 Stop bumping internal repo
  .github/workflows/bump-internal-repo.yml
Labels: internal

#742 Groups can be force-deleted
  core/api/__tests__/actions/groups.ts
  core/api/src/actions/groups.ts
  core/api/src/tasks/group/destroy.ts
  core/web/pages/group/[guid]/edit.tsx
Labels: enhancement

#743 Allow Destination Mapping Options for Required Types to be Converted
  core/web/pages/destination/[guid]/data.tsx
  plugins/@grouparoo/logger/src/lib/export/destinationMappingOptions.ts
Labels: bug

#744 Destinations can share the same App if they have different Options
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/models/destination/destination.ts
  core/api/src/models/Destination.ts
Labels: enhancement

#745 Format Destination ProfilePreview like the Export
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/actions/setupSteps.ts
  core/api/__tests__/models/destination/destination.ts
  core/api/src/models/Destination.ts
  core/api/src/modules/ops/destination.ts
  core/web/pages/destination/[guid]/data.tsx
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement

#746 Use stats API to load something about your Marketo instance for Test
  plugins/@grouparoo/marketo/src/lib/test.ts
Labels: enhancement

#748 Display Hydration errors and do not 500
  core/web/components/alerts/hydrationError.tsx
  core/web/components/layouts/main.tsx
  core/web/pages/404.tsx
  core/web/pages/_app.tsx
Labels: enhancement

#749 Fix Event load order
  core/api/src/initializers/events.ts
  core/api/src/models/ProfilePropertyRule.ts
Labels: bug

#750 Setup Steps Navigation Bar uses same color as background
  core/web/components/navigation/setupStepsNavProgressBar.tsx
  core/web/scss/grouparoo.scss
Labels: enhancement

#751 The Grouparoo Cache can be Cleared from Settings
  core/api/__tests__/actions/cluster.ts
  core/api/src/actions/cluster.ts
  core/api/src/config/routes.ts
  core/web/components/settings/clearCache.tsx
  core/web/pages/settings/[tab].tsx
Labels: enhancement

#753 Fix display bug when deleting Profile Property Rule
  core/web/components/alerts/hydrationError.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
Labels: bug

#752 Use HighWaterMark for Group Membership Calculations
  core/api/__tests__/models/group/group.ts
  core/api/__tests__/tasks/group/run.ts
  core/api/src/migrations/000043-addRunGroupHighWaterMark.ts
  core/api/src/models/Group.ts
  core/api/src/models/ProfileMultipleAssociationShim.ts
  core/api/src/models/Run.ts
  core/api/src/modules/ops/group.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/web/components/runs/list.tsx
  core/web/pages/run/[guid]/edit.tsx
Labels: enhancement

#779 Include .circleci files in docs build
  core/api/bin/publish-docs
Labels: internal

#783 Ensure that we do not touch updatedAt when incrementing a model and do not await SQL when a Transaction is in play
  core/api/src/config/sequelize.ts
  core/api/src/models/Group.ts
  core/api/src/modules/groupExport.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/event.ts
  core/api/src/modules/ops/group.ts
  core/api/src/modules/plugin.ts
  core/api/src/tasks/event/associateProfiles.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/import/associateProfile.ts
  core/api/src/tasks/profile/importAndUpdate.ts
  core/api/src/tasks/run/internalRun.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/scale.ts
Labels: bug

#785 Fix Group Run Calculation using groupHighWaterMark
  core/api/src/modules/ops/group.ts
  core/api/src/modules/ops/runs.ts
Labels: bug

#786 Only re-calculate groups in the ready state
  core/api/__tests__/tasks/group/updateCalculatedGroups.ts
  core/api/src/tasks/group/updateCalculatedGroups.ts
Labels: enhancement

#787 Use routable Resque pages
  core/web/components/tabs/resque.tsx
  core/web/next.config.js
  core/web/pages/resque.tsx
  core/web/pages/resque/delayed.tsx
  core/web/pages/resque/failed.tsx
  core/web/pages/resque/locks.tsx
  core/web/pages/resque/overview.tsx
  core/web/pages/resque/queue/[queue].tsx
  core/web/pages/resque/queue/index.tsx
  core/web/pages/resque/redis.tsx
  core/web/pages/resque/workers.tsx
Labels: enhancement
