Repository grouparoo/grouparoo, pull requests merged in 2020-10, with the labels that each got.

#793 Prevent "Job already enqueued at this time" Task errors
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: dependencies, enhancement

#794 Disconnect the App's connection after Options are set
  core/api/__tests__/models/app.ts
  core/api/src/initializers/clients.ts
  core/api/src/initializers/rpc.ts
  core/api/src/models/App.ts
  core/api/src/modules/ops/app.ts
Labels: bug

#797 Grouparoo Users can choose whether or not to start the next Schedule run against a Run with Errors or not
  core/api/__tests__/actions/settings.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/models/setting.ts
  core/api/__tests__/modules/plugin.ts
  core/api/__tests__/tasks/export/enqueue.ts
  core/api/src/actions/settings.ts
  core/api/src/initializers/settings.ts
  core/api/src/migrations/000044-settingTitleAndVariant.ts
  core/api/src/models/Run.ts
  core/api/src/models/Setting.ts
  core/api/src/modules/ops/export.ts
  core/api/src/modules/ops/profileProperty.ts
  core/api/src/modules/plugin.ts
  core/web/components/settings/identifyingProfilePropertyRule.tsx
  core/web/pages/settings/[tab].tsx
Labels: enhancement

#798 Automatically retry tasks from stuck workers
  core/api/src/config/tasks.ts
  core/package.json
  core/web/next.config.js
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: enhancement

#811 Bigquery v5.3.0
  plugins/@grouparoo/bigquery/__tests__/fixtures/query-import-property.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-property.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-schedule-options.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-source-filters.js
  plugins/@grouparoo/bigquery/package.json
Labels: dependencies

#812 Auth for DockerHub in CI
  .circleci/config.yml
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/publish/core.yml.template
  tools/merger/data/ci/publish/internal.yml.template
Labels: internal

#813 Button, Form, and Table Loading states
  .circleci/config.yml
  core/web/components/events/list.tsx
  core/web/components/loader.tsx
  core/web/components/loadingButton.tsx
  core/web/components/loadingTable.tsx
  core/web/components/profile/add.tsx
  core/web/components/profile/list.tsx
  core/web/components/profilePropertyRule/add.tsx
  core/web/components/schedule/add.tsx
  core/web/components/session/signIn.tsx
  core/web/components/settings/clearCache.tsx
  core/web/components/settings/identifyingProfilePropertyRule.tsx
  core/web/components/settings/importAndUpdate.tsx
  core/web/components/settings/resetCluster.tsx
  core/web/pages/account.tsx
  core/web/pages/apiKey/[guid]/edit.tsx
  core/web/pages/apiKey/new.tsx
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/app/new.tsx
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/destination/new.tsx
  core/web/pages/file/[guid]/edit.tsx
  core/web/pages/file/new.tsx
  core/web/pages/files.tsx
  core/web/pages/group/[guid]/edit.tsx
  core/web/pages/group/[guid]/rules.tsx
  core/web/pages/group/new.tsx
  core/web/pages/profile/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/profilePropertyRules.tsx
  core/web/pages/resque/delayed.tsx
  core/web/pages/resque/failed.tsx
  core/web/pages/resque/locks.tsx
  core/web/pages/resque/queue/[queue].tsx
  core/web/pages/resque/workers.tsx
  core/web/pages/run/[guid]/edit.tsx
  core/web/pages/settings/[tab].tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
  core/web/pages/source/[guid]/overview.tsx
  core/web/pages/source/[guid]/schedule.tsx
  core/web/pages/source/new.tsx
  core/web/pages/team/[guid]/edit.tsx
  core/web/pages/team/[guid]/members.tsx
  core/web/pages/team/initialize.tsx
  core/web/pages/team/new.tsx
  core/web/pages/teamMember/[guid]/edit.tsx
  core/web/pages/teamMember/new.tsx
  tools/merger/data/ci/base.yml.template
Labels: bug, enhancement

#727 Relax the validation requirements of email addresses
  core/api/__tests__/models/profileProperty.ts
  core/api/src/modules/ops/profileProperty.ts
  core/api/src/modules/validators/isEmail.ts
Labels: enhancement

#816 Sub-Pages for selecting new Sources and Destinations
  core/web/components/appSelectorList.tsx
  core/web/pages/app/new.tsx
  core/web/pages/destination/new.tsx
  core/web/pages/destination/new/[appGuid].tsx
  core/web/pages/destination/new/index.tsx
  core/web/pages/source/new.tsx
  core/web/pages/source/new/[appGuid].tsx
  core/web/pages/source/new/index.tsx
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/csv/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/logger/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/marketo/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/initializers/plugin.ts
  plugins/@grouparoo/salesforce/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
  plugins/@grouparoo/zendesk/src/initializers/plugin.ts
Labels: enhancement

#819 UI fixes
  core/api/src/modules/mappingHelper.ts
  core/web/components/schedule/add.tsx
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/profilePropertyRules.tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
  core/web/pages/source/[guid]/schedule.tsx
  core/web/pages/team/initialize.tsx
  core/web/pages/team/new.tsx
Labels: bug

#821 Actionhero v24.0.0-alpha.3
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: dependencies

#823 UI Fixes
  core/web/pages/imports/[guid].tsx
Labels: bug

#825 Page load errors
  core/package.json
  core/web/pages/about.tsx
  core/web/pages/object/[guid].tsx
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: bug

#828 Display out of date package versions against latest NPM tag
  core/api/__tests__/actions/plugins.ts
  core/api/__tests__/fixtures/actions/plugins.ts
  core/api/src/actions/plugins.ts
  core/api/src/utils/pluginDetails.js
  core/package.json
  core/web/pages/about.tsx
Labels: enhancement

#829 Start command replaces bash parent process with node process
  core/api/bin/dev
  core/api/bin/start
  core/api/src/grouparoo.ts
Labels: bug

#830 GrouparooSubscription uses telemetry URL
  core/api/src/modules/grouparooSubscription.ts
Labels: bug

#842 Update Actionhero and ah-sequelzie-plugin
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: dependencies

#843 Update dependencies
  cli/package.json
  core/api/__tests__/fixtures/actions/plugins.ts
  core/package.json
  package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: dependencies

#844 Sort team members in SQL to prevent typescript bug
  core/api/src/actions/teams.ts
Labels: bug

#845 Move @types to dependences so they are available for client install process
  core/package.json
Labels: bug, internal

#846 Clearer upgrade path information on About page
  core/api/__tests__/actions/plugins.ts
  core/api/src/actions/plugins.ts
  core/web/__tests__/pages/about.tsx
  core/web/hooks/useApi.ts
  core/web/pages/about.tsx
Labels: documentation, enhancement

#847 Notifiers and NewVersionNotifier
  core/api/__tests__/modules/notifiers.ts
  core/api/__tests__/notifiers/newVersionNotifier.ts
  core/api/src/actions/plugins.ts
  core/api/src/classes/notifier.ts
  core/api/src/initializers/notifiers.ts
  core/api/src/modules/pluginVersions.ts
  core/api/src/notifiers/newVersionNotifier.ts
  core/api/src/tasks/notifiers.ts
Labels: enhancement

#848 Test fixes
  core/api/src/models/ProfilePropertyRule.ts
  core/web/components/appSelectorList.tsx
  core/web/components/profile/add.tsx
  core/web/pages/apiKey/[guid]/edit.tsx
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/destination/new/[appGuid].tsx
  core/web/pages/group/[guid]/edit.tsx
  core/web/pages/group/[guid]/rules.tsx
  core/web/pages/group/new.tsx
  core/web/pages/profile/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/settings/[tab].tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
  core/web/pages/source/[guid]/schedule.tsx
  core/web/pages/source/new/[appGuid].tsx
  core/web/pages/team/[guid]/edit.tsx
  core/web/pages/teamMember/[guid]/edit.tsx
  core/web/utils/humanizePluginName.ts
  plugins/@grouparoo/email-authentication/src/components/emailSignIn.plugin.tsx
Labels: bug

#849 Stop runs when deleting parent Model
  core/api/__tests__/tasks/sweeper.ts
  core/api/src/initializers/settings.ts
  core/api/src/models/Group.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/tasks/sweeper.ts
  core/web/pages/object/[guid].tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
Labels: enhancement

#851 Use fixed version numbers when generating a new Grouparoo project
  cli/README.md
  cli/package.json
  cli/src/lib/generate.ts
  cli/src/lib/upgrade.ts
  cli/templates/package.json
  package-lock.json
  package.json
Labels: enhancement

#850 Enforce that a 'type' was selected when creating a new Profile Property Rule
  core/api/__tests__/models/profilePropertyRule.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/ops/source.ts
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
Labels: enhancement

#852 Use the same code for the event stream as the demo
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/eventStream.ts
  plugins/@grouparoo/demo/src/events.ts
Labels: enhancement

#853 App.connect() should be locked to ensure that only one worker builds the connection
  core/api/src/modules/ops/app.ts
Labels: bug

#856 @grouparoo/app-templates should be published to NPM
  plugins/@grouparoo/app-templates/package.json
Labels: bug

#858 Handle about page errors
  core/api/src/modules/pluginVersions.ts
  core/web/pages/about.tsx
Labels: bug

#875 Add tests for getChangedRowCount and rename `__hwm`
  core/api/src/models/Run.ts
  plugins/@grouparoo/app-templates/src/source/table/profiles.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-get-changed-row-count.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/bigquery/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/mysql/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/mysql/__tests__/table-import/profiles.ts
  plugins/@grouparoo/mysql/src/lib/table-import/getChangedRowCount.ts
  plugins/@grouparoo/postgres/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/postgres/src/lib/table-import-old/profiles.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-get-changed-row-count.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/snowflake/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/snowflake/__tests__/utils/nockHelper.ts
Labels: internal

#876 MySQL and Postgres apps use connection pooling
  plugins/@grouparoo/mysql/src/lib/connect.ts
  plugins/@grouparoo/postgres/src/lib/connect.ts
Labels: enhancement

#877 Store Profile Property Rules Cache in Redis
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
Labels: enhancement

#878 Log config
  apps/local-public/.env.example
  apps/staging-public/.env.example
  cli/templates/.env
  core/api/src/config/api.ts
  core/api/src/config/logger.ts
Labels: enhancement

#879 Use a script to build the API so we can message what's happening
  core/api/bin/build
  core/package.json
Labels: internal

#880 Grouparoo works with node v12.x -> v14.x (not v15)
  apps/local-public/package.json
  apps/staging-public/package.json
  cli/package.json
  cli/templates/package.json
  clients/@grouparoo/web/package.json
  core/package.json
  package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  tools/merger/package.json
Labels: bug, dependencies

#883 Refactor EventOps#associate to use sub-methods for each case
  core/api/src/modules/ops/event.ts
Labels: internal

#884 Use environment variable GROUPAROO_LOGS_PATH to set logging path for Grouparoo app
  core/api/src/config/api.ts
Labels: bug

#885 Scale command update for events and consolidation
  core/README.md
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/scale.ts
  plugins/@grouparoo/demo/src/events.ts
Labels: internal

#886 Use the URL Search Query or Environment Variable DATABASE_SSL to signal a SSL Postgres connection
  apps/local-public/.env.example
  apps/staging-public/.env.example
  cli/templates/.env
  core/api/src/config/logger.ts
  core/api/src/config/sequelize.ts
Labels: enhancement

#889 Allow the Grouparoo Database to use a self-signed SSL cert with DATABASE_SSL_SELF_SIGNED
  apps/local-public/.env.example
  apps/staging-public/.env.example
  cli/templates/.env
  core/api/src/config/sequelize.ts
Labels: enhancement

#890 Demo events don't require demo data
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/eventStream.ts
  plugins/@grouparoo/demo/src/sample_data.ts
  plugins/@grouparoo/demo/src/util/MockSession.ts
  plugins/@grouparoo/demo/src/util/postgres.ts
Labels: internal

#909 Actionhero v24.0.1
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: dependencies

#910 Use aws-sdk directly (remove @auth0/s3)
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/files-s3/src/classes/s3.ts
Labels: enhancement

#912 Use Nextjs v10
  core/package.json
Labels: dependencies

#911 Return undefined for profile properties with null or unknown input
  plugins/@grouparoo/app-templates/src/source/query/profileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperty.ts
  plugins/@grouparoo/bigquery/__tests__/query-import/import-property.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/import-property.ts
  plugins/@grouparoo/mysql/__tests__/query-import/import-property.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-property.ts
  plugins/@grouparoo/postgres/__tests__/query-import/import-property.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-property.ts
  plugins/@grouparoo/redshift/__tests__/query-import/connection.ts
  plugins/@grouparoo/redshift/__tests__/table-import/connection.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-property.js
  plugins/@grouparoo/snowflake/__tests__/query-import/import-property.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/profile-property.ts
Labels: bug

#914 In Postgres tests convert floats to fixed length decimals
  plugins/@grouparoo/postgres/__tests__/table-import/import-property.ts
Labels: internal

#916 WaitForLock should check that response is owned by caller
  core/api/src/modules/locks.ts
Labels: bug, internal
