Repository grouparoo/grouparoo, pull requests merged in 2020-11, with the labels that each got.

#888 Switch from lerna to pnpm
  .circleci/config.yml
  apps/local-public/package.json
  bin/preinstall
  bin/prepare
  core/api/bin/dev
  core/api/src/actions/resque.ts
  core/api/src/config/plugins.ts
  core/package.json
  core/web/next.config.js
  package.json
  plugins/@grouparoo/postgres/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/publish/core.yml.template
  tools/merger/src/ci_generate.js
  tools/spell-checker/check
Labels: dependencies

#937 Upgrade to Actionhero v24.0.3
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies, enhancement

#938 Count run totals with task
  core/api/__tests__/integration/runs/internalRun.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/modules/groupExport.ts
  core/api/__tests__/tasks/export/send.ts
  core/api/__tests__/tasks/export/sendBatch.ts
  core/api/__tests__/tasks/import/associateProfile.ts
  core/api/__tests__/tasks/profile/completeImport.ts
  core/api/__tests__/tasks/run/updateCounts.ts
  core/api/src/migrations/000048-addImportCreatedProfile.ts
  core/api/src/models/Import.ts
  core/api/src/models/Run.ts
  core/api/src/modules/groupExport.ts
  core/api/src/modules/ops/group.ts
  core/api/src/modules/ops/runs.ts
  core/api/src/modules/plugin.ts
  core/api/src/tasks/import/associateProfile.ts
  core/api/src/tasks/profile/completeImport.ts
  core/api/src/tasks/profileProperty/importProfileProperties.ts
  core/api/src/tasks/profileProperty/importProfileProperty.ts
  core/api/src/tasks/run/internalRun.ts
  core/api/src/tasks/run/updateCounts.ts
  plugins/@grouparoo/csv/__tests__/integration/csv.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/google-sheets-import.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
Labels: enhancement

#939 Filter profiles list by state
  core/api/__tests__/actions/profiles.ts
  core/api/src/actions/profiles.ts
  core/web/components/profile/list.tsx
  core/web/components/visualizations/totals.tsx
Labels: enhancement

#941 Manually Importing and Exporting a Profile updates state to ready
  core/api/src/actions/profiles.ts
  core/api/src/config/routes.ts
  core/api/src/modules/ops/profile.ts
  core/web/pages/profile/[guid]/edit.tsx
  core/web/utils/apiData.ts
Labels: enhancement

#940 When checking Profile Property dependencies rely on state
  core/api/__tests__/models/profileProperty.ts
  core/api/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/api/__tests__/tasks/profileProperty/importProfileProperty.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/modules/ops/event.ts
  core/api/src/tasks/profileProperty/importProfileProperties.ts
  core/api/src/tasks/profileProperty/importProfileProperty.ts
  plugins/@grouparoo/spec-helper/src/lib/workflows/import.ts
Labels: bug

#942 Batch Import Revisions
  core/api/src/migrations/000049-addStateIndxToProfiles.ts
  core/api/src/models/Profile.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/tasks/run/internalRun.ts
  core/web/components/profile/list.tsx
Labels: bug

#944 Properly consider alpha versions in semver ranges
  core/api/__tests__/actions/plugins.ts
  core/api/__tests__/notifiers/newVersionNotifier.ts
  core/api/src/modules/pluginVersions.ts
  core/api/src/notifiers/newVersionNotifier.ts
  core/package.json
  core/web/pages/about.tsx
  pnpm-lock.yaml
Labels: enhancement

#945 Directly mapped profile properties will not be marked as pending
  core/api/__tests__/models/profile.ts
  core/api/__tests__/models/profilePropertyRules/profilePropertyRule.ts
  core/api/__tests__/tasks/profileProperty/enqueue.ts
  core/api/src/migrations/000050-addDirectlyMappedToRules.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Source.ts
  core/api/src/modules/mappingHelper.ts
  core/api/src/modules/ops/profile.ts
Labels: enhancement

#962 Allow pnpm to install if deps are changing on CI (dependabot)
  .circleci/config.yml
  tools/merger/data/ci/base.yml.template
Labels: dependencies, internal

#967 Properly set mapping key/value in UI when editing an existing mapping
  core/web/pages/source/[guid]/mapping.tsx
Labels: bug

#968 Update lockfile and remove @types/jest from top-level project
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: internal

#970 Do not display Import or Export diff until complete
  core/web/components/export/diff.tsx
  core/web/components/export/list.tsx
  core/web/components/import/diff.tsx
  core/web/components/import/list.tsx
  core/web/pages/export/[guid]/edit.tsx
  core/web/pages/import/[guid]/edit.tsx
Labels: enhancement

#966 merge values in for performance and not crash with old properties
  core/api/__tests__/tasks/profile/completeImport.ts
  core/api/src/tasks/profile/completeImport.ts
Labels: bug

#971 Only allow one task worker when using a SQLite database
  core/api/src/config/sequelize.ts
Labels: enhancement

#972 New Dashboard
  core/api/__tests__/actions/groups.ts
  core/api/__tests__/actions/sources.ts
  core/api/src/actions/groups.ts
  core/api/src/actions/sources.ts
  core/api/src/config/routes.ts
  core/package.json
  core/web/components/visualizations/homepageWidgets.tsx
  core/web/components/visualizations/rollingChart.tsx
  core/web/components/visualizations/totals.tsx
  core/web/pages/dashboard.tsx
  core/web/pages/resque/overview.tsx
  core/web/utils/apiData.ts
Labels: enhancement

#973 Use type on destination same-ness calculation
  core/api/__tests__/models/destination/destination.ts
  core/api/src/models/Destination.ts
Labels: bug

#974 Update the ScheduleRuns on the homepage periodically
  core/web/components/visualizations/homepageWidgets.tsx
Labels: bug

#977 Update Batch Imports methods for BigQuery + Harden Batch Imports tests
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-properties.js
  plugins/@grouparoo/bigquery/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-properties.js
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/util.ts
Labels: bug

#978 Batch Import Updates
  core/api/__tests__/actions/sources.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/tasks/profileProperty/enqueue.ts
  core/api/src/actions/sources.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Run.ts
  core/api/src/tasks/profileProperty/enqueue.ts
  core/api/src/tasks/run/internalRun.ts
  core/web/components/destination/profilePreview.tsx
  core/web/components/events/list.tsx
  core/web/components/visualizations/homepageWidgets.tsx
  core/web/hooks/useApi.ts
  core/web/pages/apiKey/[guid]/edit.tsx
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/profile/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
  core/web/pages/source/[guid]/overview.tsx
  core/web/pages/source/[guid]/schedule.tsx
  core/web/pages/team/[guid]/edit.tsx
  core/web/pages/team/[guid]/members.tsx
  core/web/pages/teamMember/[guid]/edit.tsx
Labels: bug

#979 UNNEST all BigQuery IN queries
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-properties.js
  plugins/@grouparoo/bigquery/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/bigquery/src/lib/util.ts
Labels: enhancement

#976 Reset demo on setup
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/setup.ts
Labels: internal

#989 Update Actionhero and Node Resque
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#990 findOrCreateByUniqueProfileProperties locks the profile
  core/api/src/models/Profile.ts
  core/api/src/modules/ops/profile.ts
Labels: bug

#991 Ensure that there are no dupliacate Profile Property Values before making a Profile Property Rule unique
  core/api/__tests__/models/profilePropertyRules/profilePropertyRule.ts
  core/api/src/models/ProfilePropertyRule.ts
Labels: enhancement

#992 Lock the profile being modified within internal runs & Remove ProfilePropertyRule#Cache
  core/api/__tests__/integration/runs/internalRun.ts
  core/api/__tests__/models/group/calculatedGroup.ts
  core/api/__tests__/models/profile.ts
  core/api/__tests__/models/profileProperty.ts
  core/api/__tests__/models/profilePropertyRules/profilePropertyRule.ts
  core/api/src/actions/imports.ts
  core/api/src/actions/profiles.ts
  core/api/src/models/Destination.ts
  core/api/src/models/Group.ts
  core/api/src/models/Profile.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/internalRun.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/event.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/modules/ops/source.ts
  core/api/src/modules/plugin.ts
  core/api/src/tasks/profile/completeImport.ts
  core/api/src/tasks/run/internalRun.ts
  core/web/pages/resque/failed.tsx
Labels: bug

#994 Viewing the logs of a Profile includes Profile Proeprty logs
  core/api/__tests__/actions/logs.ts
  core/api/src/actions/logs.ts
  core/web/components/log/list.tsx
Labels: enhancement

#993 Grouparoo can be run locally without Redis
  apps/staging-public/.env.example
  cli/templates/.env
  core/api/src/config/redis.ts
  core/package.json
  core/web/components/visualizations/homepageWidgets.tsx
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/demo/src/groups.ts
  plugins/@grouparoo/demo/src/sample_data.ts
  plugins/@grouparoo/demo/src/util/shared.ts
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: enhancement

#995 Use Setting to configure Event assocation batch size
  core/api/src/initializers/settings.ts
  core/api/src/tasks/event/associateProfiles.ts
Labels: enhancement

#996 Demo can handle SQLite data
  apps/local-public/.env.example
  apps/staging-public/.env.example
  plugins/@grouparoo/demo/src/sample_data.ts
  plugins/@grouparoo/demo/src/util/database.ts
  plugins/@grouparoo/demo/src/util/postgres.ts
  plugins/@grouparoo/demo/src/util/shared.ts
Labels: internal

#997 Group runs are not complete until the Imports are imported
  core/api/__tests__/tasks/group/run.ts
  core/api/src/tasks/group/run.ts
Labels: bug

#998 Homepage group chart fixes
  core/api/src/actions/groups.ts
  core/web/components/visualizations/homepageWidgets.tsx
Labels: bug

#999 Ensure that Profiles used in Destination Preview have all properties (at least in the null state)
  core/api/__tests__/actions/destinations.ts
  core/api/src/actions/destinations.ts
Labels: bug

#1000 Do not use iLike in Actions for SQLite & Test Actions against SQLite
  .circleci/config.yml
  core/api/__tests__/actions/groups.ts
  core/api/__tests__/actions/profilePropertyRules.ts
  core/api/__tests__/actions/settings.ts
  core/api/src/actions/events.ts
  core/api/src/actions/profiles.ts
  core/api/src/models/Event.ts
  core/api/src/models/Setting.ts
  tools/merger/data/ci/core-local/job.yml.template
Labels: bug

#1018 Update Dependencies
  cli/package.json
  clients/@grouparoo/web/package.json
  clients/@grouparoo/web/src/uuid.ts
  core/api/src/actions/files.ts
  core/api/src/actions/profilePropertyRules.ts
  core/api/src/actions/setupSteps.ts
  core/api/src/classes/fileTransport.ts
  core/api/src/models/DestinationGroupMembership.ts
  core/api/src/models/ProfilePropertyRuleFilter.ts
  core/package.json
  core/web/__tests__/utils/specHelper.ts
  core/web/hooks/useRealtimeModelStream.ts
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/csv/src/lib/file-import/profiles.ts
  plugins/@grouparoo/csv/src/lib/file-import/sourcePreview.ts
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/files-s3/src/classes/s3.ts
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/logger/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/mysql/src/lib/connect.ts
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  tools/license-checker/check
Labels: dependencies

#1019 App, Source, Destination, and Profile Property Rule options gain displayName property
  core/api/__tests__/integration/events.ts
  core/api/src/initializers/events.ts
  core/api/src/migrations/000052-optionsDisplayName.ts
  core/api/src/models/App.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/modules/ops/profilePropertyRule.ts
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/source/[guid]/edit.tsx
  plugins/@grouparoo/app-templates/src/source/table/meta.ts
  plugins/@grouparoo/app-templates/src/source/table/pluginMethods.ts
  plugins/@grouparoo/app-templates/src/source/table/profilePropertyRuleOptions.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/import-property.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/csv/src/initializers/plugin.ts
  plugins/@grouparoo/demo/src/events.ts
  plugins/@grouparoo/demo/src/sample_data.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/logger/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/marketo/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-property.ts
  plugins/@grouparoo/mysql/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-property.ts
  plugins/@grouparoo/postgres/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/initializers/plugin.ts
  plugins/@grouparoo/salesforce/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/import-property.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
  plugins/@grouparoo/zendesk/src/initializers/plugin.ts
  pnpm-lock.yaml
Labels: enhancement

#1020 Relax @types packages version to *
  cli/package.json
  clients/@grouparoo/web/package.json
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sample-ui-plugin/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1021 Demo config
  plugins/@grouparoo/demo/config/purchases/1users.json
  plugins/@grouparoo/demo/config/purchases/2purchases.json
  plugins/@grouparoo/demo/config/purchases/app.json
  plugins/@grouparoo/demo/config/purchases/groups.json
  plugins/@grouparoo/demo/config/team.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/config.ts
  plugins/@grouparoo/demo/src/configFiles.ts
  plugins/@grouparoo/demo/src/sample_data.ts
  plugins/@grouparoo/demo/src/util/shared.ts
  pnpm-lock.yaml
Labels: internal

#1023 More Demo config
  core/api/src/initializers/codeConfig.ts
  core/api/src/modules/configLoaders/all.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/config.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/setup.ts
  plugins/@grouparoo/demo/src/configFiles.ts
  plugins/@grouparoo/demo/src/groups.ts
  plugins/@grouparoo/demo/src/sample_data.ts
Labels: internal

#1022 Sweep un-associated profileProperties
  core/api/__tests__/actions/groups.ts
  core/api/__tests__/actions/profilePropertyRules.ts
  core/api/__tests__/actions/runs.ts
  core/api/__tests__/actions/settings.ts
  core/api/__tests__/integration/runs/internalRun.ts
  core/api/__tests__/models/app.ts
  core/api/__tests__/models/group/calculatedGroup.ts
  core/api/__tests__/models/profile.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/models/setupStep.ts
  core/api/__tests__/models/teamMember.ts
  core/api/__tests__/modules/codeConfig.ts
  core/api/__tests__/modules/internalRun.ts
  core/api/__tests__/tasks/group/destroy.ts
  core/api/__tests__/tasks/group/exportToCSV.ts
  core/api/__tests__/tasks/group/run.ts
  core/api/__tests__/tasks/profile/export.ts
  core/api/__tests__/tasks/profileProperty/sweep.ts
  core/api/__tests__/tasks/schedule/updateSchedules.ts
  core/api/__tests__/tasks/sweeper.ts
  core/api/__tests__/tasks/telemetry.ts
  core/api/__tests__/utils/prepareSharedGroupTest.ts
  core/api/src/actions/cluster.ts
  core/api/src/classes/loggedModel.ts
  core/api/src/classes/retryableTask.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/tasks/profile/completeImport.ts
  core/api/src/tasks/profileProperty/importProfileProperties.ts
  core/api/src/tasks/profileProperty/importProfileProperty.ts
  core/api/src/tasks/profileProperty/sweep.ts
  core/api/src/tasks/run/internalRun.ts
  core/test.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: bug

#1024 Misc UI updates & Error Handling
  core/api/src/actions/swagger.ts
  core/api/src/initializers/clients.ts
  core/web/components/alerts/hydrationError.tsx
  core/web/components/navigation.tsx
  core/web/components/visualizations/homepageWidgets.tsx
  core/web/pages/_app.tsx
Labels: enhancement

#1027 Skip ProfilePropertyPluginMethod if not used for import plugins
  core/api/src/initializers/plugins.ts
  plugins/@grouparoo/csv/src/initializers/plugin.ts
  plugins/@grouparoo/csv/src/lib/file-import/profileProperty.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/profileProperty.ts
  plugins/@grouparoo/mailchimp/src/lib/import/connection.ts
  plugins/@grouparoo/mailchimp/src/lib/import/profileProperty.ts
  plugins/@grouparoo/mailchimp/src/lib/import/sourceRunPercentComplete.ts
Labels: enhancement, internal

#1033 Use JSON5 to parse Code Config files
  core/api/src/modules/configLoaders/all.ts
  core/package.json
  pnpm-lock.yaml
Labels: enhancement

#1026 code configure demo event property rules
  core/api/src/classes/codeConfig.ts
  core/api/src/modules/configLoaders/source.ts
  plugins/@grouparoo/demo/config/events/pageviews.json
  plugins/@grouparoo/demo/config/purchases/1users.json
  plugins/@grouparoo/demo/config/setup/team.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/setup.ts
  plugins/@grouparoo/demo/src/configFiles.ts
  plugins/@grouparoo/demo/src/events.ts
  plugins/@grouparoo/demo/src/sample_data.ts
  plugins/@grouparoo/demo/src/teams.ts
  plugins/@grouparoo/demo/src/util/shared.ts
Labels: internal
