Repository grouparoo/grouparoo, pull requests merged in 2020-07, with the labels that each got.

#435 Better locking for Hubspot list creation
  plugins/@grouparoo/hubspot/src/lib/export/listMethods.ts
Labels: bug

#446 ts-node-dev v1.0.0-pre.50
  core/api/bin/dev
  core/package.json
  package-lock.json
  plugins/@grouparoo/email-authentication/package.json
Labels: dependencies, enhancement

#447 Telemetry Reporting
  core/api/__tests__/actions/navigation.ts
  core/api/__tests__/fixtures/tasks/telemetry.ts
  core/api/__tests__/tasks/telemetry.ts
  core/api/jest.config.js
  core/api/src/actions/navigation.ts
  core/api/src/config/telemetry.ts
  core/api/src/initializers/settings.ts
  core/api/src/initializers/telemetry.ts
  core/api/src/tasks/telemetry.ts
  core/web/components/layouts/main.tsx
  core/web/components/navigation.tsx
  core/web/pages/_app.tsx
  core/web/pages/settings.tsx
Labels: enhancement

#448 Telemetry Documentation and code cleanup
  core/README.md
  core/api/__tests__/fixtures/tasks/telemetry.ts
  core/api/src/initializers/telemetry.ts
  core/api/src/modules/telemetryReporters.ts
  core/api/src/tasks/telemetry.ts
  documents/deployment/telemetry.md
Labels: enhancement

#449 Show more information about Runs
  core/api/__tests__/models/run.ts
  core/api/__tests__/tasks/groups/destroy.ts
  core/api/__tests__/tasks/groups/run.ts
  core/api/__tests__/tasks/runs/internalRun.ts
  core/api/src/migrations/000031-runLimitOffsetMethod.ts
  core/api/src/models/Run.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/runs/internalRun.ts
  core/web/components/layouts/main.tsx
  core/web/components/runs/list.tsx
  core/web/pages/run/[guid]/edit.tsx
Labels: enhancement

#451 Include documentation about third-party telemetry & Do not modify default behavior of third-party telemetry
  core/api/bin/dev
  core/api/bin/start
  core/package.json
  documents/deployment/telemetry.md
Labels: documentation

#450 Options can be set via Environment variables
  core/README.md
  core/api/__tests__/actions/apps.ts
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/actions/sources.ts
  core/api/__tests__/models/app.ts
  core/api/__tests__/models/destination.ts
  core/api/__tests__/models/source.ts
  core/api/src/actions/apps.ts
  core/api/src/actions/destinations.ts
  core/api/src/actions/sources.ts
  core/api/src/config/routes.ts
  core/api/src/models/App.ts
  core/api/src/modules/optionHelper.ts
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/source/[guid]/edit.tsx
  documents/deployment/security.md
  documents/images/api-key-permissions.png
  documents/images/environment-app-option.png
Labels: enhancement

#462 Uniformly update @types packages
  core/package-lock.json
  core/package.json
  package-lock.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: dependencies

#463 Update dependency: react-bootstrap@1.2.2
  core/package-lock.json
  core/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
Labels: dependencies

#452 Try to report errors with telemetry to the telemetry service
  core/api/__tests__/fixtures/tasks/telemetry.ts
  core/api/__tests__/tasks/telemetry.ts
  core/api/src/initializers/telemetry.ts
  core/api/src/tasks/telemetry.ts
  core/package-lock.json
  core/package.json
Labels: enhancement

#464 Run#highWaterMark is permanent, run#sourceOffset is per-run
  core/api/__tests__/models/app.ts
  core/api/__tests__/models/run.ts
  core/api/__tests__/models/schedule.ts
  core/api/__tests__/tasks/groups/destroy.ts
  core/api/__tests__/tasks/groups/run.ts
  core/api/__tests__/tasks/runs/internalRun.ts
  core/api/__tests__/utils/specHelper.ts
  core/api/bin/dev
  core/api/src/classes/plugin.ts
  core/api/src/migrations/000032-runHighWaterMarkAndSourceOffest.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/tasks/group/destroy.ts
  core/api/src/tasks/group/run.ts
  core/api/src/tasks/runs/internalRun.ts
  core/api/src/tasks/schedule/run.ts
  core/web/components/runs/list.tsx
  core/web/pages/run/[guid]/edit.tsx
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/bigquery/__tests__/table-import/next-filter.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/profiles.ts
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/nextFilter.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/profiles.ts
  plugins/@grouparoo/csv/src/lib/file-import/profiles.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/profiles.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/src/lib/table-import/nextFilter.ts
  plugins/@grouparoo/mysql/src/lib/table-import/profiles.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/table-import/nextFilter.ts
  plugins/@grouparoo/postgres/src/lib/table-import/profiles.ts
Labels: enhancement

#465 Disable next.js when testing api server
  core/api/jest.setup.js
  core/api/src/config/next.ts
  core/package-lock.json
  core/package.json
  core/web/jest.setup.js
Labels: internal

#466 Show Active Run count in Navigation and Dashboard
  core/api/src/actions/navigation.ts
  core/api/src/config/api.ts
  core/api/src/models/Permission.ts
  core/api/src/models/Run.ts
  core/web/components/icons.ts
  core/web/components/navigation.tsx
  core/web/components/visualizations/totals.tsx
  core/web/hooks/useRealtimeModelStream.ts
Labels: enhancement

#467 Move mutating methods to ModelOps [Refactor]
  core/api/__tests__/models/profile.ts
  core/api/__tests__/tasks/import/associateProfile.ts
  core/api/src/actions/groups.ts
  core/api/src/models/ApiKey.ts
  core/api/src/models/App.ts
  core/api/src/models/Destination.ts
  core/api/src/models/DestinationGroup.ts
  core/api/src/models/Event.ts
  core/api/src/models/Export.ts
  core/api/src/models/ExportImport.ts
  core/api/src/models/File.ts
  core/api/src/models/Group.ts
  core/api/src/models/GroupMember.ts
  core/api/src/models/GroupRule.ts
  core/api/src/models/Import.ts
  core/api/src/models/Log.ts
  core/api/src/models/Mapping.ts
  core/api/src/models/Permission.ts
  core/api/src/models/Profile.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/ProfilePropertyRuleFilter.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/models/Source.ts
  core/api/src/models/Team.ts
  core/api/src/models/TeamMember.ts
  core/api/src/modules/RuleOpsDictionary.ts
  core/api/src/modules/ops/app.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/event.ts
  core/api/src/modules/ops/group.ts
  core/api/src/modules/ops/import.ts
  core/api/src/modules/ops/profile.ts
  core/api/src/modules/ops/profilePropertyRule.ts
  core/api/src/modules/ops/runs.ts
  core/api/src/modules/ops/schedule.ts
  core/api/src/modules/ops/source.ts
  core/api/src/modules/ops/teamMember.ts
  documents/development/databases.md
Labels: internal

#468 Single-line if statements [Refactor]
  core/api/src/actions/account.ts
  core/api/src/actions/apps.ts
  core/api/src/actions/destinations.ts
  core/api/src/actions/events.ts
  core/api/src/actions/exports.ts
  core/api/src/actions/files.ts
  core/api/src/actions/groups.ts
  core/api/src/actions/imports.ts
  core/api/src/actions/logs.ts
  core/api/src/actions/profilePropertyRules.ts
  core/api/src/actions/resque.ts
  core/api/src/actions/runs.ts
  core/api/src/actions/schedules.ts
  core/api/src/actions/session.ts
  core/api/src/actions/sources.ts
  core/api/src/actions/teamMembers.ts
  core/api/src/actions/teams.ts
  core/api/src/actions/totals.ts
  core/api/src/initializers/session.ts
  core/api/src/models/ApiKey.ts
  core/api/src/models/App.ts
  core/api/src/models/Destination.ts
  core/api/src/models/DestinationGroup.ts
  core/api/src/models/DestinationGroupMembership.ts
  core/api/src/models/Event.ts
  core/api/src/models/Export.ts
  core/api/src/models/ExportImport.ts
  core/api/src/models/File.ts
  core/api/src/models/Group.ts
  core/api/src/models/GroupMember.ts
  core/api/src/models/GroupRule.ts
  core/api/src/models/Import.ts
  core/api/src/models/Log.ts
  core/api/src/models/Mapping.ts
  core/api/src/models/Option.ts
  core/api/src/models/Permission.ts
  core/api/src/models/Profile.ts
  core/api/src/models/ProfileProperty.ts
  core/api/src/models/ProfilePropertyRule.ts
  core/api/src/models/Run.ts
  core/api/src/models/Schedule.ts
  core/api/src/models/Setting.ts
  core/api/src/models/Source.ts
  core/api/src/models/Team.ts
  core/api/src/models/TeamMember.ts
  core/api/src/modules/ops/destination.ts
  core/api/src/modules/ops/profilePropertyRule.ts
  core/api/src/modules/ops/schedule.ts
  core/api/src/modules/ops/teamMember.ts
  core/api/src/modules/optionHelper.ts
  core/api/src/modules/plugin.ts
  core/api/src/tasks/imports/associateProfile.ts
Labels: internal

#469 Update dependencies
  clients/@grouparoo/web/package-lock.json
  clients/@grouparoo/web/package.json
  core/api/__tests__/actions/files.ts
  core/api/src/actions/files.ts
  core/package-lock.json
  core/package.json
  core/web/client/client.ts
  core/web/pages/file/new.tsx
  core/web/pages/files.tsx
  package-lock.json
  package.json
  plugins/@grouparoo/bigquery/package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/__tests__/integration/csv.ts
  plugins/@grouparoo/csv/package-lock.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package-lock.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package-lock.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package-lock.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package-lock.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package-lock.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package-lock.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/package-lock.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package-lock.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package-lock.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/sailthru/package-lock.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: dependencies, internal

#485 Update dependencies - Manually upgrade lodash version
  clients/@grouparoo/web/package-lock.json
  clients/@grouparoo/web/package.json
  core/package.json
  package-lock.json
  package.json
  plugins/@grouparoo/bigquery/package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package-lock.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package-lock.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package-lock.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package-lock.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package-lock.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package-lock.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package-lock.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/package-lock.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package-lock.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package-lock.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/sailthru/package-lock.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: bug, dependencies

#490 Runtime fixes for client `npm run dev`
  core/api/bin/dev
  core/api/src/server.ts
Labels: bug

#488 Product Concepts doc
  core/README.md
  documents/product/concepts.md
Labels: documentation

#491 Check the Grouparoo project for banned words
  .circleci/config.yml
  core/api/src/config/api.ts
  package.json
  tools/merger/src/ci_generate.js
  tools/spell-checker/check
Labels: enhancement, internal

#493 Group support for Array Properties
  core/api/__tests__/actions/profiles.ts
  core/api/__tests__/factories/profilePropertyRules.ts
  core/api/__tests__/models/group.ts
  core/api/__tests__/models/profile.ts
  core/api/__tests__/models/profilePropertyRule.ts
  core/api/__tests__/modules/groupExport.ts
  core/api/__tests__/tasks/profiles/importAndUpdate.ts
  core/api/src/actions/profiles.ts
  core/api/src/models/Group.ts
  core/api/src/modules/ops/group.ts
  core/package-lock.json
  core/package.json
  package-lock.json
  plugins/@grouparoo/bigquery/__tests__/fixtures/query-import-property.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-property.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-next-filter.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-schedule-options.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-source-filters.js
  plugins/@grouparoo/bigquery/__tests__/table-import/import-property.ts
  plugins/@grouparoo/bigquery/jest.setup.js
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/jest.setup.js
  plugins/@grouparoo/email-authentication/jest.setup.js
  plugins/@grouparoo/google-sheets/jest.setup.js
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/jest.setup.js
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/jest.setup.js
  plugins/@grouparoo/mailchimp/jest.setup.js
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/jest.setup.js
  plugins/@grouparoo/newrelic/jest.setup.js
  plugins/@grouparoo/postgres/jest.setup.js
  plugins/@grouparoo/sailthru/package.json
  tools/spell-checker/check
Labels: enhancement

#505 Use next.js v9.5.0
  core/api/src/classes/plugin.ts
  core/api/src/models/Group.ts
  core/package-lock.json
  core/package.json
  core/web/__tests__/components/navigation.tsx
  core/web/components/alerts/error.tsx
  core/web/components/alerts/success.tsx
  core/web/components/layouts/main.tsx
  core/web/components/loader.tsx
  core/web/components/profile/importAndUpdate.tsx
  core/web/components/profilePropertyRule/add.tsx
  core/web/components/resque/delayed.tsx
  core/web/components/resque/failed.tsx
  core/web/components/resque/locks.tsx
  core/web/components/resque/overview.tsx
  core/web/components/resque/queue.tsx
  core/web/components/resque/redis.tsx
  core/web/components/resque/workers.tsx
  core/web/components/schedule/add.tsx
  core/web/components/session/signIn.tsx
  core/web/components/session/signOut.tsx
  core/web/components/tabs/apiKey.tsx
  core/web/components/tabs/app.tsx
  core/web/components/tabs/destination.tsx
  core/web/components/tabs/event.tsx
  core/web/components/tabs/export.tsx
  core/web/components/tabs/file.tsx
  core/web/components/tabs/group.tsx
  core/web/components/tabs/import.tsx
  core/web/components/tabs/logs.tsx
  core/web/components/tabs/profile.tsx
  core/web/components/tabs/profilePropertyRule.tsx
  core/web/components/tabs/run.tsx
  core/web/components/tabs/source.tsx
  core/web/components/tabs/team.tsx
  core/web/components/tabs/teamMember.tsx
  core/web/components/visualizations/profileImageFromEmail.tsx
  core/web/components/visualizations/totals.tsx
  core/web/pages/404.tsx
  core/web/pages/session/sign-in.tsx
  core/web/pages/session/sign-out.tsx
  core/web/pages/team/initialize.tsx
  core/web/pages/team/new.tsx
  core/web/tsconfig.json
Labels: bug, dependencies

#507 Support source filters when there are no values present in the source
  plugins/@grouparoo/mysql/src/lib/table-import/sourceFilters.ts
  plugins/@grouparoo/postgres/src/lib/table-import/sourceFilters.ts
Labels: bug

#508 Event `all values` aggregation for Array Properties
  core/api/__tests__/integration/events.ts
  core/api/bin/mockEvents
  core/api/src/initializers/events.ts
  core/api/src/modules/ops/profile.ts
  core/web/components/profilePropertyRule/profilePreview.tsx
Labels: enhancement

#509 Mock next/link in test
  core/web/__tests__/components/navigation.tsx
Labels: internal

#506 Destination Plugins can opt into receiving profile property arrays
  core/api/__tests__/actions/destinations.ts
  core/api/__tests__/models/destination.ts
  core/api/__tests__/tasks/profiles/export.ts
  core/api/__tests__/utils/specHelper.ts
  core/api/src/actions/destinations.ts
  core/api/src/classes/plugin.ts
  core/api/src/config/routes.ts
  core/api/src/models/Destination.ts
  core/api/src/modules/ops/destination.ts
  core/web/pages/destination/[guid]/data.tsx
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/logger/src/initializers/plugin.ts
  plugins/@grouparoo/logger/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/sailthru/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/lib/export/exportArrayProperties.ts
Labels: enhancement

#511 Support Postgres schemas other than 'public'
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/connect.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/postgres/src/lib/table-import/sourceOptions.ts
Labels: enhancement

#512 Grouparoo Project Generator
  .circleci/config.yml
  cli/.npmignore
  cli/LICENSE.txt
  cli/README.md
  cli/__tests__/test.sh
  cli/package-lock.json
  cli/package.json
  cli/src/grouparoo.ts
  cli/src/lib/generate.ts
  cli/src/lib/logger.ts
  cli/src/lib/spawnCommand.ts
  cli/src/lib/upgrade.ts
  cli/templates/.env
  cli/templates/package.json
  cli/tsconfig.json
  lerna.json
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/cli/workflow.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/src/ci_generate.js
Labels: enhancement

#513 Update Docs to use new `npx grouparoo` CLI tool
  cli/.npmignore
  cli/package.json
  core/README.md
  documents/deployment/docker.md
  documents/deployment/getting-started.md
Labels: documentation

#515 Redshift Plugin (Source and Destination)
  .circleci/config.yml
  apps/staging-public/package.json
  core/api/src/modules/ops/source.ts
  core/web/pages/app/[guid]/edit.tsx
  core/web/pages/source/[guid]/edit.tsx
  plugins/@grouparoo/bigquery/src/lib/test.ts
  plugins/@grouparoo/postgres/src/lib/export/exportProfile.ts
  plugins/@grouparoo/redshift/.npmignore
  plugins/@grouparoo/redshift/LICENSE.txt
  plugins/@grouparoo/redshift/README.md
  plugins/@grouparoo/redshift/jest.config.js
  plugins/@grouparoo/redshift/jest.setup.js
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/redshift/public/@grouparoo/redshift/redshift.svg
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/tsconfig.json
Labels: enhancement

#516 Upgrade dependencies
  apps/local-public/package-lock.json
  clients/@grouparoo/web/package-lock.json
  clients/@grouparoo/web/package.json
  core/package.json
  core/web/__tests__/components/navigation.tsx
  plugins/@grouparoo/bigquery/package-lock.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package-lock.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/email-authentication/package-lock.json
  plugins/@grouparoo/email-authentication/package.json
  plugins/@grouparoo/files-local/package-lock.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package-lock.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package-lock.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package-lock.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/logger/package-lock.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package-lock.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mysql/package-lock.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package-lock.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package-lock.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/sailthru/package-lock.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/sample-ui-plugin/package-lock.json
  plugins/@grouparoo/sample-ui-plugin/package.json
Labels: dependencies

#518 Render Source, Destination and Profile Property pages if the App is unreachable
  core/api/__tests__/actions/profilePropertyRules.ts
  core/api/src/actions/profilePropertyRules.ts
  core/api/src/config/routes.ts
  core/web/components/destination/profilePreview.tsx
  core/web/components/navigation.tsx
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
Labels: bug, enhancement

#517 Show count of failed Resque tasks on Platform Navigation Link(s)
  core/api/__tests__/actions/profilePropertyRules.ts
  core/api/src/actions/profilePropertyRules.ts
  core/api/src/config/routes.ts
  core/web/components/destination/profilePreview.tsx
  core/web/components/navigation.tsx
  core/web/pages/destination/[guid]/data.tsx
  core/web/pages/destination/[guid]/edit.tsx
  core/web/pages/profilePropertyRule/[guid]/edit.tsx
  core/web/pages/source/[guid]/edit.tsx
  core/web/pages/source/[guid]/mapping.tsx
Labels: enhancement

#520 Read and Write permissions for Resque Actions
  core/api/src/actions/resque.ts
Labels: internal

#519 Store and compare TeamMember emails in lowercase
  core/api/__tests__/actions/sessions.ts
  core/api/__tests__/models/teamMember.ts
  core/api/src/actions/session.ts
  core/api/src/models/TeamMember.ts
  core/web/pages/teamMembers.tsx
Labels: bug

#521 Re-use single websocket connection for all instances of useRealtimeModelStream
  core/web/components/events/list.tsx
  core/web/components/log/list.tsx
  core/web/components/log/stream.tsx
  core/web/components/navigation.tsx
  core/web/components/visualizations/totals.tsx
  core/web/hooks/useRealtimeModelStream.ts
Labels: internal
