Repository grouparoo/grouparoo, pull requests merged in 2021-09, with the labels that each got.

#2236 Match `jest` versions and limit `victory` dependency to `ui-components`
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2237 Replace `victory` with `recharts`
  pnpm-lock.yaml
  ui/ui-components/components/runs/list.tsx
  ui/ui-components/components/visualizations/grouparooChart.tsx
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/components/visualizations/runDurations.tsx
  ui/ui-components/package.json
  ui/ui-components/pages/resque/overview.tsx
Labels: bug, plugin

#2238 Remove un-used packages from ui plugins
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: internal, plugin

#2229 Improvements to Eloqua error in case of bad credentials
  plugins/@grouparoo/eloqua/src/lib/client/client.ts
Labels: enhancement, plugin

#2269 Update `@sentry/*` packages
  plugins/@grouparoo/sentry/package.json
Labels: dependencies

#2270 Allow customer usage of Grouparoo with node.js >=12 (v16 included)
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  cli/__tests__/test.sh
  cli/package.json
  cli/templates/package.json
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  tools/merger/package.json
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: enhancement

#2259 Demo now generates a calculated full name property on profiles [179343542]
  plugins/@grouparoo/demo/config/shared/all/identity/apps/demo_calculated_property_app.json
  plugins/@grouparoo/demo/config/shared/all/identity/properties/full_name.json
  plugins/@grouparoo/demo/config/shared/all/identity/sources/demo_calculated_property_source.json
Labels: enhancement

#2274 Update `codeConfig` initializer start priority to be after settings
  core/src/initializers/codeConfig.ts
  core/src/initializers/coreVersionValidator.ts
  core/src/initializers/teamPermissions.ts
Labels: bug

#2277 Use date in `specHelper` directlyMapped property to ensure uniqueness
  plugins/@grouparoo/spec-helper/src/lib/factories/profile.ts
Labels: bug

#2129 Nodejs v16 Support
  .circleci/config.yml
  .nvmrc
  package.json
  pnpm-lock.yaml
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/plugin/mysql/steps.yml.template
  tools/merger/data/ci/ui/job.yml.template
  ui/ui-components/package.json
Labels: enhancement

#2279 `fake.unique` can use big numbers
  plugins/@grouparoo/spec-helper/src/lib/factories/profile.ts
Labels: bug

#2280 `validate` and `apply` cli commands prepare Settings
  core/__tests__/bin/apply.ts
  core/__tests__/bin/validate.ts
  core/__tests__/models/import.ts
  core/__tests__/models/setting.ts
  core/__tests__/modules/plugin.ts
  core/src/bin/apply.ts
  core/src/bin/validate.ts
  core/src/initializers/settings.ts
  core/src/modules/ops/setting.ts
  core/src/modules/plugin.ts
Labels: bug

#2276 Null dates don't show 1970 anymore
  pnpm-lock.yaml
  ui/ui-components/__tests__/__utils__/renderAndWait.tsx
  ui/ui-components/__tests__/components/__snapshots__/profilePreview.tsx.snap
  ui/ui-components/__tests__/components/profilePreview.tsx
  ui/ui-components/components/property/profilePreview.tsx
  ui/ui-components/package.json
Labels: bug

#2281 Abort publish if no dist folder
  bin/publish
Labels: bug, internal

#2284 Saw a test that was .only
  core/__tests__/tasks/profile/checkReady/smallerBatchSize.ts
Labels: internal

#2285 Update csv test location to new `records.csv`
  plugins/@grouparoo/csv/__tests__/integration/csv-remote.ts
  plugins/@grouparoo/csv/__tests__/remote-import/downloadAndRefreshFile.ts
  plugins/@grouparoo/csv/__tests__/remote-import/propertyOptions.ts
  plugins/@grouparoo/csv/__tests__/remote-import/recordProperties.ts
  plugins/@grouparoo/csv/__tests__/remote-import/recordProperty.ts
  plugins/@grouparoo/csv/__tests__/remote-import/records.ts
Labels: internal

#2289 When Grouparoo versions change, clear redis and resque
  core/__tests__/initializers/resque.ts
  core/src/initializers/resque.ts
  core/src/modules/reset.ts
Labels: enhancement

#2292 Use node.js v16.8.0 for CI
  .circleci/config.yml
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/ui/job.yml.template
  tools/merger/src/ci_generate.js
Labels: internal

#2294 Rename errant `profile*` files
  core/__tests__/models/destination/plugins/exportRecord.ts
  core/__tests__/models/destination/plugins/exportRecords.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/records.ts
  plugins/@grouparoo/csv/__tests__/file-import/recordProperty.ts
  plugins/@grouparoo/facebook/__tests__/integration/export-records-custom.ts
  plugins/@grouparoo/mysql/__tests__/table-import/record-property-rule-options.ts
  plugins/@grouparoo/postgres/__tests__/table-import/record-property-rule-options.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/record-property-rule-options.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/records.ts
  ui/ui-enterprise/pages/property/[id]/records.tsx
Labels: bug

#2296 Use `fa list` for Records icon
  core/src/actions/navigation.ts
  ui/ui-components/components/icons.ts
Labels: enhancement

#2299 remove csv file import test
  plugins/@grouparoo/csv/__tests__/file-import/recordProperty.ts
Labels: internal

#2298 fix: dont throw on `record:destroy` if it has already been deleted
  core/__tests__/tasks/record/destroy.ts
  core/src/tasks/record/destroy.ts
Labels: bug

#2300 fix: dont throw on `profile:destroy` if it has already been deleted (backports #2298)
  .circleci/config.yml
  core/__tests__/tasks/profile/destroy.ts
  core/src/tasks/profile/destroy.ts
  plugins/@grouparoo/csv/__tests__/integration/csv-remote.ts
  plugins/@grouparoo/csv/__tests__/remote-import/downloadAndRefreshFile.ts
  plugins/@grouparoo/csv/__tests__/remote-import/profileProperties.ts
  plugins/@grouparoo/csv/__tests__/remote-import/profileProperty.ts
  plugins/@grouparoo/csv/__tests__/remote-import/profiles.ts
  plugins/@grouparoo/csv/__tests__/remote-import/propertyOptions.ts
  pnpm-lock.yaml
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/ui/job.yml.template
  tools/merger/src/ci_generate.js
Labels: bug

#2301 Sort chart keys on dashboard
  ui/ui-components/components/visualizations/homepageWidgets.tsx
Labels: bug

#2302 Request plugin information in parallel
  core/src/modules/plugins.ts
Labels: enhancement

#2303 Show 'pending' when displaying incomplete time ranges
  ui/ui-components/components/durationTime.tsx
  ui/ui-components/components/export/list.tsx
  ui/ui-components/components/import/list.tsx
  ui/ui-components/components/runs/list.tsx
  ui/ui-components/pages/export/[id]/edit.tsx
  ui/ui-components/pages/exportProcessor/[id]/edit.tsx
  ui/ui-components/pages/exportProcessors.tsx
  ui/ui-components/pages/import/[id]/edit.tsx
  ui/ui-components/pages/run/[id]/edit.tsx
Labels: enhancement

#2306 only show "add multiple properties" if possible to do
  ui/ui-components/pages/source/[id]/overview.tsx
Labels: bug

#2307 Store invalid RecordProperties and do not throw
  core/__tests__/bin/__snapshots__/sync.ts.snap
  core/__tests__/models/record/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/models/recordProperty/recordProperty.ts
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/tasks/recordProperty/importRecordProperties.ts
  core/__tests__/tasks/recordProperty/importRecordProperty.ts
  core/src/actions/properties.ts
  core/src/migrations/000082-addRecordPropertyInvalidValue.ts
  core/src/models/Export.ts
  core/src/models/RecordProperty.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/recordProperty.ts
  ui/ui-components/components/record/arrayRecordPropertyList.tsx
  ui/ui-components/components/record/list.tsx
  ui/ui-components/pages/record/[id]/edit.tsx
Labels: enhancement

#2305 Reducing Imports under load
  cli/__tests__/test.sh
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/models/record/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/models/record/snapshot-testing.ts
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/snapshots/snapshot-testing.ts
  core/__tests__/tasks/group/updateCalculatedGroups.ts
  core/__tests__/tasks/run/tick.ts
  core/src/models/Group.ts
  core/src/modules/ops/recordProperty.ts
  core/src/tasks/group/updateCalculatedGroups.ts
Labels: enhancement

#2309 Only worker processes run migrations
  apps/staging-enterprise/__tests__/cli
  core/src/config/sequelize.ts
  core/src/config/tasks.ts
  core/src/modules/cache.ts
  core/src/modules/cli.ts
  core/src/modules/grouparooSubscription.ts
  core/src/tasks/system/status/status.ts
Labels: enhancement

#2310 Upgrade to Actionhero v27.1.2
  core/package.json
  core/src/classes/codeConfig.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2311 Retry RecordProperty Import errors outside of batch
  core/__tests__/tasks/recordProperty/importRecordProperties.ts
  core/src/tasks/recordProperty/importRecordProperties.ts
Labels: enhancement

#2313 data use DATETIME when seeding demo data for older mysql
  plugins/@grouparoo/demo/src/connections/mysql.ts
Labels: internal

#2318 Actionhero v27.1.4
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2320 Moving agent value to X-Grouparoo-Client header
  ui/ui-components/client/client.ts
Labels: bug

#2321 remove unused tests in sample apps
  apps/staging-community/__tests__/test.js
  apps/staging-enterprise/__tests__/test.js
Labels: internal

#2319 `grouaproo run` should end if there are Imports that had an error
  core/__tests__/tasks/system/status/status.ts
  core/src/modules/statusReporters.ts
Labels: bug

#2297 Braze destination plugin
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/braze/.npmignore
  plugins/@grouparoo/braze/LICENSE.txt
  plugins/@grouparoo/braze/README.md
  plugins/@grouparoo/braze/__tests__/.env.example
  plugins/@grouparoo/braze/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/braze/__tests__/export/export-records.ts
  plugins/@grouparoo/braze/__tests__/fixtures/export-records.js
  plugins/@grouparoo/braze/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/braze/jest.config.js
  plugins/@grouparoo/braze/jest.setup.js
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/braze/public/@grouparoo/braze/braze.png
  plugins/@grouparoo/braze/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/braze/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/braze/src/initializers/plugin.ts
  plugins/@grouparoo/braze/src/lib/client/campaign.ts
  plugins/@grouparoo/braze/src/lib/client/client.ts
  plugins/@grouparoo/braze/src/lib/client/user.ts
  plugins/@grouparoo/braze/src/lib/connect.ts
  plugins/@grouparoo/braze/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/braze/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/braze/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/braze/src/lib/export/exportRecords.ts
  plugins/@grouparoo/braze/src/lib/test.ts
  plugins/@grouparoo/braze/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#2323 Grouparoo Cloud CLI commands
  apps/staging-community/.env.example
  apps/staging-config/.env.example
  apps/staging-enterprise/.env.example
  core/__tests__/bin/ci.ts
  core/__tests__/bin/deploy.ts
  core/__tests__/bin/pack.ts
  core/__tests__/bin/push.ts
  core/__tests__/fixtures/codeConfig/additional-file-types/config.js
  core/__tests__/fixtures/codeConfig/additional-file-types/config.json
  core/__tests__/fixtures/codeConfig/additional-file-types/markdown.md
  core/package.json
  core/src/bin/ci.ts
  core/src/bin/deploy.ts
  core/src/bin/pack.ts
  core/src/bin/push.ts
  core/src/modules/cloud.ts
  core/src/modules/cloudCli.ts
  pnpm-lock.yaml
Labels: enhancement

#2326 Type specHelper factoires
  plugins/@grouparoo/spec-helper/src/lib/factories/apiKey.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/app.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/destination.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/export.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/exportProcessor.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/group.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/import.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/log.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/notification.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/properties.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/property.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/record.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/run.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/schedule.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/source.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/team.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/teamMember.ts
Labels: internal

#2324 Model exclusions
  core/__tests__/integration/multipleModels.ts
  core/__tests__/models/mapping.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/plugin.ts
  core/src/actions/groups.ts
  core/src/actions/properties.ts
  core/src/actions/records.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/models/GroupMember.ts
  core/src/models/Property.ts
  core/src/models/RecordProperty.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/record.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/mappingHelper.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/schedule.ts
  core/src/modules/plugin.ts
  core/src/tasks/recordProperty/importRecordProperties.ts
  core/src/tasks/recordProperty/importRecordProperty.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/model.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/record.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-components/components/record/list.tsx
  ui/ui-components/pages/destination/[id]/data.tsx
  ui/ui-components/pages/group/[id]/rules.tsx
  ui/ui-components/pages/properties.tsx
  ui/ui-components/pages/record/[id]/edit.tsx
  ui/ui-components/pages/source/[id]/mapping.tsx
Labels: blocked

#2331 fix: `grouparoo config` runs migrations
  core/src/config/sequelize.ts
  ui/ui-config/__tests__/bin/config.ts
  ui/ui-config/dist/bin/config.js
Labels: bug

#2332 Optimize `bulkDeletes` query cleaning up old RecordProperties after update
  core/__tests__/models/record/record.ts
  core/src/modules/ops/record.ts
Labels: enhancement

#2333 `status:public` is an unauthenticated action
  core/src/actions/status.ts
  ui/ui-components/utils/apiData.ts
Labels: enhancement

#2335 Support changing collection of Property options in UI
  ui/ui-components/components/visualizations/grouparooChart.tsx
  ui/ui-components/pages/property/[id]/edit.tsx
Labels: bug

#2336 Recurring Schedules run immediately after creation or update
  core/__tests__/models/schedule.ts
  core/src/models/Run.ts
  core/src/models/Schedule.ts
  core/src/modules/ops/schedule.ts
  core/src/tasks/schedule/enqueueRuns.ts
  ui/ui-components/pages/destinations.tsx
  ui/ui-components/pages/groups.tsx
Labels: enhancement

#2338 Reload the record if import-export failed
  core/src/modules/ops/record.ts
  ui/ui-components/pages/record/[id]/edit.tsx
Labels: bug

#2345 Update to axios@v0.21.4
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/spec-helper/package.json
  pnpm-lock.yaml
  ui/ui-components/package.json
Labels: dependencies

#2344 Update cloudwatch ENV variables to be generic for AWS
  apps/staging-community/.env.example
  apps/staging-config/.env.example
  apps/staging-enterprise/.env.example
  plugins/@grouparoo/cloudwatch/README.md
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/cloudwatch/src/initializers/plugin.ts
Labels: enhancement

#2339 Create a PR template w security review
  .github/pull_request_template.md
Labels: internal

#2347 chore: add more details to Braze api key and endpoint.
  plugins/@grouparoo/braze/src/initializers/plugin.ts
Labels: documentation, plugin

#2328 Mixpanel Integration ID.
  plugins/@grouparoo/mixpanel/__tests__/fixtures/export-records.js
  plugins/@grouparoo/mixpanel/src/lib/client/mixpanel.ts
Labels: enhancement, plugin

#2350 `RecordProperties` do not create Logs
  core/__tests__/actions/logs.ts
  core/__tests__/models/recordProperty/recordProperty.ts
  core/src/actions/logs.ts
  core/src/classes/commonModel.ts
  core/src/classes/loggedModel.ts
  core/src/models/Export.ts
  core/src/models/Filter.ts
  core/src/models/GroupMember.ts
  core/src/models/GroupRule.ts
  core/src/models/GrouparooModel.ts
  core/src/models/Import.ts
  core/src/models/Log.ts
  core/src/models/RecordProperty.ts
  core/src/models/Run.ts
  core/src/models/Session.ts
  ui/ui-components/components/log/list.tsx
Labels: enhancement

#2346 Rename configs and create options migrations.
  plugins/@grouparoo/demo/config/shared/all/salesforce/destinations/salesforce.json
  plugins/@grouparoo/salesforce/src/migrations/000002-plugin-salesforce-options-profile-to-records.ts
Labels: bug, plugin

#2352 Sources produce codeConfig with `modelId`
  core/__tests__/modules/configWriter.ts
  core/src/models/Source.ts
Labels: bug

#2349 Add Models to UI Config NavBar
  core/__tests__/actions/navigation.ts
  core/src/actions/navigation.ts
  ui/ui-components/components/icons.ts
Labels: enhancement
