Repository grouparoo/grouparoo, pull requests merged in 2021-12, with the labels that each got.

#2577 add appRefreshQuery to /apps
  ui/ui-components/.eslintrc.json
  ui/ui-components/pages/apps.tsx
Labels: enhancement

#2594 UI bug fixes -- query schedules textarea, `/sources`
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
  ui/ui-components/pages/model/[modelId]/sources.tsx
Labels: bug

#2597 Remove unused dependency `date-fns`
  core/package.json
  pnpm-lock.yaml
  ui/ui-components/package.json
Labels: dependencies

#2595 Groups config to match shape of other configs
  core/public/templates/groups/calculated/{{{id}}}.js.template
  core/public/templates/groups/manual/{{{id}}}.js.template
  core/src/models/Group.ts
Labels: bug

#2615 remove unused package `mime`
  core/package.json
  pnpm-lock.yaml
Labels: dependencies

#2596 Add `location` as App option for BigQuery
  plugins/@grouparoo/bigquery/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/bigquery/src/lib/connect.ts
Labels: enhancement

#2579 Handle facebook when there are 100s of audiences
  plugins/@grouparoo/facebook/__tests__/fixtures/integration/export-records-custom.js
  plugins/@grouparoo/facebook/__tests__/integration/export-records-custom.ts
  plugins/@grouparoo/facebook/src/lib/export/audienceMethods.ts
Labels: bug

#2634 Import all Sample Profiles
  core/__tests__/actions/records/importAndExport.ts
  core/src/actions/records.ts
  core/src/config/routes.ts
  core/src/initializers/codeConfig.ts
  core/src/modules/ops/record.ts
  ui/ui-components/components/record/List.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-components/utils/eventHandlers.ts
  ui/ui-components/utils/recordsHandler.ts
  ui/ui-config/pages/model/[modelId]/records.tsx
Labels: enhancement

#2636 App refresh timing
  core/__tests__/models/appRefreshQuery.ts
  core/src/models/AppRefreshQuery.ts
  core/src/tasks/appRefreshQuery/run.ts
Labels: bug

#2632 App Refresh Query UI fix on `/apps`
  ui/ui-components/pages/apps.tsx
Labels: bug

#2637 App Refresh Query UI: hitting cancel on an empty query
  ui/ui-components/pages/app/[id]/refresh.tsx
Labels: bug

#2640 Do not log sample record seeding if there are none
  core/src/initializers/codeConfig.ts
Labels: enhancement

#2641 Display list of Destinations on `record/edit` page
  core/__tests__/actions/records/records.ts
  core/src/actions/records.ts
  ui/ui-components/pages/model/[modelId]/record/[recordId]/edit.tsx
Labels: enhancement

#2643 add deprecation warning
  core/src/bin/generate.ts
  core/src/modules/deprecation.ts
Labels: enhancement

#2645 show less on `/apps` in config mode
  ui/ui-components/pages/apps.tsx
Labels: enhancement

#2639 Clarify UI disabled logic when object is locked
  core/__tests__/integration/errors.ts
  core/src/migrations/000054-lockedString.ts
  core/src/migrations/000055-errorLevelForExports.ts
  core/src/migrations/000058-runDestinationId.ts
  core/src/migrations/000089-createAppDataRefreshes.ts
  core/src/models/ApiKey.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Export.ts
  core/src/models/Group.ts
  core/src/models/GroupRule.ts
  core/src/models/GrouparooModel.ts
  core/src/models/Notification.ts
  core/src/models/Permission.ts
  core/src/models/Property.ts
  core/src/models/RecordProperty.ts
  core/src/models/Run.ts
  core/src/models/Schedule.ts
  core/src/models/Setting.ts
  core/src/models/Source.ts
  core/src/models/Team.ts
  core/src/models/TeamMember.ts
  core/src/modules/lockableHelper.ts
  ui/ui-components/components/Permissions.tsx
  ui/ui-components/components/settings/SettingCard.tsx
  ui/ui-components/pages/account.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/app/[id]/refresh.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/group/[groupId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/group/[groupId]/rules.tsx
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/mapping.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
  ui/ui-components/pages/team/[id]/edit.tsx
  ui/ui-components/pages/teamMember/[id]/edit.tsx
  ui/ui-components/pages/teams.tsx
  ui/ui-enterprise/pages/apiKey/[id]/edit.tsx
Labels: bug

#2646 Test sample records when created by trying an import
  core/__tests__/actions/records/create.ts
  core/__tests__/actions/records/importAndExport.ts
  core/__tests__/actions/records/records.ts
  core/src/actions/records.ts
  core/src/initializers/codeConfig.ts
  core/src/modules/ops/record.ts
Labels: bug, enhancement

#2649 Only show <hr> if Group add form is present
  ui/ui-components/pages/model/[modelId]/record/[recordId]/edit.tsx
Labels: enhancement

#2668 add space after app environment var options
  ui/ui-components/pages/app/[id]/edit.tsx
Labels: enhancement

#2616 Add Sample Record Card to Model Overview Page
  ui/ui-community/next-env.d.ts
  ui/ui-components/components/lib/ManagedCard.tsx
  ui/ui-components/components/record/AddSampleRecordForm.tsx
  ui/ui-components/components/record/AddSampleRecordModal.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/hooks/usePrevious.ts
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-config/next-env.d.ts
  ui/ui-enterprise/next-env.d.ts
Labels: enhancement

#2671 use saved refresh query instead of props
  ui/ui-components/pages/app/[id]/refresh.tsx
Labels: bug

#2666 Pipedrive fix retrieving exportRecord method
  plugins/@grouparoo/pipedrive/__tests__/export-organizations/export-record.ts
  plugins/@grouparoo/pipedrive/__tests__/export-persons/export-record.ts
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-organizations/destination-mapping-options.js
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-organizations/export-record.js
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-persons/destination-mapping-options.js
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-persons/export-record.js
  plugins/@grouparoo/pipedrive/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/pipedrive/src/initializers/plugin.ts
  plugins/@grouparoo/pipedrive/src/lib/common/exportRecord.ts
  plugins/@grouparoo/pipedrive/src/lib/export-organizations/exportRecord.ts
  plugins/@grouparoo/pipedrive/src/lib/export-persons/exportRecord.ts
Labels: bug

#2664 Use unescaped values for mustache strings
  core/__tests__/classes/codeConfig.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/property/dependsOn.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/source/source.ts
  core/__tests__/modules/mustacheUtils.ts
  core/__tests__/modules/plugin.ts
  core/src/modules/ops/property.ts
  core/src/modules/plugin.ts
  plugins/@grouparoo/app-templates/public/templates/query-property/{{{id}}}.js.template
  plugins/@grouparoo/bigquery/__tests__/integration/log-checking.ts
  plugins/@grouparoo/bigquery/__tests__/query-import/import-property.ts
  plugins/@grouparoo/calculated-property/__tests__/import/import-property.ts
  plugins/@grouparoo/calculated-property/__tests__/integration/calculated-property-import.ts
  plugins/@grouparoo/calculated-property/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/calculated-property/src/lib/propertyOptions.ts
  plugins/@grouparoo/clickhouse/__tests__/integration/clickhouse-query-import.ts
  plugins/@grouparoo/clickhouse/__tests__/query-import/import-property.ts
  plugins/@grouparoo/demo/config/users/properties/full_name.json
  plugins/@grouparoo/mongo/__tests__/integration/log-checking.ts
  plugins/@grouparoo/mongo/__tests__/query-import/import-property.ts
  plugins/@grouparoo/mongo/public/templates/query-property/{{{id}}}.js.template
  plugins/@grouparoo/mysql/__tests__/integration/mysql-query-import.ts
  plugins/@grouparoo/mysql/__tests__/query-import/import-property.ts
  plugins/@grouparoo/postgres/__tests__/integration/log-checking.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-query-import.ts
  plugins/@grouparoo/postgres/__tests__/query-import/import-property.ts
  plugins/@grouparoo/postgres/src/lib/validateQuery.ts
  plugins/@grouparoo/redshift/__tests__/integration/redshift-query-import.ts
  plugins/@grouparoo/snowflake/__tests__/integration/log-checking.ts
  plugins/@grouparoo/snowflake/__tests__/query-import/import-property.ts
  plugins/@grouparoo/sqlite/__tests__/integration/log-checking.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-query-import.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/import-property.ts
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
Labels: bug

#2675 Use Toasts for Success and Error Alerts
  ui/ui-components/components/alerts/Error.tsx
  ui/ui-components/components/alerts/Success.tsx
  ui/ui-components/components/alerts/Toast.tsx
  ui/ui-components/components/layouts/Main.tsx
  ui/ui-components/components/settings/ResetCluster.tsx
  ui/ui-components/hooks/useApi.ts
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/mapping.tsx
  ui/ui-components/utils/ensureMatchingModel.ts
  ui/ui-components/utils/errorHandler.ts
  ui/ui-config/pages/app/new/index.tsx
Labels: enhancement

#2676 Move Toasts to bottom right and show close button
  ui/ui-components/components/alerts/Toast.tsx
  ui/ui-components/components/layouts/Main.tsx
Labels: enhancement

#2677 Replace Record Preview in Property Editor with Sample Record Card
  core/__tests__/actions/properties.ts
  core/src/actions/properties.ts
  ui/ui-components/__tests__/components/__snapshots__/recordPreview.tsx.snap
  ui/ui-components/__tests__/components/recordPreview.tsx
  ui/ui-components/components/lib/ManagedCard.tsx
  ui/ui-components/components/model/overview/ModelOverviewSampleRecord.tsx
  ui/ui-components/components/property/PropertySampleRecord.tsx
  ui/ui-components/components/property/RecordPreview.tsx
  ui/ui-components/components/record/AddSampleRecordForm.tsx
  ui/ui-components/components/record/AddSampleRecordModal.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/hooks/useDebouncedValue.ts
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
Labels: enhancement

#2683 Model overview page fixes
  ui/ui-components/components/badges/StateBadge.tsx
  ui/ui-components/components/lib/entity/EntityInfoHeader.tsx
  ui/ui-components/components/lib/entity/EntityList.tsx
  ui/ui-components/components/model/overview/ModelOverviewDestinations.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
Labels: bug, enhancement

#2688 Set CloudWatch log retention to 90 days by default, allow customization
  plugins/@grouparoo/cloudwatch/README.md
  plugins/@grouparoo/cloudwatch/src/initializers/plugin.ts
Labels: enhancement

#2692 List all environment variables
  core/src/config/batchSize.ts
  documents/environment-variables.md
Labels: documentation

#2696 Scope Group Rules with topLevelRules to just this model
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/models/group/rules/topLevelGroupRules.ts
  core/__tests__/utils/prepareSharedGroupTest.ts
  core/src/models/Group.ts
  ui/ui-components/pages/model/[modelId]/group/[groupId]/rules.tsx
Labels: bug

#2698 Actionhero v28.0.4 & Node Resque v9.1.3
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2699 `noImplicitAny` for the CLI package
  cli/package.json
  cli/src/grouparoo.ts
  cli/src/lib/install.ts
  cli/src/lib/update.ts
  cli/src/utils/checkNodeVersion.ts
  cli/src/utils/ensurePackageJSON.ts
  cli/src/utils/ensurePath.ts
  cli/src/utils/loadLocalCommands.ts
  cli/src/utils/npm.ts
  cli/src/utils/readPackageJSON.ts
  cli/tsconfig.json
  pnpm-lock.yaml
Labels: internal

#2682 Replace Destination data page Record Preview with Sample Record Card
  core/src/models/GrouparooRecord.ts
  ui/ui-components/components/destination/DestinationSampleRecord.tsx
  ui/ui-components/components/destination/RecordPreview.tsx
  ui/ui-components/components/lib/ManagedCard.tsx
  ui/ui-components/components/property/PropertySampleRecord.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/utils/apiData.ts
Labels: enhancement

#2695 allow logging exports with GROUPAROO_EXPORT_LOG env var
  core/__tests__/models/export.ts
  core/src/models/Export.ts
Labels: enhancement

#2703 Rebuild state from props when changing from one property edit page to another
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
Labels: bug

#2700 Display destinations exported to when Record manually exported
  ui/ui-components/pages/model/[modelId]/record/[recordId]/edit.tsx
Labels: enhancement

#2667 oAuth user sign in
  core/__tests__/actions/oAuth.ts
  core/__tests__/actions/session.ts
  core/__tests__/fixtures/actions/oAuth.js
  core/__tests__/models/oAuthRequest.ts
  core/__tests__/tasks/system/sweeper.ts
  core/src/actions/oAuth.ts
  core/src/actions/records.ts
  core/src/actions/session.ts
  core/src/config/oAuth.ts
  core/src/config/routes.ts
  core/src/index.ts
  core/src/migrations/000094-createOAuthRequests.ts
  core/src/models/Filter.ts
  core/src/models/OAuthRequest.ts
  core/src/models/Option.ts
  core/src/modules/oAuth.ts
  core/src/modules/plugin.ts
  core/src/tasks/system/sweeper.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-community/pages/oauth/callback.tsx
  ui/ui-community/pages/session/sign-in.tsx
  ui/ui-components/components/session/SignIn.tsx
  ui/ui-components/pages/oauth/callback.tsx
  ui/ui-components/pages/team/initialize.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-enterprise/pages/oauth/callback.tsx
  ui/ui-enterprise/pages/session/sign-in.tsx
Labels: enhancement

#2706 Clear `destinationId` from exports when deleting related Destination
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/export.ts
  core/__tests__/models/record/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/src/actions/exports.ts
  core/src/migrations/000096-exportDestinationAllowNull.ts
  core/src/models/Destination.ts
  core/src/models/Export.ts
  ui/ui-components/components/export/List.tsx
  ui/ui-components/pages/export/[id]/edit.tsx
Labels: enhancement

#2707 Update Dependencies
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  cli/package.json
  core/package.json
  package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/__tests__/integration/megaDelete.ts
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2708 Ignore empty strings when setting options
  core/__tests__/models/option.ts
  core/src/modules/optionHelper.ts
  ui/ui-components/pages/app/[id]/edit.tsx
Labels: bug

#2712 remove single query validation
  plugins/@grouparoo/app-templates/src/source/query/recordProperty.ts
  plugins/@grouparoo/bigquery/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/bigquery/src/lib/validateQuery.ts
  plugins/@grouparoo/clickhouse/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/mysql/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/mysql/src/lib/validateQuery.ts
  plugins/@grouparoo/postgres/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/postgres/src/lib/validateQuery.ts
  plugins/@grouparoo/redshift/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/snowflake/src/lib/validateQuery.ts
  plugins/@grouparoo/sqlite/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/sqlite/src/lib/validateQuery.ts
Labels: bug

#2713 Hide parts of the sign-in page during oAuth flow
  ui/ui-components/components/session/SignIn.tsx
Labels: enhancement
