Repository grouparoo/grouparoo, pull requests merged in 2021-06, with the labels that each got.

#1844 Run summary count fix
  core/src/modules/cli.ts
  core/src/modules/statusReporters.ts
Labels: bug

#1868 update @sentry packages
  plugins/@grouparoo/sentry/package.json
  pnpm-lock.yaml
Labels: dependencies

#1839 Sample Profiles in Config UI
  core/__tests__/actions/profiles.ts
  core/__tests__/bin/__snapshots__/sync.ts.snap
  core/__tests__/fixtures/codeConfig/error-profile-missing-property/config.js
  core/__tests__/fixtures/codeConfig/error-profile-non-unique-property/config.js
  core/__tests__/fixtures/codeConfig/profiles/config.js
  core/__tests__/models/profile/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/codeConfig/syncTable.ts
  core/__tests__/modules/codeConfig/validate.ts
  core/__tests__/modules/configWriter.ts
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/src/actions/navigation.ts
  core/src/actions/profiles.ts
  core/src/actions/properties.ts
  core/src/classes/codeConfig.ts
  core/src/models/Profile.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/profile.ts
  core/src/modules/configWriter.ts
  core/src/modules/ops/profile.ts
  ui/ui-components/components/tabs/profile.tsx
  ui/ui-config/pages/profile/[id]/edit.tsx
  ui/ui-config/pages/profile/[id]/exports.tsx
  ui/ui-config/pages/profile/[id]/logs.tsx
  ui/ui-config/pages/profile/new.tsx
  ui/ui-config/pages/profiles.tsx
Labels: enhancement

#1869 Update Dependencies
  core/__tests__/fixtures/actions/plugins.ts
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1873 Add MongoDB query example to query source template.
  plugins/@grouparoo/mongo/public/templates/query-source/{{{id}}}.js.template
Labels: enhancement, plugin

#1870 fix: use convenient rules when generating group config objects
  core/__tests__/models/group/calculatedGroup.ts
  core/src/models/Group.ts
Labels: bug

#1884 Clear config require cache when new plugin installed
  core/src/actions/plugins.ts
Labels: enhancement

#1886 `run.updateTotals` before run summary
  core/__tests__/modules/status.ts
  core/src/modules/statusReporters.ts
Labels: bug

#1832 Bulk write ProfileProperties
  core/__tests__/integration/events.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/profileProperty.ts
  core/__tests__/models/property/property.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/property/updateProfileProperties.ts
  core/src/migrations/000068-profilePropertyCompositeUniqueIndex.ts
  core/src/models/Profile.ts
  core/src/models/ProfileProperty.ts
  core/src/models/Property.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profile/completeImport.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  core/src/tasks/property/updateProfileProperties.ts
  lerna.json
Labels: breaking change, enhancement

#1887 More complex filter/aggregationMethod example in Property template
  plugins/@grouparoo/app-templates/public/templates/table-property/{{{id}}}.js.template
Labels: enhancement

#1888 Memoize & preload options and mappings
  core/__tests__/models/mapping.ts
  core/__tests__/models/option.ts
  core/__tests__/models/property/property.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/models/ApiKey.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Export.ts
  core/src/models/ExportProcessor.ts
  core/src/models/Group.ts
  core/src/models/Permission.ts
  core/src/models/Profile.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Source.ts
  core/src/models/Team.ts
  core/src/modules/groupExport.ts
  core/src/modules/mappingHelper.ts
  core/src/modules/middleware/authentication.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/schedule.ts
  core/src/modules/ops/source.ts
  core/src/modules/optionHelper.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/export/process.ts
  core/src/tasks/export/send.ts
  core/src/tasks/export/sendBatch.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
Labels: enhancement

#1889 removed `build_static_refs` objects for property rules
  core/__tests__/bin/build_static_refs.ts
  core/bin/build_static_refs
Labels: internal

#1885 Add scripts to staging-config to make it easier to work in config mode
  apps/staging-config/README.md
  apps/staging-config/package.json
Labels: enhancement

#1872 Fix issues when deleting multiple objects at the same time
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/exportProfiles.ts
  core/__tests__/models/destination/plugins/processExportedProfiles.ts
  core/__tests__/models/group/group.ts
  core/__tests__/models/property/localCache.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/schedule.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/export/enqueue.ts
  core/__tests__/tasks/export/enqueueProcessors.ts
  core/__tests__/tasks/group/destroy.ts
  core/__tests__/tasks/source/destroy.ts
  core/src/actions/properties.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/models/Run.ts
  core/src/models/Schedule.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/exportProcessor.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/schedule.ts
  core/src/modules/ops/source.ts
  core/src/tasks/export/enqueueProcessors.ts
  core/src/tasks/export/process.ts
  core/src/tasks/export/send.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  core/src/tasks/source/destroy.ts
  ui/ui-components/pages/properties.tsx
Labels: bug

#1891 Only consider ready profiles to add to groups
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/tasks/group/run.ts
  core/__tests__/utils/prepareSharedGroupTest.ts
  core/src/models/Group.ts
  core/src/models/ProfileMultipleAssociationShim.ts
  core/src/modules/ops/group.ts
Labels: bug

#1893 Only write update to run once
  core/src/models/Run.ts
  core/src/modules/ops/runs.ts
Labels: enhancement

#1896 fix: get status report for deleted sources and destinations
  core/__tests__/modules/status.ts
  core/src/modules/statusReporters.ts
Labels: bug

#1900 Groups don't have "updating" state in Config UI
  apps/staging-config/README.md
  apps/staging-config/package.json
  core/__tests__/models/group/group.ts
  core/src/modules/ops/group.ts
  pnpm-lock.yaml
Labels: enhancement

#1902 Only recalculate run complete percentage on state change or in updateCounts task
  core/src/models/Run.ts
  core/src/modules/ops/runs.ts
Labels: enhancement

#1904 Conditionally set Sentry tags for Action or Task
  plugins/@grouparoo/newrelic/src/initializers/newrelic.ts
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
Labels: bug

#1903 Write `profile:export` updates to Import in bulk
  core/src/tasks/profile/export.ts
Labels: enhancement

#1905 remove `profile:destroyEvents` task
  core/__tests__/models/profile/profile.ts
  core/__tests__/tasks/profile/destroyEvents.ts
  core/src/models/Profile.ts
  core/src/tasks/profile/destroyEvents.ts
Labels: internal

#1897 Store Individual Status Metrics
  bin/timed_run
  core/__tests__/actions/status.ts
  core/__tests__/modules/status.ts
  core/__tests__/tasks/system/status/status.ts
  core/__tests__/tasks/system/status/statusSample.ts
  core/src/actions/resque.ts
  core/src/actions/status.ts
  core/src/bin/status.ts
  core/src/index.ts
  core/src/modules/status.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/system/status.ts
  core/src/tasks/system/status/status.ts
  core/src/tasks/system/status/statusSample.ts
  ui/ui-components/components/navigation/resqueFailedBadgeCount.tsx
  ui/ui-components/components/navigation/runningRunsBadge.tsx
  ui/ui-components/components/navigation/unreadNotificationsBadge.tsx
  ui/ui-components/components/visualizations/grouparooChart.tsx
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/pages/resque/overview.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-components/utils/eventDispatcher.ts
  ui/ui-components/utils/statusHandler.ts
Labels: enhancement

#1909 Test `timed_run` weekly with 100,000 profiles
  .github/workflows/timed-run.yml
Labels: internal

#1910 Relax min number of points on chart with variable status metrics
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/pages/resque/overview.tsx
Labels: bug

#1911 Add query-property template to Mongo plugin
  plugins/@grouparoo/mongo/public/templates/query-property/{{{id}}}.js.template
  plugins/@grouparoo/mongo/src/initializers/plugin.ts
Labels: enhancement, plugin

#1913 Clean up SQLite plugin queries
  plugins/@grouparoo/sqlite/__tests__/export/export-profile.ts
  plugins/@grouparoo/sqlite/__tests__/integration/cli-generate-from.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-query-import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-table-import.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/import-property.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/profiles.ts
  plugins/@grouparoo/sqlite/__tests__/utils/data.ts
  plugins/@grouparoo/sqlite/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/sqlite/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/sqlite/src/lib/export/exportProfile.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getChangedRowCount.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getChangedRows.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getSampleRows.ts
Labels: bug

#1917 Fix sqlite plugin specs
  plugins/@grouparoo/sqlite/__tests__/utils/data.ts
Labels: plugin

#1916 Move config CLI command to ui-config
  .gitignore
  core/src/bin/config.ts
  pnpm-lock.yaml
  ui/ui-config/dist/bin/config.js
  ui/ui-config/package.json
Labels: enhancement

#1918 Remove group calcs in Config UI
  pnpm-lock.yaml
  ui/ui-components/pages/destination/[id]/data.tsx
  ui/ui-components/pages/group/[id]/edit.tsx
  ui/ui-components/pages/group/[id]/rules.tsx
  ui/ui-components/pages/groups.tsx
Labels: enhancement

#1919 Fix logging message for new config UI subscription
  core/src/modules/grouparooSubscription.ts
Labels: bug

#1914 End validation if error is `instanceof Sequelize.DatabaseError`
  core/__tests__/actions/apiKey.ts
  core/__tests__/integration/errors.ts
  core/src/config/errors.ts
  core/src/modules/configLoaders/index.ts
Labels: bug

#1835 Setup steps page on /setup
  core/src/actions/navigation.ts
  plugins/@grouparoo/spec-helper/src/lib/integrationSpecHelper.ts
  ui/ui-community/pages/session/sign-in.tsx
  ui/ui-components/__tests__/pages/index.tsx
  ui/ui-components/components/navigation.tsx
  ui/ui-components/components/setupSteps/setupStepCard.tsx
  ui/ui-components/pages/index.tsx
  ui/ui-components/pages/setup.tsx
  ui/ui-config/__tests__/integration/happyPath.ts
  ui/ui-config/pages/index.tsx
  ui/ui-config/pages/session/sign-in.tsx
  ui/ui-config/pages/setup.tsx
  ui/ui-enterprise/pages/session/sign-in.tsx
Labels: enhancement

#1921 Update the pnpm lockfile as part publish
  .github/workflows/publish.yml
  .github/workflows/update-branch.yml
  .github/workflows/update-lockfile.yml
Labels: internal

#1915 fix: source with directlyMapped property can be destroyed
  core/__tests__/models/source.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/tasks/source/destroy.ts
Labels: bug

#1922 Use regular `specHelper` for UI tests
  core/src/config/api.ts
  core/src/config/next.ts
  core/src/index.ts
  core/src/modules/plugin.ts
  plugins/@grouparoo/spec-helper/src/index.ts
  plugins/@grouparoo/spec-helper/src/lib/environment.ts
  plugins/@grouparoo/spec-helper/src/lib/integrationSpecHelper.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  pnpm-lock.yaml
  ui/ui-community/__tests__/integration/happyPath.ts
  ui/ui-community/jest.config.js
  ui/ui-community/jest.setup.ts
  ui/ui-community/package.json
  ui/ui-components/client/client.ts
  ui/ui-components/components/navigation/setupStepsNavProgressBar.tsx
  ui/ui-components/components/statusSubscription.tsx
  ui/ui-config/__tests__/integration/happyPath.ts
  ui/ui-config/jest.config.js
  ui/ui-config/jest.setup.ts
  ui/ui-config/package.json
  ui/ui-enterprise/__tests__/integration/happyPath.ts
  ui/ui-enterprise/jest.config.js
  ui/ui-enterprise/jest.setup.ts
  ui/ui-enterprise/package.json
Labels: internal

#1925 Using env vars for secret values in Config UI
  core/__tests__/modules/configWriter.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Source.ts
  ui/ui-components/pages/app/[id]/edit.tsx
Labels: enhancement

#1926 Fix [Object] display bug on Destination Data
  ui/ui-components/pages/destination/[id]/data.tsx
Labels: bug

#1923 Log problematic SQL statement when `NODE_ENV` is development or test
  core/package.json
  core/src/initializers/exceptionReporter.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/newrelic/src/initializers/newrelic.ts
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: enhancement

#1930 Relax error throwing for `profileProperties:enqueue` task
  core/src/classes/tasks/retryableTask.ts
  core/src/tasks/import/associateProfiles.ts
  core/src/tasks/profileProperty/enqueue.ts
Labels: bug

#1928 Human IDs, Part 2
  core/__tests__/modules/configWriter.ts
  core/src/classes/loggedModel.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Source.ts
  core/src/modules/configWriter.ts
Labels: enhancement

#1935 Reorganize navigation action
  core/src/actions/navigation.ts
  ui/ui-components/components/navigation.tsx
  ui/ui-components/components/navigation/setupStepsNavProgressBar.tsx
Labels: internal

#1933 Fix filenames for array objects
  core/__tests__/modules/configWriter.ts
  core/src/modules/configWriter.ts
Labels: bug

#1934 Change "sign in" to "register" for config
  ui/ui-config/pages/index.tsx
  ui/ui-config/pages/session/sign-in.tsx
Labels: enhancement

#1936 Set groups right to ready in config
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/models/group/group.ts
  core/src/models/Group.ts
Labels: enhancement

#1929 Show group member count in parenthesis
  ui/ui-components/pages/destination/[id]/data.tsx
Labels: bug

#1932 Write cluster name setting if it has changed
  core/__tests__/modules/configWriter.ts
  core/src/models/Setting.ts
  core/src/modules/configWriter.ts
Labels: enhancement

#1939 Fix autofocus for config sign in
  ui/ui-config/pages/session/sign-in.tsx
Labels: enhancement

#1940 Move available env vars closer to docs note on config app edit form
  ui/ui-components/pages/app/[id]/edit.tsx
Labels: enhancement

#1938 Remove UI plugins from the `grouparoo.plugins` section in package.json file
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  cli/src/lib/install.ts
  cli/src/utils/npm.ts
  cli/templates/package.json
  core/src/utils/pluginDetails.js
Labels: enhancement

#1941 Redshift options match Postgres
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
Labels: enhancement

#1942 SQLite Task Fixes
  core/src/tasks/system/status/status.ts
  plugins/@grouparoo/csv/src/lib/shared/parseProfileProperties.ts
  plugins/@grouparoo/csv/src/lib/shared/parseProfiles.ts
  plugins/@grouparoo/csv/src/lib/shared/previewCSV.ts
  plugins/@grouparoo/csv/src/lib/shared/sleep.ts
Labels: bug

#1957 Trigger a config write when creating a config user
  core/src/actions/config.ts
Labels: enhancement

#1968 Fixup profileProperties:enqueue error reporting
  core/src/tasks/profileProperty/enqueue.ts
Labels: bug

#1970 Update sentry version
  plugins/@grouparoo/sentry/package.json
Labels: dependencies

#1971 Update prettier
  cli/package.json
  core/package.json
  package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1973 Do not retry `profile:completeImport` if not ready
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/tasks/profile/checkReady.ts
  core/__tests__/tasks/profile/completeImport.ts
  core/__tests__/tasks/profile/export.ts
  core/src/models/Group.ts
  core/src/models/GroupMember.ts
  core/src/models/Profile.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profile/completeImport.ts
Labels: enhancement

#1974 Destroy Event Models
  core/src/actions/navigation.ts
  core/src/migrations/000071-removeEvents.ts
  ui/ui-components/components/log/list.tsx
  ui/ui-components/components/tabs/profile.tsx
  ui/ui-components/pages/source/[id]/overview.tsx
Labels: bug, enhancement

#1969 Don't boot config server when there are errors
  core/src/initializers/codeConfig.ts
Labels: bug

#1959 ConfigWriter.generateId() throws an error when it can't build a valid id
  core/__tests__/modules/configWriter.ts
  core/src/modules/configWriter.ts
Labels: enhancement

#1960 Add a first setup step in config mode that is always true
  core/__tests__/models/setupStep.ts
  core/src/initializers/setupSteps.ts
  core/src/models/SetupStep.ts
  core/src/modules/ops/setupSteps.ts
  ui/ui-components/components/setupSteps/setupStepCard.tsx
Labels: enhancement

#1976 Speed up `exports:list`
  core/__tests__/models/profile/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/src/actions/exports.ts
  core/src/actions/imports.ts
  core/src/models/Export.ts
Labels: enhancement

#1980 Resque overview page works entirely on polling
  core/src/actions/navigation.ts
  core/src/actions/resque.ts
  ui/ui-components/pages/resque/overview.tsx
Labels: enhancement

#1981 Update Actionhero Dependencies
  core/package.json
  plugins/@grouparoo/postgres/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#1982 Remove `thank-you` script
  core/package.json
  core/thank-you
Labels: internal

#1983 Update ah-next-plugin
  core/package.json
  pnpm-lock.yaml
Labels: bug

#1984 Remove `ah-next-plugin` + Next.js v11.0.1
  core/package.json
  core/src/actions/next.ts
  core/src/config/plugins.ts
  core/src/config/routes.ts
  core/src/initializers/next.ts
  pnpm-lock.yaml
  ui/ui-community/next-env.d.ts
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/next-env.d.ts
  ui/ui-config/package.json
  ui/ui-enterprise/next-env.d.ts
  ui/ui-enterprise/package.json
Labels: bug, dependencies

#1985 Readme Updates
  plugins/@grouparoo/app-templates/README.md
  plugins/@grouparoo/bigquery/README.md
  plugins/@grouparoo/csv/README.md
  plugins/@grouparoo/customerio/README.md
  plugins/@grouparoo/dbt/README.md
  plugins/@grouparoo/facebook/README.md
  plugins/@grouparoo/files-local/README.md
  plugins/@grouparoo/files-s3/README.md
  plugins/@grouparoo/google-sheets/README.md
  plugins/@grouparoo/hubspot/README.md
  plugins/@grouparoo/intercom/README.md
  plugins/@grouparoo/iterable/README.md
  plugins/@grouparoo/logger/README.md
  plugins/@grouparoo/mailchimp/README.md
  plugins/@grouparoo/marketo/README.md
  plugins/@grouparoo/mongo/README.md
  plugins/@grouparoo/mysql/README.md
  plugins/@grouparoo/newrelic/README.md
  plugins/@grouparoo/onesignal/README.md
  plugins/@grouparoo/pardot/README.md
  plugins/@grouparoo/pipedrive/README.md
  plugins/@grouparoo/postgres/README.md
  plugins/@grouparoo/redshift/README.md
  plugins/@grouparoo/sailthru/README.md
  plugins/@grouparoo/salesforce/README.md
  plugins/@grouparoo/sendgrid/README.md
  plugins/@grouparoo/sentry/README.md
  plugins/@grouparoo/snowflake/README.md
  plugins/@grouparoo/spec-helper/README.md
  plugins/@grouparoo/sqlite/README.md
  plugins/@grouparoo/zendesk/README.md
  ui/ui-community/README.md
  ui/ui-components/README.md
  ui/ui-config/README.md
  ui/ui-enterprise/README.md
Labels: documentation

#1958 Attempt to open web browser when starting config ui
  pnpm-lock.yaml
  ui/ui-config/__tests__/bin/config.ts
  ui/ui-config/dist/bin/config.js
  ui/ui-config/package.json
Labels: enhancement

#1988 `import:associateProfile` gets 3 tries
  core/__tests__/tasks/import/associateProfile.ts
  core/src/tasks/import/associateProfile.ts
Labels: bug

#1989 next.js wildcard route should be injected last in start lifecycle step
  core/src/config/routes.ts
  core/src/initializers/next.ts
  core/src/initializers/resque.ts
Labels: bug

#1990 Better protect `status#get` from old-format status samples
  core/__tests__/modules/status.ts
  core/src/modules/status.ts
Labels: bug

#1943 Move Schedule Error to after run
  core/__tests__/bin/run.ts
  core/__tests__/modules/status.ts
  core/src/bin/run.ts
  core/src/modules/cli.ts
  core/src/modules/status.ts
  core/src/modules/statusReporters.ts
Labels: enhancement

#1987 Don't delete config files if we can't retrieve new objects
  core/__tests__/modules/configWriter.ts
  core/src/modules/configWriter.ts
Labels: bug

#1993 Manual groups do not add a rules key to their config object
  core/__tests__/modules/configWriter.ts
  core/src/models/Group.ts
Labels: bug

#1994 staging-config dev mode disables workers
  apps/staging-config/package.json
Labels: internal

#1992 Use absolute times in UI
  ui/ui-components/components/export/list.tsx
  ui/ui-components/components/import/list.tsx
  ui/ui-components/components/profile/arrayProfilePropertyList.tsx
  ui/ui-components/components/profile/list.tsx
  ui/ui-components/components/runs/list.tsx
  ui/ui-components/components/settings/settingCard.tsx
  ui/ui-components/pages/apiKeys.tsx
  ui/ui-components/pages/apps.tsx
  ui/ui-components/pages/destinations.tsx
  ui/ui-components/pages/export/[id]/edit.tsx
  ui/ui-components/pages/exportProcessors.tsx
  ui/ui-components/pages/files.tsx
  ui/ui-components/pages/group/[id]/edit.tsx
  ui/ui-components/pages/groups.tsx
  ui/ui-components/pages/notification/[id]/edit.tsx
  ui/ui-components/pages/notifications.tsx
  ui/ui-components/pages/profile/[id]/edit.tsx
  ui/ui-components/pages/properties.tsx
  ui/ui-components/pages/run/[id]/edit.tsx
  ui/ui-components/pages/source/[id]/overview.tsx
  ui/ui-components/pages/source/[id]/schedule.tsx
  ui/ui-components/pages/sources.tsx
  ui/ui-components/pages/team/[id]/members.tsx
  ui/ui-components/pages/teamMember/[id]/edit.tsx
  ui/ui-components/pages/teams.tsx
  ui/ui-components/utils/formatTimestamp.tsx
  ui/ui-config/components/cliStream.tsx
  ui/ui-enterprise/pages/group/[id]/destinations.tsx
Labels: enhancement

#1999 Use unlinkSync instead of rmSync
  core/src/modules/configWriter.ts
Labels: bug

#2002 Revert adding `bluebird` as a `@grouparoo/facebook` dependency
  plugins/@grouparoo/facebook/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#1996 `TopLevelGroupRules` start with `grouparoo` prefix
  core/__tests__/models/group/rules/topLevelGroupRules.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/run/run.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/migrations/000073-renameTopLevelGroupRules.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
Labels: enhancement

#2000 copy and link update
  ui/ui-components/pages/destination/[id]/data.tsx
  ui/ui-components/pages/profile/[id]/edit.tsx
Labels: bug

#2005 Update nav on group create
  ui/ui-components/pages/group/[id]/rules.tsx
Labels: bug

#2011 Update error message when no workers on `grouparoo run`
  core/src/bin/run.ts
Labels: enhancement

#2009 redirect to app edit after plugin install
  ui/ui-config/pages/app/new.tsx
Labels: enhancement

#2012 Upgrade to Actionhero v26.1.0 and stop reporting "unknown action" errors to Sentry
  core/package.json
  core/src/config/errors.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies, internal

#2013 set mapped column when bootstrapping google sheets property
  plugins/@grouparoo/google-sheets/__tests__/integration/unique-property-bootstrap-options.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/uniquePropertyBootstrapOptions.ts
Labels: bug

#2014 Bring back `/profile/[id]/export` tab to ui-config
  ui/ui-components/components/tabs/profile.tsx
Labels: enhancement

#2015 Show failure message if there is a reboot problem when installing plugin from ui-config
  core/src/actions/plugins.ts
  ui/ui-config/pages/app/new.tsx
Labels: enhancement

#2008 fix: save and load profile column group rules in code config
  core/__tests__/fixtures/codeConfig/top-level-group-rule/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/configWriter.ts
  core/src/actions/groups.ts
  core/src/classes/codeConfig.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/topLevelGroupRules.ts
  ui/ui-components/pages/group/[id]/rules.tsx
Labels: bug
