Repository grouparoo/grouparoo, pull requests merged in 2021-11, with the labels that each got.

#2512 Update `jest`, `ts-jest`, and `nock` to latest versions
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2513 Update `sequelize` and `ts-sequelize` to latest versions
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#2511 Replace `compare-versions` with `semver`
  core/package.json
  core/src/modules/plugins.ts
  pnpm-lock.yaml
Labels: dependencies

#2518 fix broken app link in destination page
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/edit.tsx
Labels: bug

#2519 Snowflake not reading primary key when "always uppercase" setting is on.
  plugins/@grouparoo/snowflake/__tests__/fixtures/integration/app-data-refresh.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/integration/log-checking.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import/import-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import/records.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/get-changed-row-count.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/import-properties.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/import-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/record-property-rule-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/records.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/schedule-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/source-filters.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/source-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/source-preview.js
  plugins/@grouparoo/snowflake/src/lib/table-import/getChangedRows.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/util.ts
Labels: bug

#2515 Synced Records per Month
  core/__tests__/models/export.ts
  core/__tests__/models/setting.ts
  core/__tests__/modules/status.ts
  core/__tests__/tasks/export/enqueue.ts
  core/__tests__/tasks/record/destroy.ts
  core/__tests__/tasks/system/sweeper.ts
  core/src/models/Destination.ts
  core/src/models/Export.ts
  core/src/models/GrouparooRecord.ts
  core/src/modules/ops/setting.ts
  core/src/modules/status.ts
  core/src/modules/statusReporters.ts
  core/src/modules/telemetry.ts
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/pages/dashboard.tsx
Labels: enhancement

#2526 run configWriter on model changes
  core/__tests__/actions/apps.ts
  core/__tests__/actions/destinations.ts
  core/__tests__/actions/groups.ts
  core/__tests__/actions/models.ts
  core/__tests__/actions/properties.ts
  core/__tests__/actions/schedules.ts
  core/__tests__/actions/sources.ts
  core/src/actions/models.ts
Labels: bug

#2523 Hubspot Companies export tests
  plugins/@grouparoo/hubspot/__tests__/export-objects/export-records-companies.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/export-records-companies.js
Labels: plugin

#2524 set serverName on sentry events, allow env overriding
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
Labels: enhancement

#2525 add message and url params to cloud cli commands
  core/src/bin/ci.ts
  core/src/bin/deploy.ts
  core/src/bin/push.ts
  core/src/modules/cloud.ts
  core/src/modules/cloudCli.ts
Labels: enhancement

#2514 Update to latest `next` version (v12.x)
  core/src/initializers/next.ts
  pnpm-lock.yaml
  ui/ui-community/.babelrc.js
  ui/ui-community/next.config.js
  ui/ui-community/package.json
  ui/ui-community/tsconfig.json
  ui/ui-components/package.json
  ui/ui-config/.babelrc.js
  ui/ui-config/next.config.js
  ui/ui-config/package.json
  ui/ui-config/tsconfig.json
  ui/ui-enterprise/.babelrc.js
  ui/ui-enterprise/next.config.js
  ui/ui-enterprise/package.json
  ui/ui-enterprise/tsconfig.json
Labels: dependencies

#2522 Sql updates for performance
  plugins/@grouparoo/bigquery/__tests__/data/purchases.csv
  plugins/@grouparoo/bigquery/__tests__/data/records.csv
  plugins/@grouparoo/bigquery/__tests__/fixtures/integration/app-data-refresh.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/integration/cli-generate-from.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/integration/log-checking.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/query-import/import-property.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/query-import/records.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/get-changed-row-count.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/import-properties.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/import-property.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/record-property-rule-options.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/records.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/schedule-options.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/source-filters.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/source-options.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/source-preview.js
  plugins/@grouparoo/bigquery/__tests__/integration/cli-generate-from.ts
  plugins/@grouparoo/bigquery/__tests__/integration/log-checking.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/import-property.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/record-property-rule-options.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/schedule-options.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/source-filters.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/source-options.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/source-preview.ts
  plugins/@grouparoo/bigquery/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mysql/src/lib/connect.ts
  plugins/@grouparoo/mysql/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/snowflake/__tests__/data/profiles.csv
  plugins/@grouparoo/snowflake/__tests__/data/purchases.csv
  plugins/@grouparoo/snowflake/__tests__/fixtures/integration/app-data-refresh.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/integration/log-checking.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import/import-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import/records.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/get-changed-row-count.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/import-properties.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/import-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/record-property-rule-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/records.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/schedule-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/source-filters.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/source-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/source-preview.js
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValues.ts
Labels: enhancement

#2304 More error logging for batch helper
  plugins/@grouparoo/app-templates/src/destination/batch/exportRecords.ts
Labels: enhancement

#2476 appRefreshQuery Task and Ops update
  core/__tests__/models/appRefreshQuery.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/tasks/appRefreshQuery/check.ts
  core/__tests__/tasks/appRefreshQuery/query.ts
  core/src/models/AppRefreshQuery.ts
  core/src/modules/ops/appRefreshQuery.ts
  core/src/tasks/appRefreshQuery/check.ts
  core/src/tasks/appRefreshQuery/query.ts
  plugins/@grouparoo/bigquery/__tests__/integration/app-data-refresh.ts
  plugins/@grouparoo/mysql/__tests__/integration/app-data-refresh.ts
  plugins/@grouparoo/postgres/__tests__/integration/app-data-refresh.ts
  plugins/@grouparoo/snowflake/__tests__/integration/app-data-refresh.ts
  plugins/@grouparoo/sqlite/__tests__/integration/app-data-refresh.ts
Labels: bug

#2534 Integration tests for Redshift Plugin
  plugins/@grouparoo/redshift/__tests__/.env.example
  plugins/@grouparoo/redshift/__tests__/data/accounts.sql
  plugins/@grouparoo/redshift/__tests__/data/purchases.sql
  plugins/@grouparoo/redshift/__tests__/data/users.sql
  plugins/@grouparoo/redshift/__tests__/integration/redshift-query-import.ts
  plugins/@grouparoo/redshift/__tests__/integration/redshift-table-import.ts
  plugins/@grouparoo/redshift/__tests__/utils/data.ts
  plugins/@grouparoo/redshift/jest.config.js
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/spec-helper/src/lib/cliSpecHelper.ts
  pnpm-lock.yaml
Labels: internal

#2531 Test demo command via creating and deleting a config directory
  core/__tests__/tasks/destination/destroy.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/record.ts
  core/src/tasks/destination/destroy.ts
  plugins/@grouparoo/demo/__tests__/integration/megaDelete.ts
  plugins/@grouparoo/demo/config/logger/all/apps/logger.json
  plugins/@grouparoo/demo/config/logger/users/destinations/logger.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/demo.ts
  plugins/@grouparoo/demo/src/util/config.ts
  plugins/@grouparoo/demo/src/util/configFiles.ts
  plugins/@grouparoo/demo/src/util/shared.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  pnpm-lock.yaml
Labels: internal

#2539 Fix redirects and multiplePropertyOptions
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
Labels: bug

#2541 Fix `APIData.ensureObject` optional recusion flag
  core/__tests__/modules/apiData.ts
  core/src/modules/apiData.ts
Labels: bug

#2543 App and Plugin Action Cleanup
  core/__tests__/actions/apps.ts
  core/__tests__/actions/plugins.ts
  core/__tests__/fixtures/actions/plugins.js
  core/__tests__/notifiers/newVersionNotifier.ts
  core/src/actions/apps.ts
  core/src/actions/plugins.ts
  core/src/config/routes.ts
  core/src/modules/plugins.ts
  core/src/notifiers/newVersionNotifier.ts
  ui/ui-components/components/AppSelectorList.tsx
  ui/ui-components/pages/about.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/app/new/[...plugin].tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-config/pages/app/new/index.tsx
  ui/ui-config/pages/plugins.tsx
  ui/ui-enterprise/pages/app/new/index.tsx
Labels: enhancement

#2546 Sleep longer in tests with backoff when waiting for boot
  apps/staging-enterprise/__tests__/integration
Labels: internal

#2544 Ignore pnpm-lock from Prettier formatting
  .prettierignore
Labels: internal

#2549 Fixup the core version test
  core/__tests__/actions/plugins.ts
Labels: internal

#2542 In dbt plugin, dbt “profile” was accidentally renamed to “record”
  plugins/@grouparoo/dbt/__tests__/profiles/bigquery/my-keyfile.json
  plugins/@grouparoo/dbt/__tests__/profiles/bigquery/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/invalid_name/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/invalid_target/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/postgres/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/redshift/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/snowflake/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/unknown/profiles.yml
  plugins/@grouparoo/dbt/__tests__/profiles/unsupported/profiles.yml
  plugins/@grouparoo/dbt/__tests__/projects/default/dbt_project.yml
  plugins/@grouparoo/dbt/__tests__/settings/parse.ts
  plugins/@grouparoo/dbt/src/settings/command.ts
  plugins/@grouparoo/dbt/src/settings/parse.ts
  plugins/@grouparoo/dbt/src/settings/plugins.ts
Labels: bug

#2553 Display Resque task args in progress
  .circleci/config.yml
  ui/ui-components/pages/resque/overview.tsx
  ui/ui-components/pages/resque/workers.tsx
Labels: enhancement

#2559 `private_key_passphrase` for Snowflake keypair apps
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/lib/connect.ts
Labels: enhancement, plugin

#2548 AppRefreshQuery tasks/actions update
  core/__tests__/actions/appRefreshQuery.ts
  core/__tests__/fixtures/codeConfig/bootstrapped-property-in-source/config.js
  core/__tests__/fixtures/codeConfig/changes/config.js
  core/__tests__/fixtures/codeConfig/initial/config.js
  core/__tests__/models/appRefreshQuery.ts
  core/__tests__/tasks/appRefreshQuery/check.ts
  core/__tests__/tasks/appRefreshQuery/query.ts
  core/src/actions/appRefreshQuery.ts
  core/src/bin/run.ts
  core/src/classes/codeConfig.ts
  core/src/config/routes.ts
  core/src/migrations/000092-appRefreshQueryInterval.ts
  core/src/models/AppRefreshQuery.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/ops/appRefreshQuery.ts
  core/src/tasks/appRefreshQuery/check.ts
  core/src/tasks/appRefreshQuery/query.ts
  core/src/tasks/schedule/enqueueRuns.ts
  plugins/@grouparoo/bigquery/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/mysql/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/postgres/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/snowflake/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/sqlite/public/templates/app/{{{id}}}.js.template
  ui/ui-components/pages/app/[id]/refresh.tsx
  ui/ui-components/utils/apiData.ts
Labels: bug

#2562 bug fix in api route
  ui/ui-components/pages/app/[id]/refresh.tsx
Labels: bug

#2564 First-time User Improvements
  core/__tests__/actions/sessions.ts
  core/__tests__/actions/status.ts
  core/__tests__/models/property/property.ts
  core/__tests__/modules/configWriter.ts
  core/src/models/GrouparooRecord.ts
  core/src/models/Property.ts
  core/src/modules/mappingHelper.ts
  core/src/modules/middleware/authentication.ts
  core/src/modules/ops/record.ts
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
  ui/ui-components/client/client.ts
Labels: bug

#2540 Replace directly mapped property per source with a single primary key property for all models
  core/__tests__/bin/__snapshots__/sync.ts.snap
  core/__tests__/models/destination/plugins/exportRecord.ts
  core/__tests__/models/destination/plugins/exportRecords.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/record/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/models/source/source.ts
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/tasks/record/confirm/confirm.ts
  core/__tests__/tasks/record/destroy.ts
  core/__tests__/tasks/source/destroy.ts
  core/__tests__/tasks/system/destroy.ts
  core/src/actions/properties.ts
  core/src/migrations/000091-renamePropertyDirectlyMappedToIsPrimaryKey.ts
  core/src/models/GrouparooRecord.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/record.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/record.ts
  core/src/tasks/source/destroy.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/record.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-components/__tests__/components/test-record.json
  ui/ui-components/hooks/useApi.ts
  ui/ui-components/pages/model/[modelId]/properties.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/mapping.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/overview.tsx
  ui/ui-config/pages/model/[modelId]/record/new.tsx
Labels: enhancement

#2566 Fix directlyMapped to isPrimaryKey renames
  core/__tests__/modules/configWriter.ts
  core/src/models/GrouparooRecord.ts
Labels: bug

#2560 When an export is rate-limited, do not count that as an error
  core/__tests__/models/destination/plugins/exportRecord.ts
  core/__tests__/models/destination/plugins/exportRecords.ts
  core/__tests__/models/destination/plugins/processExportedProfiles.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/src/models/Export.ts
  ui/ui-components/components/export/List.tsx
Labels: enhancement

#2569 Add salesforce account and pipedrive to demo command
  plugins/@grouparoo/demo/config/pipedrive/all/apps/pipedrive.json
  plugins/@grouparoo/demo/config/pipedrive/users/destinations/pipedrive_persons.json
  plugins/@grouparoo/demo/config/salesforce/accounts/destinations/salesforce_accounts.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/demo.ts
  plugins/@grouparoo/demo/src/util/config.ts
  plugins/@grouparoo/demo/src/util/env.ts
Labels: internal

#2563 Retry cli uploads on timeout
  core/__tests__/bin/push.ts
  core/src/modules/cloud.ts
  core/src/modules/cloudCli.ts
Labels: enhancement

#2561 Only show properties for this Model in mustache builder
  core/__tests__/modules/plugin.ts
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/exports.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/imports.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/logs.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
Labels: enhancement, blocked

#2571 Miscellaneous ClickHouse fixes
  plugins/@grouparoo/clickhouse/public/@grouparoo/clickhouse/clickhouse.png
  plugins/@grouparoo/clickhouse/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/clickhouse/src/initializers/plugin.ts
Labels: enhancement, plugin

#2572 Fix property selection in source mapping page to be based on which source has the primary key property
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/mapping.tsx
Labels: bug

#2574 Throw error when mapping to source's own property while primary key belongs to another source
  core/__tests__/models/property/property.ts
  core/__tests__/models/source/source.ts
  core/__tests__/modules/configWriter.ts
  core/src/models/Property.ts
  core/src/modules/mappingHelper.ts
Labels: bug

#2575 Do not show "Add Multiple Properties" if source is not ready
  ui/ui-components/components/property/Add.tsx
  ui/ui-components/components/property/AddMultiple.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/overview.tsx
Labels: bug

#2565 Add model-centric UI overview page
  ui/ui-community/pages/model/[modelId]/overview.tsx
  ui/ui-components/client/client.ts
  ui/ui-components/components/GroupIcon.tsx
  ui/ui-components/components/Icons.ts
  ui/ui-components/components/ModelIcon.tsx
  ui/ui-components/components/PageHeader.tsx
  ui/ui-components/components/destination/DestinationCollectionLink.tsx
  ui/ui-components/components/lib/ManagedCard.tsx
  ui/ui-components/components/lib/SectionContainer.tsx
  ui/ui-components/components/lib/SeparatedItems.tsx
  ui/ui-components/components/lib/entity/EntityInfoContainer.tsx
  ui/ui-components/components/lib/entity/EntityInfoHeader.tsx
  ui/ui-components/components/lib/entity/EntityList.tsx
  ui/ui-components/components/model/overview/ModelOverviewDestinations.tsx
  ui/ui-components/components/model/overview/ModelOverviewGroups.tsx
  ui/ui-components/components/model/overview/ModelOverviewPrimarySource.tsx
  ui/ui-components/components/model/overview/ModelOverviewSchedules.tsx
  ui/ui-components/components/model/overview/ModelOverviewSecondarySources.tsx
  ui/ui-components/components/model/overview/SourceInfo.tsx
  ui/ui-components/components/schedule/RunAllSchedulesButton.tsx
  ui/ui-components/components/visualizations/RecordImageFromEmail.tsx
  ui/ui-components/contexts/grouparooModel.tsx
  ui/ui-components/hooks/useApi.ts
  ui/ui-components/pages/_app.tsx
  ui/ui-components/pages/apps.tsx
  ui/ui-components/pages/model/[modelId]/destinations.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/sources.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-components/utils/eventHandlers.ts
  ui/ui-components/utils/formatName.tsx
  ui/ui-components/utils/formatSchedule.tsx
  ui/ui-config/pages/model/[modelId]/overview.tsx
  ui/ui-enterprise/pages/model/[modelId]/overview.tsx
Labels: enhancement

#2578 Show example of local Postgres passwords
  apps/staging-community/.env.example
  apps/staging-config/.env.example
  apps/staging-enterprise/.env.example
  cli/templates/.env
Labels: internal
