Repository grouparoo/grouparoo, pull requests merged in 2021-04, with the labels that each got.

#1601 Set jest maxWorkers to 50%
  clients/@grouparoo/web/jest.config.js
  core/jest.config.js
  core/package.json
  plugins/@grouparoo/app-templates/jest.config.js
  plugins/@grouparoo/bigquery/jest.config.js
  plugins/@grouparoo/csv/jest.config.js
  plugins/@grouparoo/customerio/jest.config.js
  plugins/@grouparoo/dbt/jest.config.js
  plugins/@grouparoo/demo/jest.config.js
  plugins/@grouparoo/facebook/jest.config.js
  plugins/@grouparoo/google-sheets/jest.config.js
  plugins/@grouparoo/hubspot/jest.config.js
  plugins/@grouparoo/intercom/jest.config.js
  plugins/@grouparoo/iterable/jest.config.js
  plugins/@grouparoo/logger/jest.config.js
  plugins/@grouparoo/mailchimp/jest.config.js
  plugins/@grouparoo/marketo/jest.config.js
  plugins/@grouparoo/mongo/jest.config.js
  plugins/@grouparoo/mysql/jest.config.js
  plugins/@grouparoo/newrelic/jest.config.js
  plugins/@grouparoo/onesignal/jest.config.js
  plugins/@grouparoo/pardot/jest.config.js
  plugins/@grouparoo/pipedrive/jest.config.js
  plugins/@grouparoo/postgres/jest.config.js
  plugins/@grouparoo/redshift/jest.config.js
  plugins/@grouparoo/sailthru/jest.config.js
  plugins/@grouparoo/salesforce/jest.config.js
  plugins/@grouparoo/sendgrid/jest.config.js
  plugins/@grouparoo/sentry/jest.config.js
  plugins/@grouparoo/snowflake/jest.config.js
  plugins/@grouparoo/spec-helper/jest.config.js
  plugins/@grouparoo/sqlite/jest.config.js
  plugins/@grouparoo/zendesk/jest.config.js
  ui/ui-community/jest.config.js
  ui/ui-components/jest.config.js
  ui/ui-enterprise/jest.config.js
Labels: internal

#1600 Get MongoDB fields names automatically.
  plugins/@grouparoo/mongo/__tests__/table-import/get-changed-row-count-nested.ts
  plugins/@grouparoo/mongo/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/mongo/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mongo/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/mongo/__tests__/table-import/profiles.ts
  plugins/@grouparoo/mongo/__tests__/table-import/schedule-options.ts
  plugins/@grouparoo/mongo/__tests__/table-import/source-filters.ts
  plugins/@grouparoo/mongo/__tests__/table-import/source-preview.ts
  plugins/@grouparoo/mongo/__tests__/utils/data.ts
  plugins/@grouparoo/mongo/src/lib/table-import/connection.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getSampleRows.ts
  plugins/@grouparoo/mongo/src/lib/table-import/util.ts
Labels: enhancement

#1608 Fix type on Google Sheets Source template
  core/src/utils/pluginDetails.js
  plugins/@grouparoo/google-sheets/__tests__/cli/integration.ts
  plugins/@grouparoo/google-sheets/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/spec-helper/src/index.ts
  plugins/@grouparoo/spec-helper/src/lib/cliSpecHelper.ts
Labels: bug

#1617 Render boolean values in source preview
  ui/ui-enterprise/pages/source/[id]/edit.tsx
Labels: bug

#1619 Fix `@grouparoo/postgres` date parsing
  plugins/@grouparoo/postgres/__tests__/connection/dates.ts
  plugins/@grouparoo/postgres/__tests__/data/profiles.csv
  plugins/@grouparoo/postgres/__tests__/data/purchases.csv
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/src/lib/connect.ts
Labels: bug

#1625 Clean up Mongo package-lock.
  plugins/@grouparoo/mongo/package-lock.json
Labels: internal, plugin

#1628 Do not fail tasks if primary objects cannot be found
  core/__tests__/models/profile/profile.ts
  core/__tests__/tasks/event/associateProfile.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/group/run.ts
  core/__tests__/tasks/import/associateProfile.ts
  core/__tests__/tasks/profile/destroyEvents.ts
  core/__tests__/tasks/profile/export.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/profileProperty/importProfileProperty.ts
  core/__tests__/tasks/schedule/run.ts
  core/src/models/Profile.ts
  core/src/tasks/event/associateProfile.ts
  core/src/tasks/export/send.ts
  core/src/tasks/export/sendBatch.ts
  core/src/tasks/group/run.ts
  core/src/tasks/import/associateProfile.ts
  core/src/tasks/profile/destroyEvents.ts
  core/src/tasks/profile/export.ts
  core/src/tasks/schedule/run.ts
Labels: enhancement

#1630 `export:enqueue` should not re-attempt to send complete exports
  core/__tests__/tasks/export/enqueue.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/export.ts
Labels: bug

#1631 `migrator` command
  core/.sequelizerc
  core/bin/migrator
  core/package.json
  pnpm-lock.yaml
Labels: internal

#1632 `export:send` tasks should not rollback transaction if there's a returned error
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/src/models/Export.ts
  core/src/tasks/export/send.ts
  core/src/tasks/export/sendBatch.ts
  plugins/@grouparoo/iterable/src/lib/export/exportProfile.ts
Labels: bug

#1641 Remove un-used `faker` package from core
  core/package.json
Labels: dependencies

#1642 Migrator Fixes
  core/bin/migrator
Labels: bug, internal

#1643 Use webpack v5 with next.js
  ui/ui-community/next.config.js
  ui/ui-enterprise/next.config.js
Labels: dependencies, enhancement

#1645 Send new TeamMembers to Telemetry + OptOut
  core/__tests__/actions/teamMembers.ts
  core/__tests__/actions/teams.ts
  core/__tests__/tasks/system/telemetry.ts
  core/package.json
  core/src/actions/teamMembers.ts
  core/src/actions/teams.ts
  core/src/config/telemetry.ts
  core/src/initializers/telemetry.ts
  core/src/modules/grouparooSubscription.ts
  core/src/modules/telemetry.ts
  core/src/tasks/system/telemetry.ts
  ui/ui-components/pages/team/initialize.tsx
  ui/ui-components/pages/teamMember/new.tsx
Labels: enhancement

#1652 `grouparoo generate --help` provides an example for `-describe`
  core/src/bin/generate.ts
Labels: enhancement

#1653 Move Auth middlewares into transactions
  core/src/initializers/session.ts
  core/src/modules/middleware/authentication.ts
Labels: enhancement

#1654 Rename mongo import to make things more automate-able.
  plugins/@grouparoo/demo/config/mongo/sources/demo_purchases.json
  plugins/@grouparoo/demo/config/mongo/sources/demo_users.json
  plugins/@grouparoo/mongo/__tests__/table-import/get-changed-row-count-nested.ts
  plugins/@grouparoo/mongo/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/mongo/__tests__/table-import/profiles.ts
  plugins/@grouparoo/mongo/src/lib/table-import/connection.ts
Labels: enhancement, plugin

#1655 Add priority to auth middleware which writes
  core/src/modules/middleware/authentication.ts
Labels: internal

#1656 Re-apply `type` when code-configuring
  core/__tests__/fixtures/codeConfig/error-changed-type-duplicate/config.js
  core/__tests__/fixtures/codeConfig/error-changed-type-missing/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/modules/configLoaders/apiKey.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/source.ts
Labels: enhancement

#1659 Wait longer for page to change in integration test
  ui/ui-enterprise/__tests__/integration/happyPath.ts
Labels: internal

#1577 UI Stats via Websocket
  core/__tests__/actions/groups.ts
  core/__tests__/actions/sources.ts
  core/__tests__/actions/status.ts
  core/__tests__/bin/statuts.ts
  core/__tests__/models/group/group.ts
  core/__tests__/models/source.ts
  core/__tests__/modules/status.ts
  core/__tests__/tasks/system/status.ts
  core/__tests__/tasks/system/telemetry.ts
  core/src/actions/groups.ts
  core/src/actions/sources.ts
  core/src/actions/status.ts
  core/src/bin/run.ts
  core/src/bin/status.ts
  core/src/config/api.ts
  core/src/config/routes.ts
  core/src/initializers/settings.ts
  core/src/modules/cli.ts
  core/src/modules/middleware/authentication.ts
  core/src/modules/ops/source.ts
  core/src/modules/status.ts
  core/src/modules/statusReporters.ts
  core/src/modules/telemetry.ts
  core/src/modules/telemetryReporters.ts
  core/src/tasks/import/associateProfile.ts
  core/src/tasks/system/status.ts
  plugins/@grouparoo/spec-helper/src/lib/integrationSpecHelper.ts
  ui/ui-components/components/events/list.tsx
  ui/ui-components/components/log/list.tsx
  ui/ui-components/components/log/stream.tsx
  ui/ui-components/components/navigation.tsx
  ui/ui-components/components/navigation/resqueFailedBadgeCount.tsx
  ui/ui-components/components/navigation/runningRunsBadge.tsx
  ui/ui-components/components/navigation/unreadNotificationsBadge.tsx
  ui/ui-components/components/session/signOut.tsx
  ui/ui-components/components/statusSubscription.tsx
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/hooks/useRealtimeStream.ts
  ui/ui-components/pages/_app.tsx
  ui/ui-components/pages/dashboard.tsx
  ui/ui-components/pages/resque/overview.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-components/utils/eventDispatcher.ts
  ui/ui-components/utils/statusHandler.ts
Labels: enhancement

#1569 Destination Sync Modes
  core/__tests__/actions/destinations.ts
  core/__tests__/fixtures/codeConfig/initial/config.js
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/exportProfiles.ts
  core/__tests__/models/destination/plugins/noExportMethods.ts
  core/__tests__/models/option.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/tasks/profile/export.ts
  core/src/actions/destinations.ts
  core/src/actions/session.ts
  core/src/bin/generate.ts
  core/src/classes/codeConfig.ts
  core/src/classes/plugin.ts
  core/src/config/sequelize.ts
  core/src/index.ts
  core/src/migrations/000063-addSyncModeToDestination.ts
  core/src/models/Destination.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/errors.ts
  core/src/modules/middleware/authentication.ts
  core/src/modules/ops/destination.ts
  plugins/@grouparoo/app-templates/src/destination/batch/exportProfiles.ts
  plugins/@grouparoo/app-templates/src/destination/batch/types.ts
  plugins/@grouparoo/app-templates/src/destination/templates.ts
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-archive.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-delete.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-lead.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-lifecycle.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-no-create.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-no-delete.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-user.js
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-no-create.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-no-delete.ts
  plugins/@grouparoo/intercom/__tests__/utils/shared.ts
  plugins/@grouparoo/intercom/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/intercom/src/initializers/plugin.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/exportProfile.ts
  plugins/@grouparoo/intercom/src/migrations/000001-plugin-intercom-syncMode.ts
  plugins/@grouparoo/onesignal/src/lib/export/exportProfile.ts
  plugins/@grouparoo/pipedrive/__tests__/export/export-profile.ts
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/pipedrive/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/pipedrive/src/initializers/plugin.ts
  plugins/@grouparoo/pipedrive/src/lib/export/exportProfile.ts
  plugins/@grouparoo/pipedrive/src/migrations/000001-plugin-pipedrive-syncMode.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/destination.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-enterprise/pages/destination/[id]/edit.tsx
Labels: breaking change, enhancement

#1663 Fix types for csv source templates
  plugins/@grouparoo/csv/public/templates/source/file/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/source/remote/{{{id}}}.js.template
Labels: bug

#1611 Add sync modes for Hubspot
  plugins/@grouparoo/hubspot/__tests__/export/export-profile.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/hubspot-export.js
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/export/exportProfile.ts
  plugins/@grouparoo/hubspot/src/migrations/000001-plugin-hubspot-syncModes.ts
Labels: enhancement, plugin

#1644 Refactor Facebook destination to use standardized sync modes
  plugins/@grouparoo/app-templates/__tests__/destination/batch.ts
  plugins/@grouparoo/app-templates/__tests__/destination/group.ts
  plugins/@grouparoo/app-templates/src/destination/group/exportProfiles.ts
  plugins/@grouparoo/app-templates/src/destination/group/types.ts
  plugins/@grouparoo/facebook/__tests__/fixtures/export-profiles-custom.js
  plugins/@grouparoo/facebook/__tests__/integration/destination-mapping-custom.ts
  plugins/@grouparoo/facebook/__tests__/integration/export-profiles-custom.ts
  plugins/@grouparoo/facebook/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/facebook/src/initializers/plugin.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/connection.ts
  plugins/@grouparoo/facebook/src/lib/export-custom/exportProfiles.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/connection.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/exportProfiles.ts
  plugins/@grouparoo/facebook/src/lib/export-lookalike/model.ts
  plugins/@grouparoo/facebook/src/lib/export/facebookExporter.ts
  plugins/@grouparoo/facebook/src/lib/export/fields.ts
  plugins/@grouparoo/facebook/src/lib/export/model.ts
  plugins/@grouparoo/facebook/src/migrations/000001-plugin-facebook-syncMode.ts
Labels: breaking change, plugin

#1627 Add sync modes for Marketo
  plugins/@grouparoo/marketo/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/marketo/__tests__/integration/export-profiles.ts
  plugins/@grouparoo/marketo/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/marketo/src/initializers/plugin.ts
  plugins/@grouparoo/marketo/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/marketo/src/migrations/000001-plugin-marketo-syncMode.ts
Labels: enhancement, plugin

#1660 Fix customer.io app template generation
  plugins/@grouparoo/customerio/src/initializers/plugin.ts
  plugins/@grouparoo/customerio/src/migrations/000001-plugin-customerio-renameApp.ts
Labels: bug, plugin

#1665 `grouparoo validate --local` does not try to connect to bootstrap a source
  core/src/models/Source.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/ops/source.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/cli.js
  plugins/@grouparoo/snowflake/__tests__/integration/cli.ts
Labels: bug

#1666 Get changed rows count issue.
  plugins/@grouparoo/mongo/__tests__/table-import/get-changed-row-count-nested.ts
  plugins/@grouparoo/mongo/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getChangedRowCount.ts
Labels: bug, plugin

#1686 Run Dependabot Monthly
  .github/dependabot.yml
Labels: internal

#1687 Run action and model tests separately on CI against SQLite
  .circleci/config.yml
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/src/ci_generate.js
Labels: internal

#1689 `-` is valid in config object IDs
  core/__tests__/classes/loggedModel.ts
  core/__tests__/fixtures/codeConfig/error-id/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/codeConfig/errors.ts
  core/src/classes/codeConfig.ts
  core/src/classes/loggedModel.ts
  core/src/modules/configLoaders/apiKey.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/configLoaders/syncTable.ts
  core/src/modules/configLoaders/team.ts
  core/src/modules/configLoaders/teamMember.ts
Labels: enhancement

#1691 Fix Resque Error display on Overview
  ui/ui-components/pages/resque/overview.tsx
Labels: bug

#1692 Simplify `cli-test-generate` test for most plugins
  plugins/@grouparoo/bigquery/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/csv/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/customerio/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/facebook/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/hubspot/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/intercom/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/iterable/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/logger/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/marketo/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/mongo/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/mysql/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/onesignal/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/pardot/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/pipedrive/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/postgres/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/redshift/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/sailthru/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/salesforce/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/sendgrid/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/snowflake/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/spec-helper/src/lib/cliSpecHelper.ts
  plugins/@grouparoo/sqlite/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/zendesk/__tests__/integration/cli-generate-validate.ts
Labels: internal

#1693 Clearer error messages when a plugin isn't installed or typo'd
  core/__tests__/models/app/app.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/source.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/modules/optionHelper.ts
Labels: enhancement

#1685 Fix issue adding to groups after being cleared by no-delete syncMode
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/exportProfiles.ts
  core/src/modules/ops/destination.ts
  plugins/@grouparoo/hubspot/__tests__/export/export-profile.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/hubspot/src/lib/export/exportProfile.ts
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-no-delete.js
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-no-delete.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/exportProfile.ts
  plugins/@grouparoo/pipedrive/__tests__/export/export-profile.ts
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/pipedrive/src/lib/export/exportProfile.ts
Labels: bug

#1623 Add sync mode to Mailchimp.
  plugins/@grouparoo/mailchimp/__tests__/data/emails.json
  plugins/@grouparoo/mailchimp/__tests__/data/emails.txt
  plugins/@grouparoo/mailchimp/__tests__/export/export-profile.ts
  plugins/@grouparoo/mailchimp/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailchimp/public/templates/destination/email/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/destination/id/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/lib/export-id/connection.ts
  plugins/@grouparoo/mailchimp/src/lib/export-id/exportProfile.ts
  plugins/@grouparoo/mailchimp/src/lib/export/connection.ts
  plugins/@grouparoo/mailchimp/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mailchimp/src/lib/shared/updateProfile.ts
  plugins/@grouparoo/mailchimp/src/migrations/000001-plugin-mailchimp-syncModes.ts
  pnpm-lock.yaml
Labels: enhancement, plugin

#1695 Send additional telemetry calls
  core/__tests__/models/teamMember.ts
  core/__tests__/tasks/system/status.ts
  core/__tests__/tasks/system/telemetry.ts
  core/src/models/TeamMember.ts
  core/src/modules/telemetry.ts
  core/src/tasks/system/status.ts
  core/src/tasks/system/telemetry.ts
  core/src/tasks/system/telemetry/adHoc.ts
  core/src/tasks/system/telemetry/telemetry.ts
Labels: internal

#1694 Log pacote/npm errors at `info` log level
  core/src/modules/pluginVersions.ts
Labels: enhancement

#1696 cli: add extra help text if no local commands have been loaded
  apps/staging-enterprise/__tests__/cli
  cli/src/grouparoo.ts
  cli/src/utils/loadLocalCommands.ts
Labels: enhancement

#1704 Assume redis db=0 when undefined
  core/src/config/redis.ts
Labels: bug

#1705 When there's an error loading the current team member, do not try to subscribe to status
  ui/ui-components/pages/_app.tsx
Labels: bug

#1703 Do not update Mailchimp status when updating others variables.
  plugins/@grouparoo/mailchimp/__tests__/data/emails.json
  plugins/@grouparoo/mailchimp/__tests__/export/export-profile.ts
  plugins/@grouparoo/mailchimp/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/mailchimp-export-id.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/mailchimp-export.js
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export-id.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export.ts
  plugins/@grouparoo/mailchimp/src/lib/shared/updateProfile.ts
  pnpm-lock.yaml
Labels: bug, plugin

#1707 Build step on CI requires more RAM
  .circleci/config.yml
  tools/merger/data/ci/base.yml.template
Labels: internal

#1701 Selective local config validation with grouparoo cli
  cli/src/utils/loadLocalCommands.ts
  core/__tests__/actions/apps.ts
  core/__tests__/fixtures/codeConfig/error-app-destination-remote/config.js
  core/__tests__/fixtures/codeConfig/error-app-remote/config.js
  core/__tests__/modules/codeConfig/validate.ts
  core/package.json
  core/src/bin/validate.ts
  core/src/modules/configLoaders/index.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: enhancement

#1711 Telemetry Updates
  core/__tests__/modules/telemetry.ts
  core/__tests__/tasks/system/status.ts
  core/__tests__/tasks/system/telemetry.ts
  core/package.json
  core/src/initializers/telemetry.ts
  core/src/modules/telemetry.ts
  core/src/tasks/system/status.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: enhancement

#1702 Return runs sorted by updatedAt
  core/src/actions/runs.ts
  ui/ui-components/components/runs/list.tsx
Labels: bug

#1713 Do not do bulk updates if there's an empty IN clause
  core/__tests__/models/misc.ts
  core/src/models/Destination.ts
  core/src/models/ProfileProperty.ts
  core/src/models/Run.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/import.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/profileProperty.ts
Labels: bug

#1715 update snowflake nock files paths
  plugins/@grouparoo/snowflake/__tests__/query-import/import-property.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/profiles.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/schedule-options.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/source-filters.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/source-options.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/source-preview.ts
Labels: internal

#1716 Check that recurring tasks are enqueued every hour
  .circleci/config.yml
  core/__tests__/initializers/resque.ts
  core/src/initializers/resque.ts
Labels: enhancement

#1717 Use published @grouparoo/node-marketo-rest package
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/marketo/src/lib/connect.ts
  pnpm-lock.yaml
Labels: enhancement

#1718 Do not run staging apps with `npm`
  Procfile
Labels: internal

#1697 Add sync modes to Zendesk plugin
  plugins/@grouparoo/zendesk/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/zendesk/__tests__/export/export-profile.ts
  plugins/@grouparoo/zendesk/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/zendesk/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/zendesk/__tests__/integration/export-profile.ts
  plugins/@grouparoo/zendesk/src/initializers/plugin.ts
  plugins/@grouparoo/zendesk/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/zendesk/src/lib/export/exportProfile.ts
  plugins/@grouparoo/zendesk/src/migrations/000001-plugin-hubspot-syncModes.ts
Labels: enhancement, plugin

#1720 Add sort indexes on tables displayed as lists in the UI
  core/src/migrations/000064-addSortIndicies.ts
Labels: enhancement

#1722 Fix link to events API test page
  ui/ui-enterprise/pages/apiKey/[id]/edit.tsx
Labels: bug

#1724 UI resilience if API has errors
  ui/ui-components/components/navigation/setupStepsNavProgressBar.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-components/utils/statusHandler.ts
Labels: bug

#1725 When disconnecting App connections, only disconnect the App in question
  core/__tests__/models/app/app.ts
  core/src/initializers/rpc.ts
  core/src/models/App.ts
Labels: bug
