Repository grouparoo/grouparoo, pull requests merged in 2021-10, with the labels that each got.

#2356 `timed_run` test runs `grouparoo demo -c` (no purchases)
  bin/timed_run
Labels: bug

#2383 `actionhero` v 27.1.5
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2384 `CLSTasks` include the `QueueLock` Middleware
  core/__tests__/tasks/recordProperty/enqueue/enqueue.ts
  core/src/classes/tasks/clsTask.ts
  core/src/tasks/group/run.ts
  core/src/tasks/system/status/statusSample.ts
Labels: bug

#2354 Use `displayNames` in UI App Selector Cards
  core/__tests__/actions/apps.ts
  core/src/actions/apps.ts
  core/src/modules/plugins.ts
  ui/ui-components/components/appSelectorList.tsx
Labels: enhancement

#2386 Moves to Facebook v12 API
  plugins/@grouparoo/facebook/__tests__/fixtures/export-records-custom.js
  plugins/@grouparoo/facebook/package.json
  pnpm-lock.yaml
  tools/license-checker/check
Labels: plugin

#2355 passing in demo types as flags
  apps/staging-config/package.json
  plugins/@grouparoo/demo/__tests__/bin/accounts.ts
  plugins/@grouparoo/demo/__tests__/bin/admins.ts
  plugins/@grouparoo/demo/__tests__/bin/reset.ts
  plugins/@grouparoo/demo/__tests__/bin/setup.ts
  plugins/@grouparoo/demo/__tests__/bin/users.ts
  plugins/@grouparoo/demo/config/accounts/groups/high_value_accounts.json
  plugins/@grouparoo/demo/config/accounts/sources/account_users.json
  plugins/@grouparoo/demo/config/mailchimp/users/destinations/mailchimp.json
  plugins/@grouparoo/demo/config/salesforce/users/destinations/salesforce.json
  plugins/@grouparoo/demo/data/sql/bigquery.sql
  plugins/@grouparoo/demo/data/sql/snowflake.sql
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/demo.ts
  plugins/@grouparoo/demo/src/util/config.ts
  plugins/@grouparoo/demo/src/util/configFiles.ts
Labels: internal

#2392 Fix a typo in core/README.md
  core/README.md
Labels: documentation

#2348 add "Create Model" setup step
  core/__tests__/actions/setupSteps.ts
  core/__tests__/models/setupStep.ts
  core/src/modules/ops/setupSteps.ts
Labels: enhancement

#2393 Update README.md
  core/README.md
Labels: documentation

#2385 Split import and export buttons on Record Edit page
  core/__tests__/actions/records/importAndExport.ts
  core/__tests__/actions/records/records.ts
  core/src/actions/records.ts
  core/src/config/routes.ts
  ui/ui-components/pages/record/[id]/edit.tsx
  ui/ui-components/utils/apiData.ts
Labels: bug, enhancement

#2390 Clarify auto migration logic in initializer
  core/src/config/sequelize.ts
Labels: internal

#2394 Set `RecordProperty.startedAt` to null after import
  core/__tests__/tasks/recordProperty/importRecordProperties.ts
  core/__tests__/tasks/recordProperty/importRecordProperty.ts
  core/src/modules/ops/record.ts
  core/src/tasks/recordProperty/importRecordProperties.ts
  core/src/tasks/recordProperty/importRecordProperty.ts
Labels: enhancement

#2388 Add `modelId` input to action schedules:list
  core/__tests__/actions/schedules.ts
  core/src/actions/schedules.ts
  ui/ui-components/pages/source/[id]/mapping.tsx
Labels: enhancement

#2396 Store config files generated in navigation test in `/tmp`
  core/__tests__/actions/navigation.ts
Labels: internal

#2341 View records with invalid values
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  core/__tests__/actions/records/records.ts
  core/__tests__/bin/__snapshots__/sync.ts.snap
  core/__tests__/models/record/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/models/recordProperty/recordProperty.ts
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/tasks/recordProperty/importRecordProperties.ts
  core/__tests__/tasks/recordProperty/importRecordProperty.ts
  core/__tests__/tasks/run/internalRun.ts
  core/bin/debug
  core/src/actions/properties.ts
  core/src/actions/records.ts
  core/src/migrations/000084-addRecordPropertyInvalidReason.ts
  core/src/migrations/000085-addRecordsPropertyInvalid.ts
  core/src/models/GrouparooRecord.ts
  core/src/models/Property.ts
  core/src/models/RecordProperty.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/recordProperty.ts
  core/src/tasks/recordProperty/importRecordProperties.ts
  ui/ui-components/components/record/arrayRecordPropertyList.tsx
  ui/ui-components/components/record/list.tsx
  ui/ui-components/pages/record/[id]/edit.tsx
Labels: enhancement

#2473 Bug fixes for appRefreshQuery
  core/src/models/AppRefreshQuery.ts
  core/src/tasks/appRefreshQuery/check.ts
Labels: bug

#2440 Hubspot custom objects plugin
  plugins/@grouparoo/hubspot/__tests__/.env.example
  plugins/@grouparoo/hubspot/__tests__/export-contacts/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-contacts/export-record.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/destination-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/export-records-contact.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/export-records-custom-object.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/export-record.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/destination-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/export-records-contact.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/export-records-custom-object.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/integration/hubspot-export.js
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/public/templates/destination/contacts/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/public/templates/destination/objects/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/client/client.ts
  plugins/@grouparoo/hubspot/src/lib/client/objects.ts
  plugins/@grouparoo/hubspot/src/lib/connect.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationMappingOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/exportRecord.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/listMethods.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/destinationMappingOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/destinationOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/exportRecords.ts
  plugins/@grouparoo/hubspot/src/lib/export/customObject.ts
  plugins/@grouparoo/hubspot/src/lib/export/options.ts
  plugins/@grouparoo/hubspot/src/lib/shared/exportArrayProperties.ts
Labels: plugin

#2474 Spread out purchases and other objects better
  plugins/@grouparoo/demo/src/util/sample_data.ts
  plugins/@grouparoo/demo/src/util/shared.ts
Labels: internal
