Repository grouparoo/grouparoo, pull requests merged in 2021-03, with the labels that each got.

#1373 [mailchimp] Add export tests
  plugins/@grouparoo/mailchimp/__tests__/.env.example
  plugins/@grouparoo/mailchimp/__tests__/data/emails.txt
  plugins/@grouparoo/mailchimp/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/mailchimp/__tests__/export/export-profile.ts
  plugins/@grouparoo/mailchimp/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mailchimp/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mailchimp/src/lib/shared/updateProfile.ts
Labels: enhancement

#1394 Maintain Option Types
  core/__tests__/models/option.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/run/run.ts
  core/src/initializers/events.ts
  core/src/migrations/000060-addTypeToOption.ts
  core/src/models/Destination.ts
  core/src/models/Option.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/modules/optionHelper.ts
  core/src/tasks/event/associateProfile.ts
  plugins/@grouparoo/app-templates/src/source/query/profileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperties.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profiles.ts
  plugins/@grouparoo/app-templates/src/source/table/propertyOptions.ts
  plugins/@grouparoo/app-templates/src/source/table/scheduleOptions.ts
  plugins/@grouparoo/app-templates/src/source/table/sourceFilters.ts
  plugins/@grouparoo/app-templates/src/source/table/sourcePreview.ts
  plugins/@grouparoo/bigquery/__tests__/integration/cli.ts
  plugins/@grouparoo/bigquery/src/lib/connect.ts
  plugins/@grouparoo/csv/src/lib/file-import/profiles.ts
  plugins/@grouparoo/csv/src/lib/file-import/sourceRunPercentComplete.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/eventStream.ts
  plugins/@grouparoo/facebook/src/lib/connect.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/profiles.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/spreadsheet.ts
  plugins/@grouparoo/hubspot/src/lib/client.ts
  plugins/@grouparoo/logger/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/logger/src/lib/test.ts
  plugins/@grouparoo/mailchimp/src/lib/connect.ts
  plugins/@grouparoo/mailchimp/src/lib/export-id/exportProfile.ts
  plugins/@grouparoo/mailchimp/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mailchimp/src/lib/import/profiles.ts
  plugins/@grouparoo/mailchimp/src/lib/shared/destinationMappingOptions.ts
  plugins/@grouparoo/mysql/src/lib/connect.ts
  plugins/@grouparoo/mysql/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/mysql/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/mysql/src/lib/export/exportProfile.ts
  plugins/@grouparoo/postgres/src/lib/connect.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/exportProfile.ts
  plugins/@grouparoo/salesforce/src/lib/export/options.ts
  plugins/@grouparoo/sendgrid/src/lib/connect.ts
  plugins/@grouparoo/snowflake/src/lib/connect.ts
  ui/ui-enterprise/pages/app/[id]/edit.tsx
  ui/ui-enterprise/pages/destination/[id]/edit.tsx
  ui/ui-enterprise/pages/property/[id]/edit.tsx
  ui/ui-enterprise/pages/source/[id]/edit.tsx
  ui/ui-enterprise/pages/source/[id]/schedule.tsx
Labels: bug

#1400 Update to `main` integration branch
  .circleci/config.yml
  .github/workflows/publish-docs.yml
  bin/publish
  core/README.md
  core/bin/publish-docs
  lerna.json
  tools/merger/data/ci/base.yml.template
Labels: internal

#1408 Prepend rolling charts with 0-value data for consistent x-axis
  pnpm-lock.yaml
  ui/ui-components/components/visualizations/grouparooChart.tsx
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/pages/resque/overview.tsx
Labels: enhancement

#1409 Better page change detection for PageTransition
  ui/ui-components/components/pageTransition.tsx
Labels: bug

#1396 Mailchimp: remove tags before deleting a user.
  plugins/@grouparoo/mailchimp/__tests__/data/emails.txt
  plugins/@grouparoo/mailchimp/__tests__/export/export-profile.ts
  plugins/@grouparoo/mailchimp/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mailchimp/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mailchimp/src/lib/shared/updateProfile.ts
Labels: enhancement

#1410 Handle empty args in dbtProfile
  plugins/@grouparoo/dbt/__tests__/settings/parse.ts
  plugins/@grouparoo/dbt/src/settings/parse.ts
Labels: bug

#1411 Redshift not doing batching of profile property values
  plugins/@grouparoo/redshift/src/lib/table-import/connection.ts
Labels: bug

#1415 Update Actionhero and Node-Resque
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package-lock.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#1418 Reset Cluster removes all data in Redis
  core/__tests__/actions/cluster.ts
  core/src/actions/cluster.ts
  ui/ui-components/components/settings/clearCache.tsx
  ui/ui-components/components/visualizations/grouparooChart.tsx
Labels: enhancement

#1421 Log a warning when using more than one worker with SQLite + Session TTL
  core/src/config/tasks.ts
  core/src/initializers/environment.ts
  core/src/initializers/session.ts
  pnpm-lock.yaml
Labels: enhancement

#1422 Destination Profile Preview does not crash with new optional mapping
  core/__tests__/actions/destinations.ts
  core/src/modules/ops/destination.ts
  ui/ui-components/components/visualizations/homepageWidgets.tsx
Labels: bug

#1426 Fix off-by-one error when limiting batch size
  plugins/@grouparoo/app-templates/__tests__/destination/batch.ts
  plugins/@grouparoo/app-templates/__tests__/destination/group.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/app-templates/src/destination/batch/exportProfiles.ts
  plugins/@grouparoo/app-templates/src/destination/group/exportProfiles.ts
  pnpm-lock.yaml
Labels: bug

#1427 Sort the data in GrouparooChart by x-axis
  ui/ui-components/components/visualizations/grouparooChart.tsx
Labels: bug

#1430 Show warning when using SQLite and >1 WORKERS
  core/src/initializers/environment.ts
Labels: bug

#1435 Link from Destinations List changes based on UI edition
  ui/ui-components/pages/destinations.tsx
Labels: enhancement

#1438 Do not prepend chart data if there are no points
  pnpm-lock.yaml
  ui/ui-components/components/visualizations/grouparooChart.tsx
Labels: bug

#1440 Identifying should default to false
  plugins/@grouparoo/app-templates/public/templates/table-property/{{{id}}}.js.template
Labels: bug

#1450 Support next.js pre-rendering of _error page
  pnpm-lock.yaml
  ui/ui-components/pages/_error.tsx
Labels: bug

#1451 Prevent deadlock for profileProperty:importProfileProperties
  core/__tests__/models/profile/profile.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/src/models/Profile.ts
  core/src/models/ProfileProperty.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
Labels: bug

#1437 Pool and Retry Settings for Sequelize
  core/src/config/sequelize.ts
  core/src/config/tasks.ts
  core/src/initializers/environment.ts
  ui/ui-components/pages/resque/overview.tsx
Labels: enhancement

#1453 fix: falsy check on formatVar could clear zeros
  plugins/@grouparoo/marketo/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/sailthru/src/lib/export/exportProfile.ts
  plugins/@grouparoo/zendesk/src/lib/export/exportProfile.ts
Labels: bug

#1391 Pardot destination
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/pardot/.npmignore
  plugins/@grouparoo/pardot/LICENSE.txt
  plugins/@grouparoo/pardot/README.md
  plugins/@grouparoo/pardot/__tests__/.env.example
  plugins/@grouparoo/pardot/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/pardot/__tests__/export/export-profiles.ts
  plugins/@grouparoo/pardot/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/pardot/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/pardot/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/pardot/jest.config.js
  plugins/@grouparoo/pardot/jest.setup.js
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pardot/public/@grouparoo/pardot/pardot.png
  plugins/@grouparoo/pardot/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/pardot/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/pardot/src/initializers/plugin.ts
  plugins/@grouparoo/pardot/src/lib/appOptions.ts
  plugins/@grouparoo/pardot/src/lib/client.ts
  plugins/@grouparoo/pardot/src/lib/connect.ts
  plugins/@grouparoo/pardot/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/pardot/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/pardot/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/pardot/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/pardot/src/lib/export/listMethods.ts
  plugins/@grouparoo/pardot/src/lib/parallelism.ts
  plugins/@grouparoo/pardot/src/lib/test.ts
  plugins/@grouparoo/pardot/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#1457 Reset Commands and Actions
  core/__tests__/actions/cluster.ts
  core/__tests__/actions/reset.ts
  core/__tests__/bin/generate.ts
  core/__tests__/bin/reset.ts
  core/__tests__/bin/validate.ts
  core/__tests__/modules/reset.ts
  core/src/actions/cluster.ts
  core/src/actions/reset.ts
  core/src/bin/apply.ts
  core/src/bin/destroy.ts
  core/src/bin/generate.ts
  core/src/bin/reset.ts
  core/src/bin/run.ts
  core/src/bin/status.ts
  core/src/bin/sync.ts
  core/src/bin/validate.ts
  core/src/config/routes.ts
  core/src/modules/cli.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/reset.ts
  ui/ui-components/components/settings/resetCache.tsx
  ui/ui-components/components/settings/resetCluster.tsx
  ui/ui-components/components/settings/resetData.tsx
  ui/ui-components/pages/settings/[tab].tsx
  ui/ui-components/utils/apiData.ts
Labels: enhancement

#1458 `grouparoo init` creates a .gitignore
  cli/__tests__/test.sh
  cli/src/lib/initialize.ts
  cli/templates/.gitignore
Labels: enhancement

#1461 QuerySourceTemplate was not setting the template files
  plugins/@grouparoo/app-templates/src/source/query/templates.ts
Labels: bug

#1460 [Pardot] fix: encode uri component when getting prospect by email
  plugins/@grouparoo/pardot/__tests__/export/export-profiles.ts
  plugins/@grouparoo/pardot/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/pardot/src/lib/client.ts
Labels: bug

#1463 Test CLI commands within context of App
  .circleci/config.yml
  apps/staging-community/__tests__/cli
  apps/staging-community/__tests__/integration
  apps/staging-enterprise/__tests__/cli
  apps/staging-enterprise/__tests__/integration
  core/src/modules/configLoaders/index.ts
  plugins/@grouparoo/customerio/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/sailthru/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/sailthru/public/templates/destination/{{{id}}}.js.template
  tools/merger/data/ci/apps/job.yml.template
  tools/shared/max_bg_procs
Labels: bug

#1465 Rename template .gitignore so it is not ignored
  cli/src/lib/initialize.ts
  cli/templates/gitignore
Labels: bug

#1468 Refactor `sortConfigObjectsWithIds` to use topological sort algorithm
  core/__tests__/classes/codeConfig.ts
  core/__tests__/fixtures/codeConfig/duplicate-id/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/codeConfig/syncTable.ts
  core/__tests__/modules/codeConfig/validate.ts
  core/src/classes/codeConfig.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/topologicalSort.ts
Labels: bug

#1484 Node v15 for local development
  .nvmrc
  pnpm-lock.yaml
Labels: internal

#1485 Next.js v10.0.9
  .github/workflows/update-branch.yml
  pnpm-lock.yaml
  tools/merger/github_action
  tools/merger/lockfile
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1487 Re-use AuthenticationError for session exceptions
  core/src/actions/session.ts
  core/src/modules/middleware/authentication.ts
Labels: internal

#1488 Suppress sentry shutdown errors if they occur
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
Labels: bug

#1489 Remove Underscore from HTTP headers
  core/__tests__/actions/sessions.ts
  core/src/modules/middleware/authentication.ts
  ui/ui-components/client/client.ts
Labels: bug

#1492 Add an initializer that looks for multiple versions of core
  core/src/initializers/coreVersionValidator.ts
Labels: enhancement

#1496 Test mysql container with MYSQL_ALLOW_EMPTY_PASSWORD
  .circleci/config.yml
  tools/merger/data/ci/plugin/mysql/docker.yml.template
Labels: internal

#1493 Grouparoo Init can run on Windows
  cli/src/utils/npm.ts
Labels: enhancement

#1499 Update Snowflake Packages & re-record nockfiles
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-profiles.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-get-changed-row-count.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-properties.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-property-rule-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-property.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profiles.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-schedule-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-source-filters.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-source-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-source-preview.js
  plugins/@grouparoo/snowflake/__tests__/query-import/import-property.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/import-property.ts
  plugins/@grouparoo/snowflake/package.json
  pnpm-lock.yaml
Labels: dependencies

#1500 Upgrade to type-fest@0.21.3 and es2019 compile target
  cli/tsconfig.json
  core/package.json
  core/tsconfig.json
  plugins/@grouparoo/app-templates/tsconfig.json
  plugins/@grouparoo/bigquery/tsconfig.json
  plugins/@grouparoo/csv/tsconfig.json
  plugins/@grouparoo/customerio/tsconfig.json
  plugins/@grouparoo/dbt/tsconfig.json
  plugins/@grouparoo/demo/tsconfig.json
  plugins/@grouparoo/facebook/tsconfig.json
  plugins/@grouparoo/files-local/tsconfig.json
  plugins/@grouparoo/files-s3/tsconfig.json
  plugins/@grouparoo/google-sheets/tsconfig.json
  plugins/@grouparoo/hubspot/tsconfig.json
  plugins/@grouparoo/intercom/tsconfig.json
  plugins/@grouparoo/iterable/tsconfig.json
  plugins/@grouparoo/logger/tsconfig.json
  plugins/@grouparoo/mailchimp/tsconfig.json
  plugins/@grouparoo/marketo/tsconfig.json
  plugins/@grouparoo/mysql/tsconfig.json
  plugins/@grouparoo/newrelic/tsconfig.json
  plugins/@grouparoo/onesignal/tsconfig.json
  plugins/@grouparoo/pardot/tsconfig.json
  plugins/@grouparoo/postgres/tsconfig.json
  plugins/@grouparoo/redshift/tsconfig.json
  plugins/@grouparoo/sailthru/tsconfig.json
  plugins/@grouparoo/salesforce/tsconfig.json
  plugins/@grouparoo/sendgrid/tsconfig.json
  plugins/@grouparoo/sentry/tsconfig.json
  plugins/@grouparoo/snowflake/tsconfig.json
  plugins/@grouparoo/spec-helper/tsconfig.json
  plugins/@grouparoo/zendesk/tsconfig.json
  pnpm-lock.yaml
  ui/ui-components/package.json
Labels: dependencies

#1504 Grouparoo Files are cached locally for 1 hour
  core/__tests__/integration/files.ts
  core/src/classes/fileTransportLocal.ts
  plugins/@grouparoo/files-s3/src/classes/s3.ts
Labels: enhancement

#1521 Add support for redis usernames and adds `REDIS_USER`
  core/src/config/redis.ts
Labels: enhancement

#1522 User REDIS_PASS to match DB_PASS
  core/src/config/redis.ts
Labels: documentation

#1523 Ignore 1-char Redis usernames
  core/src/config/redis.ts
Labels: bug

#1524 Do not try to re-associate imports that have an error
  core/__tests__/tasks/import/associateProfiles.ts
  core/src/tasks/import/associateProfiles.ts
Labels: bug

#1525 Always display enough of the progress bar to see the label
  ui/ui-components/components/visualizations/homepageWidgets.tsx
Labels: bug

#1503 [WIP] SQLite Source
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/sqlite/.npmignore
  plugins/@grouparoo/sqlite/LICENSE.txt
  plugins/@grouparoo/sqlite/README.md
  plugins/@grouparoo/sqlite/__tests__/data/profiles.csv
  plugins/@grouparoo/sqlite/__tests__/data/purchases.csv
  plugins/@grouparoo/sqlite/__tests__/integration/cli.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-query-import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-table-import.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/getChangedRows.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/import-property.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/profiles.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/import-property.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/profile-property-rule-options.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/profiles.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/schedule-options.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/source-filters.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/source-options.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/source-preview.ts
  plugins/@grouparoo/sqlite/__tests__/utils/data.ts
  plugins/@grouparoo/sqlite/jest.config.js
  plugins/@grouparoo/sqlite/jest.setup.js
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/sqlite/public/@grouparoo/sqlite/sqlite.svg
  plugins/@grouparoo/sqlite/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/sqlite/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/sqlite/src/initializers/plugin.ts
  plugins/@grouparoo/sqlite/src/lib/connect.ts
  plugins/@grouparoo/sqlite/src/lib/disconnect.ts
  plugins/@grouparoo/sqlite/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/sqlite/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/sqlite/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/sqlite/src/lib/export/exportProfile.ts
  plugins/@grouparoo/sqlite/src/lib/query-import/connection.ts
  plugins/@grouparoo/sqlite/src/lib/query-import/executeQuery.ts
  plugins/@grouparoo/sqlite/src/lib/query-import/getChangedRows.ts
  plugins/@grouparoo/sqlite/src/lib/sqlite.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/connection.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getChangedRowCount.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getChangedRows.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getSampleRows.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getTables.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/util.ts
  plugins/@grouparoo/sqlite/src/lib/test.ts
  plugins/@grouparoo/sqlite/src/lib/validateQuery.ts
  plugins/@grouparoo/sqlite/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#1486 Pipedrive Destination
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/pipedrive/.npmignore
  plugins/@grouparoo/pipedrive/LICENSE.txt
  plugins/@grouparoo/pipedrive/README.md
  plugins/@grouparoo/pipedrive/__tests__/.env.example
  plugins/@grouparoo/pipedrive/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/pipedrive/__tests__/export/export-profile.ts
  plugins/@grouparoo/pipedrive/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/pipedrive/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/pipedrive/__tests__/utils/shared.ts
  plugins/@grouparoo/pipedrive/jest.config.js
  plugins/@grouparoo/pipedrive/jest.setup.js
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/pipedrive/public/@grouparoo/pipedrive/pipedrive.png
  plugins/@grouparoo/pipedrive/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/pipedrive/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/pipedrive/src/initializers/plugin.ts
  plugins/@grouparoo/pipedrive/src/lib/client.ts
  plugins/@grouparoo/pipedrive/src/lib/connect.ts
  plugins/@grouparoo/pipedrive/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/pipedrive/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/pipedrive/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/pipedrive/src/lib/export/exportProfile.ts
  plugins/@grouparoo/pipedrive/src/lib/export/listMethods.ts
  plugins/@grouparoo/pipedrive/src/lib/test.ts
  plugins/@grouparoo/pipedrive/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#1527 Split node_modules cache on CI
  .circleci/config.yml
  plugins/@grouparoo/sqlite/package.json
  pnpm-lock.yaml
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/publish/core.yml.template
  tools/merger/data/ci/ui/job.yml.template
  tools/merger/src/ci_generate.js
Labels: invalid

#1529 Imports and Exports that aren't complete after a time will be retried
  core/__tests__/tasks/export/enqueue.ts
  core/__tests__/tasks/import/associateProfiles.ts
  core/src/config/sequelize.ts
  core/src/initializers/settings.ts
  core/src/migrations/000061-addImportStartedAt.ts
  core/src/models/Import.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/import.ts
  core/src/tasks/event/associateProfiles.ts
  core/src/tasks/export/enqueue.ts
  core/src/tasks/import/associateProfiles.ts
Labels: bug, enhancement

#1526 Wrap CLI commands and Initializers in transactions
  core/__tests__/bin/reset.ts
  core/__tests__/bin/run.ts
  core/__tests__/tasks/system/status.ts
  core/__tests__/tasks/system/sweeper.ts
  core/__tests__/tasks/system/telemetry.ts
  core/src/bin/reset.ts
  core/src/bin/run.ts
  core/src/bin/status.ts
  core/src/classes/initializers/clsInitializer.ts
  core/src/config/tasks.ts
  core/src/initializers/codeConfig.ts
  core/src/initializers/plugins.ts
  core/src/initializers/rpc.ts
  core/src/initializers/session.ts
  core/src/initializers/settings.ts
  core/src/initializers/setupSteps.ts
  core/src/initializers/teamPermissions.ts
  core/src/modules/cls.ts
  core/src/tasks/event/associateProfile.ts
  core/src/tasks/import/associateProfile.ts
  core/src/tasks/system/notifiers.ts
  core/src/tasks/system/status.ts
  core/src/tasks/system/sweeper.ts
  core/src/tasks/system/telemetry.ts
Labels: bug

#1532 If GROUPAROO_ENV_CONFIG_FILE is provided, don't try to load a local .env file
  core/src/config/environment.ts
  plugins/@grouparoo/spec-helper/src/lib/integrationSpecHelper.ts
Labels: bug

#1535 Properly bump `startedAt` for old Imports or Exports when retried
  core/__tests__/tasks/export/enqueue.ts
  core/__tests__/tasks/import/associateProfiles.ts
  core/src/initializers/settings.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/import.ts
Labels: bug

#1528 Default option values
  core/__tests__/models/option.ts
  core/src/models/App.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/pardot/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
Labels: enhancement

#1538 `grouparoo install` with no argument runs `npm install`
  cli/src/lib/install.ts
Labels: bug

#1533 Plugins can choose to obfuscate passwords
  core/__tests__/actions/apps.ts
  core/__tests__/models/app/app.ts
  core/__tests__/models/option.ts
  core/src/classes/plugin.ts
  core/src/models/App.ts
  core/src/modules/ops/app.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/bigquery/src/lib/appOptions.ts
  plugins/@grouparoo/customerio/src/initializers/plugin.ts
  plugins/@grouparoo/customerio/src/lib/appOptions.ts
  plugins/@grouparoo/facebook/src/initializers/plugin.ts
  plugins/@grouparoo/facebook/src/lib/appOptions.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/appOptions.ts
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/appOptions.ts
  plugins/@grouparoo/intercom/src/initializers/plugin.ts
  plugins/@grouparoo/intercom/src/lib/appOptions.ts
  plugins/@grouparoo/iterable/src/initializers/plugin.ts
  plugins/@grouparoo/iterable/src/lib/appOptions.ts
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/lib/appOptions.ts
  plugins/@grouparoo/marketo/src/initializers/plugin.ts
  plugins/@grouparoo/marketo/src/lib/appOptions.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/src/lib/appOptions.ts
  plugins/@grouparoo/onesignal/src/initializers/plugin.ts
  plugins/@grouparoo/onesignal/src/lib/appOptions.ts
  plugins/@grouparoo/pardot/src/lib/appOptions.ts
  plugins/@grouparoo/pipedrive/src/initializers/plugin.ts
  plugins/@grouparoo/pipedrive/src/lib/appOptions.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/appOptions.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/lib/appOptions.ts
  plugins/@grouparoo/salesforce/src/initializers/plugin.ts
  plugins/@grouparoo/salesforce/src/lib/appOptions.ts
  plugins/@grouparoo/sendgrid/src/initializers/plugin.ts
  plugins/@grouparoo/sendgrid/src/lib/appOptions.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/lib/appOptions.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  plugins/@grouparoo/zendesk/src/initializers/plugin.ts
  plugins/@grouparoo/zendesk/src/lib/appOptions.ts
  ui/ui-enterprise/pages/app/[id]/edit.tsx
  ui/ui-enterprise/pages/destination/[id]/edit.tsx
  ui/ui-enterprise/pages/source/[id]/edit.tsx
Labels: enhancement

#1539 Use init dir for project name in `grouparoo init`
  cli/__tests__/test.sh
  cli/src/lib/initialize.ts
  cli/templates/package.json
Labels: enhancement

#1540 Log internal SQL statements at `debug` log level
  core/package.json
  core/src/config/sequelize.ts
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/spec-helper/package.json
  pnpm-lock.yaml
Labels: dependencies, enhancement

#1542 facebook-nodejs-business-sdk v10.0.0
  plugins/@grouparoo/facebook/__tests__/fixtures/export-profiles-custom.js
  plugins/@grouparoo/facebook/package.json
  pnpm-lock.yaml
  tools/license-checker/check
Labels: plugin

#1541 Upgrade `postgres-date` and fix timezone appending for strings without zone
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/postgres/src/lib/connect.ts
  pnpm-lock.yaml
Labels: dependencies

#1537 Add custom fields tests for Hubspot & Support Dates
  plugins/@grouparoo/hubspot/__tests__/.env.example
  plugins/@grouparoo/hubspot/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/export/export-profile.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/hubspot/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export/exportProfile.ts
Labels: enhancement

#1531 Better validation errors when using the wrong `id`
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/codeConfig/errors.ts
  core/__tests__/modules/codeConfig/validate.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/topologicalSort.ts
Labels: bug

#1534 Properly handle changing email address for Pipedrive and Iterable
  plugins/@grouparoo/iterable/__tests__/export/export-profile.ts
  plugins/@grouparoo/iterable/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/iterable/src/lib/export/exportProfile.ts
  plugins/@grouparoo/pipedrive/__tests__/export/export-profile.ts
  plugins/@grouparoo/pipedrive/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/pipedrive/src/lib/export/exportProfile.ts
Labels: bug

#1565 Nextjs v10.1.0
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1567 Add a delay for pub/sub commands to break mock redis callback chains
  core/src/initializers/rpc.ts
Labels: bug

#1568 Add info level to email strict validation errors.
  plugins/@grouparoo/mailchimp/__tests__/data/emails.txt
  plugins/@grouparoo/mailchimp/__tests__/export/export-profile.ts
  plugins/@grouparoo/mailchimp/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailchimp/src/lib/shared/updateProfile.ts
  pnpm-lock.yaml
Labels: enhancement

#1570 Use `pluralize` to properly pluralize words
  core/package.json
  core/src/bin/apply.ts
  core/src/bin/validate.ts
  pnpm-lock.yaml
Labels: bug

#1572 Disable logging to file without `GROUPAROO_LOGS_PATH` set
  .gitignore
  apps/staging-community/.env.example
  apps/staging-enterprise/.env.example
  cli/templates/.env
  core/src/config/api.ts
Labels: enhancement

#1574 Query result issue.
  plugins/@grouparoo/mongo/__tests__/query-import/import-property.ts
  plugins/@grouparoo/mongo/src/lib/query-import/connection.ts
  plugins/@grouparoo/mongo/src/lib/query-import/executeQuery.ts
Labels: bug

#1576 Add longer sleep in RPC test
  core/__tests__/models/app/app.ts
Labels: internal
