Repository grouparoo/grouparoo, pull requests merged in 2021-02, with the labels that each got.

#1249 Actionhero v25.0.5 + JSON5 v2.2.0
  core/package.json
  core/src/modules/configLoaders/index.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/dataPurchases.ts
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1250 Intercom bug fix for external_id assumptions
  plugins/@grouparoo/intercom/src/lib/export-contacts/exportProfile.ts
Labels: bug

#1252 New relic setup
  plugins/@grouparoo/newrelic/README.md
Labels: internal

#1253 Another env variable for newrelic
  plugins/@grouparoo/newrelic/README.md
Labels: internal

#1251 Set the Sequelize pool size via WORKERS or SEQUELIZE_POOL_SIZE, whichever is larger
  core/src/config/sequelize.ts
Labels: bug

#1256 Update CI
  .circleci/config.yml
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/publish/core.yml.template
  tools/merger/data/ci/ui/job.yml.template
  tools/merger/src/ci_generate.js
Labels: internal

#1257 Ensure that sessions have teamMember IDs
  core/src/initializers/session.ts
Labels: bug

#1258 `/object` page works by looking up IDs in the database
  core/__tests__/actions/object.ts
  core/src/actions/object.ts
  core/src/config/routes.ts
  ui/ui-components/pages/object/[id].tsx
  ui/ui-components/utils/apiData.ts
Labels: enhancement

#1259 Update Github links to new WWW pages
  .github/SECURITY.md
Labels: documentation

#1261 peerDependencies match core version
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: bug, dependencies

#1263 Export CLI command info for use on WWW site
  .gitignore
  core/__tests__/bin/build_static_refs.ts
  core/bin/build_static_refs
  core/src/utils/cli.js
Labels: internal

#1264 Try no peer dependencies
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: bug, dependencies

#1265 Upgrade React, React-Dom and Enzyme for react 17
  pnpm-lock.yaml
  ui/ui-community/jest.setup.js
  ui/ui-community/package.json
  ui/ui-components/jest.setup.js
  ui/ui-components/package.json
  ui/ui-enterprise/jest.setup.js
  ui/ui-enterprise/package.json
Labels: dependencies

#1266 ah-next-plugin v0.5.0
  core/package.json
  plugins/@grouparoo/iterable/package-lock.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/components/visualizations/eventsTotals.tsx
  ui/ui-components/components/visualizations/rollingChart.tsx
  ui/ui-components/components/visualizations/runDurations.tsx
  ui/ui-components/package.json
  ui/ui-components/pages/run/[id]/edit.tsx
  ui/ui-enterprise/package.json
Labels: dependencies

#1228 Code config to make it easier to sync wide mapping table to destinations
  core/__tests__/classes/codeConfig.ts
  core/__tests__/fixtures/codeConfig/sync-table/initial/config.js
  core/__tests__/modules/codeConfig/syncTable.ts
  core/__tests__/modules/codeConfig/validate.ts
  core/src/bin/apply.ts
  core/src/bin/validate.ts
  core/src/classes/codeConfig.ts
  core/src/modules/configLoaders/apiKey.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/setting.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/configLoaders/syncTable.ts
  core/src/modules/configLoaders/team.ts
  core/src/modules/configLoaders/teamMember.ts
  core/src/modules/ops/app.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/app-templates/src/source/table/meta.ts
  plugins/@grouparoo/app-templates/src/source/table/pluginMethods.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/mysql/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getColumns.ts
Labels: enhancement

#1268 Updating more deps for NPM
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-components/pages/swagger.tsx
  ui/ui-components/scss/grouparoo.scss
  ui/ui-enterprise/package.json
Labels: dependencies

#1269 Use `legacy-peer-deps` if npm v7 in use
  cli/src/utils/npm.ts
Labels: dependencies

#1276 Bootstrapping a Property will not fail if there is already an Identifying Property
  core/__tests__/models/source.ts
  core/src/models/Property.ts
  core/src/modules/ops/source.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-query-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-query-import.ts
Labels: internal

#1280 Remove SetupStep to create a Team
  core/__tests__/actions/setupSteps.ts
  core/__tests__/models/setupStep.ts
  core/src/modules/ops/setupSteps.ts
Labels: enhancement

#1281 Update Bigquery and Snowflake package.json to indicate node v14 is OK
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/snowflake/package.json
Labels: bug

#1283 UI enterprise bugs (React 17 compatibility)
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  cli/templates/package.json
  pnpm-lock.yaml
  ui/ui-community/next.config.js
  ui/ui-components/components/datePicker.tsx
  ui/ui-components/package.json
  ui/ui-components/scss/grouparoo.scss
  ui/ui-enterprise/next.config.js
  ui/ui-enterprise/package.json
Labels: bug

#1284 Provide a text input for dates on Safari
  ui/ui-components/components/datePicker.tsx
Labels: enhancement

#1285 Update README with focus on customer-centric audience
  core/README.md
Labels: enhancement

#1282 Node.js v15
  .circleci/config.yml
  .nvmrc
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  cli/package.json
  cli/templates/package.json
  clients/@grouparoo/web/package.json
  core/package.json
  package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/cli/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/command/job.yml.template
  tools/merger/data/ci/core-local/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/publish/core.yml.template
  tools/merger/data/ci/publish/internal.yml.template
  tools/merger/data/ci/ui/job.yml.template
  tools/merger/package.json
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-enterprise/package.json
Labels: enhancement

#1286 Resque Updates
  core/package.json
  core/src/actions/cluster.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-components/components/runs/list.tsx
  ui/ui-components/components/visualizations/rollingChart.tsx
  ui/ui-components/pages/resque/overview.tsx
  ui/ui-components/pages/settings/[tab].tsx
Labels: enhancement

#1287 SetupSteps link to www/docs for help
  core/__tests__/actions/setupSteps.ts
  core/src/models/SetupStep.ts
  core/src/modules/ops/setupSteps.ts
  ui/ui-components/components/setupSteps/setupStepCard.tsx
Labels: enhancement

#1298 Manually update dependencies
  cli/package.json
  clients/@grouparoo/web/package.json
  core/package.json
  package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1299 `grouparoo init` does not include any plugins
  cli/src/grouparoo.ts
  cli/src/lib/initialize.ts
  cli/templates/package.json
  core/src/bin/generate.ts
Labels: enhancement

#1302 Reset previously set ProfileId when changing tracked Group in Destination Preview
  core/src/models/Destination.ts
  ui/ui-components/components/destination/profilePreview.tsx
Labels: bug

#1303 CLI Install & Uninstall
  cli/__tests__/test.sh
  cli/package.json
  cli/src/grouparoo.ts
  cli/src/lib/install.ts
  cli/src/lib/uninstall.ts
  cli/src/utils/getCoreVersion.ts
  cli/src/utils/isGrouparooPlugin.ts
  cli/src/utils/npm.ts
  pnpm-lock.yaml
Labels: bug, enhancement

#1301 Copy Code Config README templates into the work directory.
  cli/__tests__/test.sh
  cli/src/lib/initialize.ts
  cli/src/utils/templates.ts
  cli/templates/config/README.md
  cli/templates/config/apps/README.md
  cli/templates/config/destinations/README.md
  cli/templates/config/groups/README.md
  cli/templates/config/properties/README.md
  cli/templates/config/sources/README.md
Labels: enhancement

#1308 Require `parent` when generating code-config objects
  core/__tests__/bin/generate.ts
  core/public/templates/events/app/{{{id}}}.js.template
  core/public/templates/events/property/{{{id}}}.js.template
  core/public/templates/events/source/{{{id}}}.js.template
  core/public/templates/manual/property/{{{id}}}.js.template
  core/public/templates/manual/source/{{{id}}}.js.template
  core/public/templates/teamMembers/{{{id}}}.js.template
  core/src/bin/generate.ts
  core/src/classes/configTemplate.ts
  core/src/templates/events.ts
  core/src/templates/manual.ts
  core/src/templates/teamMember.ts
  plugins/@grouparoo/app-templates/public/templates/query-property/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/query-schedule/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/query-source/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-property/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-schedule/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-source/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/src/destination/templates.ts
  plugins/@grouparoo/app-templates/src/source/query/templates.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
  plugins/@grouparoo/csv/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/csv/src/lib/templates.ts
  plugins/@grouparoo/facebook/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/templates.ts
  plugins/@grouparoo/hubspot/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/intercom/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/destination/email/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/destination/id/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/src/lib/templates.ts
  plugins/@grouparoo/marketo/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/mysql/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/postgres/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/redshift/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/salesforce/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/zendesk/public/templates/destination/{{{id}}}.js.template
  pnpm-lock.yaml
Labels: enhancement

#1309 `cluster:destroy` tries to remove resque errors
  core/__tests__/actions/cluster.ts
  core/src/actions/cluster.ts
Labels: enhancement

#1290 Sendgrid Marketing Destination
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/sendgrid/.npmignore
  plugins/@grouparoo/sendgrid/LICENSE.txt
  plugins/@grouparoo/sendgrid/README.md
  plugins/@grouparoo/sendgrid/__tests__/.env.example
  plugins/@grouparoo/sendgrid/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/sendgrid/__tests__/export/export-profile.ts
  plugins/@grouparoo/sendgrid/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/sendgrid/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/sendgrid/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/sendgrid/__tests__/utils/shared.ts
  plugins/@grouparoo/sendgrid/jest.config.js
  plugins/@grouparoo/sendgrid/jest.setup.js
  plugins/@grouparoo/sendgrid/package-lock.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sendgrid/public/@grouparoo/sendgrid/sendgrid.png
  plugins/@grouparoo/sendgrid/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/sendgrid/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/sendgrid/src/initializers/plugin.ts
  plugins/@grouparoo/sendgrid/src/lib/client.ts
  plugins/@grouparoo/sendgrid/src/lib/connect.ts
  plugins/@grouparoo/sendgrid/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/sendgrid/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/sendgrid/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/sendgrid/src/lib/export/exportProfile.ts
  plugins/@grouparoo/sendgrid/src/lib/export/fieldsMethods.ts
  plugins/@grouparoo/sendgrid/src/lib/export/listMethods.ts
  plugins/@grouparoo/sendgrid/src/lib/test.ts
  plugins/@grouparoo/sendgrid/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#1310 handle boolean cases
  core/src/modules/ops/profileProperty.ts
Labels: bug

#1315 Get core version exactly from installed package.json for `grouparoo install`
  cli/src/lib/install.ts
  cli/src/lib/uninstall.ts
  cli/src/utils/JSONUtils.ts
  cli/src/utils/getCoreVersion.ts
Labels: enhancement

#1307 [Code Config] Add Schedule objects to Sources on generate
  core/__tests__/modules/configTemplate.ts
  core/src/bin/generate.ts
  core/src/classes/configTemplate.ts
  plugins/@grouparoo/app-templates/public/templates/query-schedule/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/query-source/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-schedule/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-source/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/src/source/query/templates.ts
  plugins/@grouparoo/app-templates/src/source/table/scheduleOptions.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/csv/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/csv/src/initializers/plugin.ts
  plugins/@grouparoo/csv/src/lib/templates.ts
  plugins/@grouparoo/google-sheets/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/templates.ts
  plugins/@grouparoo/mailchimp/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/lib/templates.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
Labels: enhancement

#1314 Remove ability to disable SCHEDULER
  .circleci/config.yml
  Procfile
  apps/staging-community/.env.example
  apps/staging-enterprise/.env.example
  cli/templates/.env
  core/__tests__/bin/run.ts
  core/src/config/tasks.ts
  tools/merger/data/ci/apps/job.yml.template
Labels: enhancement

#1316 Always use local selection for Group for Destination Profile Preview
  ui/ui-components/components/destination/profilePreview.tsx
Labels: bug

#1318 Submit @grouparoo/core version to telemetry
  core/__tests__/tasks/telemetry.ts
  core/src/modules/telemetryReporters.ts
Labels: internal

#1312 chore: tests on read only fields.
  plugins/@grouparoo/sendgrid/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/sendgrid/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/sendgrid/__tests__/fixtures/export-profile.js
Labels: internal

#1319 Prevent the application from starting if there are code-config errors
  core/__tests__/bin/validate.ts
  core/src/grouparoo.ts
  core/src/initializers/codeConfig.ts
Labels: enhancement

#1313 Complex Source + Properties generator
  core/__tests__/actions/teams.ts
  core/__tests__/bin/generate.ts
  core/src/bin/apply.ts
  core/src/bin/generate.ts
  core/src/classes/configTemplate.ts
  core/src/modules/configLoaders/index.ts
  plugins/@grouparoo/app-templates/public/templates/table-property/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-source/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/src/source/table/tableSpeculation.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/cli.js
  plugins/@grouparoo/bigquery/__tests__/integration/cli.ts
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/__tests__/integration/cli.ts
  plugins/@grouparoo/mysql/__tests__/utils/data.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/__tests__/integration/cli.ts
  plugins/@grouparoo/postgres/__tests__/utils/data.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/cli.js
  plugins/@grouparoo/snowflake/__tests__/integration/cli.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
Labels: blocked, enhancement

#1325 Subscriber Telemetry
  core/__tests__/actions/teamMembers.ts
  core/src/modules/grouparooSubscription.ts
  ui/ui-components/pages/team/initialize.tsx
  ui/ui-components/pages/teamMember/new.tsx
Labels: internal

#1332 Lerna v4
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1317 [Hubspot] Destination types mapping improvements
  plugins/@grouparoo/hubspot/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/hubspot/jest.config.js
  plugins/@grouparoo/hubspot/src/lib/export/destinationMappingOptions.ts
Labels: enhancement

#1339 Batch Generator Descriptions
  core/src/bin/generate.ts
  core/src/classes/configTemplate.ts
  core/src/templates/apiKey.ts
  core/src/templates/events.ts
  core/src/templates/group.ts
  core/src/templates/manual.ts
  core/src/templates/team.ts
  core/src/templates/teamMember.ts
  plugins/@grouparoo/app-templates/src/app/templates.ts
  plugins/@grouparoo/app-templates/src/destination/templates.ts
  plugins/@grouparoo/app-templates/src/source/query/templates.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
  plugins/@grouparoo/csv/src/lib/templates.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/templates.ts
  plugins/@grouparoo/mailchimp/src/lib/templates.ts
Labels: enhancement

#1340 Clarify that to hide setup steps you go to the settings page
  ui/ui-components/pages/setup.tsx
Labels: enhancement

#1341 Update Sendgrid icon with official & transparent icon
  plugins/@grouparoo/sendgrid/README.md
  plugins/@grouparoo/sendgrid/public/@grouparoo/sendgrid/sendgrid.png
Labels: enhancement

#1344 Show link to help page while logged out
  core/__tests__/actions/navigation.ts
  core/src/actions/navigation.ts
Labels: enhancement

#1352 Instruct Lerna to use exact versions
  .circleci/config.yml
  .github/workflows/update-branch.yml
  bin/publish
  package.json
  tools/package-fixer/fix
  tools/package-fixer/github_action
  tools/package-fixer/package-lock.json
  tools/package-fixer/package.json
Labels: bug, dependencies, internal

#1355 session:create should be within a transaction
  core/src/actions/session.ts
  ui/ui-components/utils/apiData.ts
Labels: bug

#1353 `grouparoo apply` command creates runs + run resilience via the `run:tick` task
  cli/src/utils/loadLocalCommands.ts
  core/__tests__/actions/destinations.ts
  core/__tests__/actions/profiles.ts
  core/__tests__/integration/happyPath.ts
  core/__tests__/integration/runs/internalRun.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/group/calculatedGroup.ts
  core/__tests__/models/group/group.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/run/isRunEnqueued.ts
  core/__tests__/models/run/run.ts
  core/__tests__/modules/internalRun.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/group/run.ts
  core/__tests__/tasks/group/updateCalculatedGroups.ts
  core/__tests__/tasks/run/internalRun.ts
  core/__tests__/tasks/run/tick.ts
  core/__tests__/tasks/schedule/run.ts
  core/__tests__/tasks/schedule/updateSchedules.ts
  core/src/bin/apply.ts
  core/src/bin/console.ts
  core/src/bin/destroy.ts
  core/src/bin/generate.ts
  core/src/bin/run.ts
  core/src/bin/start.ts
  core/src/bin/status.ts
  core/src/bin/sync.ts
  core/src/bin/validate.ts
  core/src/migrations/000058-runDestinationId.ts
  core/src/models/Run.ts
  core/src/modules/internalRun.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/runs.ts
  core/src/tasks/group/run.ts
  core/src/tasks/run/internalRun.ts
  core/src/tasks/run/tick.ts
  core/src/tasks/run/updateCounts.ts
  core/src/tasks/schedule/run.ts
  core/src/tasks/schedule/updateSchedules.ts
  plugins/@grouparoo/csv/__tests__/integration/csv.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/google-sheets-import.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-import.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
Labels: bug, enhancement

#1356 If a .env file is present, load it in all environments + Testing Updates
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  core/src/config/environment.ts
  core/src/config/logger.ts
  core/src/config/sequelize.ts
  core/src/modules/configLoaders/index.ts
  pnpm-lock.yaml
Labels: enhancement

#1357 When Group Runs are waiting on imports, they are 100% compete
  core/__tests__/models/run/run.ts
  core/src/modules/ops/runs.ts
Labels: enhancement

#1359 Recover stuck Imports - `imports:associateProfiles`
  core/__tests__/models/schedule.ts
  core/__tests__/tasks/import/associateProfiles.ts
  core/__tests__/tasks/schedule/run.ts
  core/src/modules/ops/schedule.ts
  core/src/tasks/import/associateProfiles.ts
  core/src/tasks/run/internalRun.ts
  core/src/tasks/schedule/run.ts
Labels: enhancement

#1362 import:associateProfile needs to be unique and return early if import already associated
  core/src/modules/ops/profile.ts
  core/src/tasks/import/associateProfile.ts
  core/src/tasks/import/associateProfiles.ts
Labels: bug

#1361 Replace Nivo charts with Victory charts
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-community/pages/events/overview.tsx
  ui/ui-components/components/runs/list.tsx
  ui/ui-components/components/visualizations/chartColors.ts
  ui/ui-components/components/visualizations/eventsTotals.tsx
  ui/ui-components/components/visualizations/grouparooChart.tsx
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/components/visualizations/rollingChart.tsx
  ui/ui-components/components/visualizations/runDurations.tsx
  ui/ui-components/package.json
  ui/ui-components/pages/dashboard.tsx
  ui/ui-components/pages/export/[id]/edit.tsx
  ui/ui-components/pages/import/[id]/edit.tsx
  ui/ui-components/pages/resque/overview.tsx
  ui/ui-components/pages/run/[id]/edit.tsx
  ui/ui-components/utils/ContainerWidthSizer.tsx
  ui/ui-enterprise/package.json
  ui/ui-enterprise/pages/events/overview.tsx
Labels: enhancement

#1363 Disable API caching so dashboard widgets update faster
  ui/ui-components/components/visualizations/homepageWidgets.tsx
Labels: enhancement

#1365 Update readme links + remove other methods of running
  core/README.md
Labels: documentation

#1364 `grouparoo status` can output JSON
  core/__tests__/bin/statuts.ts
  core/src/bin/status.ts
Labels: enhancement

#1366 `APIData.formatDate` utility to enforce same date format in API responses
  core/src/models/ApiKey.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/DestinationGroupMembership.ts
  core/src/models/Event.ts
  core/src/models/Export.ts
  core/src/models/File.ts
  core/src/models/Group.ts
  core/src/models/GroupMember.ts
  core/src/models/GroupRule.ts
  core/src/models/Import.ts
  core/src/models/Log.ts
  core/src/models/Mapping.ts
  core/src/models/Notification.ts
  core/src/models/Option.ts
  core/src/models/Profile.ts
  core/src/models/ProfileProperty.ts
  core/src/models/Property.ts
  core/src/models/PropertyFilter.ts
  core/src/models/Run.ts
  core/src/models/Schedule.ts
  core/src/models/Setting.ts
  core/src/models/SetupStep.ts
  core/src/models/Source.ts
  core/src/models/Team.ts
  core/src/models/TeamMember.ts
  core/src/modules/apiData.ts
Labels: bug

#1367 Display a loading animation if page transitions are slow
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/components/pageTransition.tsx
  ui/ui-components/package.json
  ui/ui-components/pages/_app.tsx
  ui/ui-components/scss/grouparoo.scss
  ui/ui-components/scss/nprogress.scss
  ui/ui-enterprise/package.json
Labels: enhancement

#1354 Customer.io destination
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/customerio/.npmignore
  plugins/@grouparoo/customerio/LICENSE.txt
  plugins/@grouparoo/customerio/README.md
  plugins/@grouparoo/customerio/__tests__/.env.example
  plugins/@grouparoo/customerio/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/customerio/__tests__/export/export-profile.ts
  plugins/@grouparoo/customerio/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/customerio/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/customerio/__tests__/utils/shared.ts
  plugins/@grouparoo/customerio/jest.config.js
  plugins/@grouparoo/customerio/jest.setup.js
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/customerio/public/@grouparoo/customerio/customerio.png
  plugins/@grouparoo/customerio/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/customerio/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/customerio/src/initializers/plugin.ts
  plugins/@grouparoo/customerio/src/lib/connect.ts
  plugins/@grouparoo/customerio/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/customerio/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/customerio/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/customerio/src/lib/export/exportProfile.ts
  plugins/@grouparoo/customerio/src/lib/test.ts
  plugins/@grouparoo/customerio/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#1368 Show Identifying Property Name on Profile Pages
  ui/ui-components/components/profile/getProfileDisplayName.ts
  ui/ui-components/components/tabs/profile.tsx
  ui/ui-components/pages/profile/[id]/edit.tsx
  ui/ui-components/pages/profile/[id]/events.tsx
  ui/ui-components/pages/profile/[id]/exports.tsx
  ui/ui-components/pages/profile/[id]/imports.tsx
  ui/ui-components/pages/profile/[id]/logs.tsx
Labels: enhancement

#1358 [hubspot] add new tests and for hubspot.
  plugins/@grouparoo/hubspot/__tests__/export/export-profile.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/hubspot-export.js
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/src/lib/client.ts
  plugins/@grouparoo/hubspot/src/lib/connect.ts
  plugins/@grouparoo/hubspot/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export/exportProfile.ts
  plugins/@grouparoo/hubspot/src/lib/export/listMethods.ts
  plugins/@grouparoo/hubspot/src/lib/test.ts
Labels: enhancement

#1369 Sessions are stored in the database + Better Auth errors
  core/__tests__/actions/apiKey.ts
  core/__tests__/actions/groups.ts
  core/__tests__/actions/profiles.ts
  core/__tests__/actions/sessions.ts
  core/__tests__/actions/teams.ts
  core/src/actions/session.ts
  core/src/initializers/session.ts
  core/src/migrations/000059-createSessions.ts
  core/src/models/Session.ts
  core/src/modules/middleware/authentication.ts
  core/src/tasks/sweeper.ts
  ui/ui-components/client/client.ts
  ui/ui-components/components/visualizations/grouparooChart.tsx
Labels: enhancement

#1370 Separate Arguments from Options in `grouparoo generate --describe`
  core/src/bin/generate.ts
Labels: enhancement

#1371 Throw better error if plugin not found
  core/__tests__/fixtures/codeConfig/error-not-installed/config.js
  core/__tests__/models/app/app.ts
  core/__tests__/models/source.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/models/App.ts
  core/src/models/Source.ts
  core/src/modules/optionHelper.ts
Labels: enhancement

#1372 Remove reEnqueueIfGuidParams
  core/__tests__/modules/taskUtils.ts
  core/src/classes/tasks/clsTask.ts
  core/src/modules/taskUtils.ts
  core/src/tasks/event/associateProfile.ts
  core/src/tasks/import/associateProfile.ts
Labels: internal
