Repository grouparoo/grouparoo, pull requests merged in 2021-01, with the labels that each got.

#1140 Run NPM though CLI subshell
  cli/package.json
  cli/src/lib/initialize.ts
  cli/src/utils/npm.ts
  cli/src/utils/spawnPromise.ts
  pnpm-lock.yaml
Labels: bug, dependencies

#1142 @grouparoo/core is not a plugin
  core/src/utils/pluginDetails.js
Labels: bug, dependencies

#1143 Property Lifecycle Fixes
  core/__tests__/models/profile.ts
  core/__tests__/models/source.ts
  core/src/modules/ops/event.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/source.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
Labels: bug, enhancement

#1155 `grouparoo init` creates config directory
  cli/src/lib/initialize.ts
Labels: enhancement

#1157 `grouparoo run` disables web servers without modifying env
  core/src/bin/run.ts
  core/src/modules/cli.ts
Labels: bug

#1158 `grouparoo destroy` command
  core/src/bin/destroy.ts
  core/src/modules/cli.ts
Labels: enhancement

#1159 Task updates after CLSTask introduction
  core/__tests__/tasks/export/enqueue.ts
  core/src/tasks/export/enqueue.ts
  core/src/tasks/import/associateProfile.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: bug

#1145 Intercom Destination
  .circleci/config.yml
  apps/staging-public/package.json
  plugins/@grouparoo/hubspot/src/lib/export/listMethods.ts
  plugins/@grouparoo/intercom/.npmignore
  plugins/@grouparoo/intercom/LICENSE.txt
  plugins/@grouparoo/intercom/README.md
  plugins/@grouparoo/intercom/__tests__/.env.example
  plugins/@grouparoo/intercom/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-archive.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-delete.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-enrich.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-lead.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-lifecycle.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-skip.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-user.js
  plugins/@grouparoo/intercom/__tests__/fixtures/lead-quirks.js
  plugins/@grouparoo/intercom/__tests__/integration/destination-mapping-options.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-archive.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-delete.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-enrich.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-lead.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-lifecycle.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-skip.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-user.ts
  plugins/@grouparoo/intercom/__tests__/integration/lead-quirks.ts
  plugins/@grouparoo/intercom/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/intercom/__tests__/utils/shared.ts
  plugins/@grouparoo/intercom/jest.config.js
  plugins/@grouparoo/intercom/jest.setup.js
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/intercom/public/@grouparoo/intercom/intercom.png
  plugins/@grouparoo/intercom/src/initializers/plugin.ts
  plugins/@grouparoo/intercom/src/lib/client/contact.ts
  plugins/@grouparoo/intercom/src/lib/client/data-attribute.ts
  plugins/@grouparoo/intercom/src/lib/client/intercom.md
  plugins/@grouparoo/intercom/src/lib/client/tag.ts
  plugins/@grouparoo/intercom/src/lib/connect.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/destinationMappingOptions.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/exportArrayProperties.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/exportProfile.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/listMethods.ts
  plugins/@grouparoo/intercom/src/lib/test.ts
  plugins/@grouparoo/intercom/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#1179 Move event#assocaite retry logic to Task
  core/src/modules/ops/event.ts
  core/src/tasks/event/associateProfile.ts
Labels: bug

#1181 Simplify retry logic of event:associateProfile Task
  core/src/tasks/event/associateProfile.ts
Labels: internal

#1160 `grouparoo generate` command
  cli/src/grouparoo.ts
  cli/src/utils/loadLocalCommands.ts
  core/__tests__/bin/generate.ts
  core/__tests__/bin/validate.ts
  core/__tests__/modules/configTemplate.ts
  core/package.json
  core/public/.gitkeep
  core/public/templates/groups/calculated/{{{name}}}.js.template
  core/public/templates/groups/manual/{{{name}}}.js.template
  core/src/actions/teams.ts
  core/src/bin/apply.ts
  core/src/bin/console.ts
  core/src/bin/destroy.ts
  core/src/bin/generate.ts
  core/src/bin/run.ts
  core/src/bin/start.ts
  core/src/bin/status.ts
  core/src/bin/validate.ts
  core/src/classes/configTemplate.ts
  core/src/initializers/codeConfig.ts
  core/src/modules/cli.ts
  core/src/modules/configTemplateUtils.ts
  core/src/modules/grouparooSubscription.ts
  core/src/modules/mustacheUtils.ts
  core/src/modules/plugin.ts
  core/src/templates/group.ts
  pnpm-lock.yaml
Labels: enhancement

#1182 Store files locally within project root
  core/__tests__/actions/files.ts
  core/src/classes/fileTransportLocal.ts
  core/src/config/sequelize.ts
  core/src/initializers/files.ts
  core/src/utils/pluginDetails.js
  ui/client/client.ts
Labels: enhancement

#1185 Schedule UI Fixes
  ui/pages/source/[guid]/overview.tsx
  ui/pages/source/[guid]/schedule.tsx
Labels: bug

#1186 Do not trhow an error when the schedule:run task cannot find the schedule
  core/__tests__/tasks/schedule/run.ts
  core/src/modules/cls.ts
  core/src/tasks/schedule/run.ts
Labels: bug

#1188 `npm run watch` command to help with tsc
  cli/package.json
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/zendesk/package.json
Labels: internal

#1183 Task Resilience
  core/__tests__/integration/happyPath.ts
  core/__tests__/models/profile.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/profile/completeImport.ts
  core/__tests__/tasks/profile/export.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/event/associateProfile.ts
  core/src/tasks/profile/completeImport.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
Labels: bug

#1196 Upgrade Actionhero, Sequelize and Sequelize Typescript to latest versions
  cli/package.json
  cli/src/lib/initialize.ts
  cli/src/utils/loadLocalCommands.ts
  core/package.json
  core/src/actions/cluster.ts
  core/src/actions/properties.ts
  core/src/actions/totals.ts
  core/src/classes/loggedModel.ts
  core/src/models/EventData.ts
  core/src/models/Export.ts
  core/src/models/Group.ts
  core/src/models/GroupMember.ts
  core/src/models/GroupRule.ts
  core/src/models/Import.ts
  core/src/models/Log.ts
  core/src/models/PropertyFilter.ts
  core/src/models/Run.ts
  core/src/modules/ops/profile.ts
  core/src/modules/telemetryReporters.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: documentation

#1197 Node SASS v5.0.0
  ui/package.json
Labels: dependencies

#1198 Update dependencies
  cli/package.json
  core/__tests__/fixtures/actions/plugins.ts
  core/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1199 Allow code-config Destinations without a tracked group
  core/src/modules/configLoaders/destination.ts
Labels: bug

#1201 Fetch up to 1000 mail chimp lists
  plugins/@grouparoo/mailchimp/__tests__/fixtures/mailchimp-export-id.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/mailchimp-export.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/mailchimp-import.js
  plugins/@grouparoo/mailchimp/src/lib/shared/connectionOptions.ts
  plugins/@grouparoo/mailchimp/src/lib/test.ts
Labels: bug

#1206 After change Destination Options, the tracked Group is re-run
  core/__tests__/models/destination/destination.ts
  core/src/models/Destination.ts
Labels: enhancement

#1207 Grouparoo Run Schedule options
  core/__tests__/tasks/schedule/updateSchedules.ts
  core/src/bin/run.ts
  core/src/modules/cli.ts
  core/src/tasks/run/recurringInternalRun.ts
  core/src/tasks/schedule/updateSchedules.ts
Labels: enhancement

#1203 Update helper text for cli generate command
  core/src/bin/generate.ts
  plugins/@grouparoo/app-templates/public/templates/query-property/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/query-schedule/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/query-source/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-property/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-schedule/{{{id}}}.js.template
  plugins/@grouparoo/app-templates/public/templates/table-source/{{{id}}}.js.template
  plugins/@grouparoo/bigquery/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/csv/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/facebook/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/facebook/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/google-sheets/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/intercom/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/intercom/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/destination/email/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/destination/id/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/property/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/schedule/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/public/templates/source/{{{id}}}.js.template
  plugins/@grouparoo/mailchimp/src/lib/templates.ts
  plugins/@grouparoo/marketo/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/marketo/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/mysql/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/mysql/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/postgres/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/postgres/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/redshift/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/redshift/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/salesforce/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/salesforce/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/snowflake/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/zendesk/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/zendesk/public/templates/destination/{{{id}}}.js.template
Labels: enhancement

#1215 Ensure that posgres SSL option is always treated as boolean
  plugins/@grouparoo/postgres/src/lib/connect.ts
Labels: bug

#1205 Intercom updates
  core/src/modules/cache.ts
  plugins/@grouparoo/intercom/__tests__/.env.example
  plugins/@grouparoo/intercom/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-archive.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-delete.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-enrich.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-lead.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-lifecycle.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-skip.js
  plugins/@grouparoo/intercom/__tests__/fixtures/export-profile-user.js
  plugins/@grouparoo/intercom/__tests__/fixtures/lead-quirks.js
  plugins/@grouparoo/intercom/__tests__/integration/destination-mapping-options.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-archive.ts
  plugins/@grouparoo/intercom/__tests__/integration/export-profile-lead.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/destinationMappingOptions.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/intercom/src/lib/export-contacts/exportProfile.ts
Labels: internal

#1222 Externally validate config by default
  core/__tests__/modules/cls.ts
  core/src/bin/apply.ts
  core/src/bin/validate.ts
  core/src/modules/cls.ts
Labels: enhancement

#1225 Use email_address instead of email for mailchimp mapping
  plugins/@grouparoo/mailchimp/public/templates/destination/email/{{{id}}}.js.template
Labels: bug

#1226 Simplify CLI command flag parsing
  cli/src/utils/loadLocalCommands.ts
  core/__tests__/bin/generate.ts
  core/__tests__/bin/run.ts
  core/src/bin/apply.ts
  core/src/bin/generate.ts
  core/src/bin/run.ts
  core/src/bin/validate.ts
  core/src/modules/cli.ts
  pnpm-lock.yaml
Labels: internal

#1229 `grouparoo sync` - import and export one profile via the command line
  core/__tests__/bin/__snapshots__/sync.ts.snap
  core/__tests__/bin/sync.ts
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/src/bin/generate.ts
  core/src/bin/sync.ts
  core/src/models/Profile.ts
  core/src/modules/cli.ts
  core/src/modules/ops/profile.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement

#1223 Use mapping values as prereq for determining code config order
  core/__tests__/classes/codeConfig.ts
  core/src/classes/codeConfig.ts
Labels: bug

#1224 Better description for table v query sources on CLI
  plugins/@grouparoo/app-templates/src/source/query/templates.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
Labels: enhancement

#1230 `grouparoo run` can skip exports
  core/__tests__/tasks/profile/completeImport.ts
  core/src/bin/run.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profile/checkReady.ts
  core/src/tasks/profile/completeImport.ts
  pnpm-lock.yaml
Labels: enhancement

#1233 Right after `init`, instruct folks to run `grouparoo` again to see the new commands
  cli/src/lib/initialize.ts
Labels: enhancement

#1232 Client test updates
  apps/staging-public/__tests__/test.js
  core/__tests__/modules/codeConfig/snapshotTest.ts
  core/src/utils/pluginDetails.js
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/next.config.js
Labels: bug

#1235 Upgrade to node-resque v8.2.1
  core/package.json
  core/src/actions/resque.ts
  pnpm-lock.yaml
Labels: dependencies

#1236 Webpack v5.18.0
  clients/@grouparoo/web/package.json
  clients/@grouparoo/web/webpack.config.js
Labels: dependencies

#1237 facebook-nodejs-business-sdk v9.0.1
  plugins/@grouparoo/facebook/package.json
  pnpm-lock.yaml
  tools/license-checker/check
Labels: dependencies

#1239 Fix issue with generate's ID notice
  core/__tests__/bin/generate.ts
  core/src/bin/generate.ts
Labels: bug

#1241 Script to write group property ops to JSON file
  .gitignore
  core/__tests__/bin/build_static_refs.ts
  core/__tests__/modules/ruleOpsDictionary.ts
  core/bin/build_static_refs
  core/public/templates/groups/calculated/{{{id}}}.js.template
  core/src/actions/groups.ts
  core/src/models/Group.ts
  core/src/modules/ruleOpsDictionary.ts
Labels: enhancement

#1243 Split the core tests into a chunk for each test dir
  .circleci/config.yml
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/core/workflow.yml.template
  tools/merger/src/ci_generate.js
Labels: internal
