Repository grouparoo/grouparoo, pull requests merged in 2021-07, with the labels that each got.

#2019 Publish with concurrency of 1
  bin/publish
Labels: internal

#2006 Add "Create Sample Profiles" to setup steps in config
  core/__tests__/models/setupStep.ts
  core/src/modules/ops/setupSteps.ts
Labels: enhancement

#2033 Use getConfigId() when generating sample profile config files
  core/__tests__/bin/__snapshots__/sync.ts.snap
  core/__tests__/models/profile/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/modules/configWriter.ts
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/src/actions/properties.ts
  core/src/models/Profile.ts
  core/src/modules/ops/profile.ts
Labels: bug

#2017 Add mapping from Grouparoo fields to Iterable nested objects.
  plugins/@grouparoo/iterable/__tests__/export/export-profile.ts
  plugins/@grouparoo/iterable/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/iterable/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/iterable/__tests__/utils/shared.ts
  plugins/@grouparoo/iterable/jest.config.js
  plugins/@grouparoo/iterable/src/lib/export/exportProfile.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement, plugin

#2034 fix: set scope on model options
  core/__tests__/models/app/app.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/schedule.ts
  core/__tests__/models/source.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Source.ts
Labels: bug

#2018 "Import and Export" button will Export Profile to Destinations that it should be removed from
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/profile/sync.ts
  core/src/actions/profiles.ts
  core/src/models/Profile.ts
  core/src/modules/ops/profile.ts
Labels: enhancement

#2042 Upgrade `@sentry/*` packages to v6.8.0
  plugins/@grouparoo/sentry/package.json
Labels: dependencies

#2040 remove warning from source and property pages
  ui/ui-components/pages/property/[id]/edit.tsx
  ui/ui-components/pages/source/[id]/mapping.tsx
Labels: enhancement

#1997 Destroy before ending run
  core/__tests__/modules/status.ts
  core/__tests__/tasks/source/destroy.ts
  core/src/bin/status.ts
  core/src/modules/status.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/source/destroy.ts
  core/src/tasks/system/status/status.ts
Labels: bug

#2010 batch properties SUM and AVG return 0 for null
  plugins/@grouparoo/app-templates/src/source/table/profileProperties.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-properties.js
  plugins/@grouparoo/bigquery/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mongo/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-properties.js
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/import-properties.ts
Labels: bug

#2041 resilient import completion and exports creation
  core/__tests__/tasks/profile/checkReady.ts
  core/__tests__/tasks/profile/completeImport.ts
  core/__tests__/tasks/profile/enqueueExports.ts
  core/__tests__/tasks/profile/export.ts
  core/src/migrations/000074-mergeCompleteImportTask.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profile/checkReady.ts
  core/src/tasks/profile/completeImport.ts
  core/src/tasks/profile/enqueueExports.ts
  plugins/@grouparoo/spec-helper/src/lib/workflows/import.ts
Labels: enhancement

#2045 Add mobile padding on setupStep cards
  ui/ui-components/components/setupSteps/setupStepCard.tsx
Labels: bug

#2046 Adjust RPC stop priority & wait
  core/src/initializers/plugins.ts
  core/src/initializers/rpc.ts
  core/src/models/App.ts
Labels: internal

#2050 Do not render homepage widgets if stats are not loaded
  ui/ui-components/components/visualizations/homepageWidgets.tsx
Labels: bug

#1975 Add Eloqua destination plugin integration
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  core/src/classes/plugin.ts
  core/src/modules/ops/destination.ts
  plugins/@grouparoo/eloqua/.npmignore
  plugins/@grouparoo/eloqua/LICENSE.txt
  plugins/@grouparoo/eloqua/README.md
  plugins/@grouparoo/eloqua/__tests__/.env.example
  plugins/@grouparoo/eloqua/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/eloqua/__tests__/export/export-profiles.ts
  plugins/@grouparoo/eloqua/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/eloqua/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/eloqua/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/eloqua/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/eloqua/__tests__/utils/shared.ts
  plugins/@grouparoo/eloqua/jest.config.js
  plugins/@grouparoo/eloqua/jest.setup.js
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/eloqua/public/@grouparoo/eloqua/eloqua.png
  plugins/@grouparoo/eloqua/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/eloqua/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/eloqua/src/initializers/plugin.ts
  plugins/@grouparoo/eloqua/src/lib/client/bulk.ts
  plugins/@grouparoo/eloqua/src/lib/client/client.ts
  plugins/@grouparoo/eloqua/src/lib/client/contact.ts
  plugins/@grouparoo/eloqua/src/lib/client/contactList.ts
  plugins/@grouparoo/eloqua/src/lib/client/field.ts
  plugins/@grouparoo/eloqua/src/lib/connect.ts
  plugins/@grouparoo/eloqua/src/lib/export/cachedMethods.ts
  plugins/@grouparoo/eloqua/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/eloqua/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/eloqua/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/eloqua/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/eloqua/src/lib/export/processExportedProfiles.ts
  plugins/@grouparoo/eloqua/src/lib/test.ts
  plugins/@grouparoo/eloqua/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#2051 Remove manual app
  core/__tests__/actions/apps.ts
  core/__tests__/fixtures/codeConfig/error-changed-type-duplicate/config.js
  core/__tests__/models/property/property.ts
  core/__tests__/models/schedule.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/attribution.md
  core/public/templates/manual/app/{{{id}}}.js.template
  core/public/templates/manual/property/{{{id}}}.js.template
  core/public/templates/manual/source/{{{id}}}.js.template
  core/src/initializers/plugins.ts
  core/src/migrations/000076-removeManualApp.ts
  core/src/modules/ops/property.ts
  core/src/templates/manual.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/spec-helper/src/lib/cliSpecHelper.ts
  ui/ui-components/pages/profile/[id]/edit.tsx
Labels: internal

#2052 Notify Omnibus via webhook on new version + use shared secrets in actions
  .github/workflows/publish.yml
  .github/workflows/update-lockfile.yml
Labels: internal

#2044 Hide setup bar if complete
  core/__tests__/actions/setupSteps.ts
  core/src/actions/setupSteps.ts
  core/src/initializers/settings.ts
  ui/ui-components/components/icons.ts
  ui/ui-components/components/navigation/setupStepsNavProgressBar.tsx
  ui/ui-components/components/session/signIn.tsx
  ui/ui-components/pages/setup.tsx
  ui/ui-config/pages/session/sign-in.tsx
Labels: enhancement

#2053 Prevent empty string problems when setting Destination data
  ui/ui-components/pages/destination/[id]/data.tsx
Labels: bug

#2047 UI -- Consistent CTAs for empty objects
  ui/ui-components/pages/destination/new/index.tsx
  ui/ui-components/pages/profile/[id]/edit.tsx
  ui/ui-components/pages/source/new/index.tsx
  ui/ui-config/pages/profile/new.tsx
Labels: bug

#2016 add ui-config to `grouparoo init`
  cli/templates/package.json
Labels: enhancement

#2055 Support minor and major releases in Github action
  .github/workflows/publish.yml
  bin/publish
Labels: internal

#2058 Update Actionhero, Node-resque, and related dependencies
  cli/package.json
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2056 Async React Component testing
  ui/ui-components/__tests__/components/setupStepsNavProgressBar.tsx
  ui/ui-components/client/client.ts
  ui/ui-components/components/navigation/setupStepsNavProgressBar.tsx
  ui/ui-components/hooks/useApi.ts
Labels: internal

#2057 Slight sleep when using SQLite if transaction is busy
  core/src/initializers/plugins.ts
  core/src/modules/cls.ts
  core/src/modules/locks.ts
  core/src/tasks/run/tick.ts
  plugins/@grouparoo/demo/src/util/shared.ts
Labels: bug

#2059 Heroku can skip caching the .next cache files for smaller slugs
  package.json
Labels: internal

#2060 Keep only 7 days of logs by default
  core/__tests__/tasks/system/sweeper.ts
  core/src/initializers/settings.ts
Labels: enhancement

#2063 Fixup migration after polymorphic filters update
  core/src/migrations/000076-removeManualApp.ts
Labels: bug

#2065 Support locked cluster-name Setting when initializing first Team
  core/__tests__/actions/settings.ts
  core/__tests__/actions/teams.ts
  core/src/actions/settings.ts
  core/src/actions/teams.ts
  core/src/config/routes.ts
  ui/ui-components/pages/team/initialize.tsx
  ui/ui-components/utils/apiData.ts
Labels: bug

#2064 fix typo on ui-components/pages/destinations/new
  ui/ui-components/pages/destination/new/index.tsx
Labels: bug

#2066 Continue to use ENV string when re-setting option with ObfuscatedPasswordString
  core/__tests__/models/option.ts
  core/src/modules/optionHelper.ts
Labels: bug

#2049 clear profile properties when they no longer exist in the source
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/source.ts
  core/__tests__/tasks/profileProperty/enqueue.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/profileProperty/importProfileProperty.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/profileProperty.ts
  core/src/modules/ops/source.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement

#2069 Remove `profile:completeImport` and `schedule:updateSchedules` tasks
  core/src/tasks/profile/completeImport.ts
  core/src/tasks/schedule/updateSchedules.ts
Labels: internal

#2068 clear `directlyMapped` properties when profile has been removed from the source
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/exportProfiles.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/modules/plugin.ts
  core/__tests__/tasks/import/associateProfile.ts
  core/__tests__/tasks/profile/checkReady.ts
  core/__tests__/tasks/profile/export.ts
  core/__tests__/tasks/profileProperty/enqueue.ts
  core/src/models/Profile.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/import/associateProfile.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/profile.ts
Labels: enhancement

#2071 Rename `profile.properties()` to `profile.getProperties()`
  core/__tests__/actions/properties.ts
  core/__tests__/integration/runs/internalRun.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/profile/sync.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/groupExport.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/profileProperty/sweep.ts
  core/src/models/Profile.ts
  core/src/modules/groupExport.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/source.ts
  core/src/modules/plugin.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperties.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperty.ts
  plugins/@grouparoo/csv/__tests__/integration/csv-file.ts
  plugins/@grouparoo/csv/__tests__/integration/csv-remote.ts
  plugins/@grouparoo/csv/src/lib/file-import/profileProperties.ts
  plugins/@grouparoo/csv/src/lib/remote-import/profileProperties.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/google-sheets-import.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-import.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-query-import.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-query-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-query-import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-table-import.ts
Labels: internal

#2074 Github Codespaces
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
Labels: internal

#2073 Sort Sources when importing a Profile all at once
  core/__tests__/actions/sources.ts
  core/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/profile/snapshot-testing.ts
  core/__tests__/models/source/sortByDependencies.ts
  core/__tests__/models/source/source.ts
  core/__tests__/modules/groupExport.ts
  core/__tests__/tasks/group/destroy.ts
  core/__tests__/tasks/group/run.ts
  core/__tests__/utils/prepareSharedGroupTest.ts
  core/src/actions/apiKeys.ts
  core/src/actions/destinations.ts
  core/src/actions/files.ts
  core/src/actions/groups.ts
  core/src/actions/logs.ts
  core/src/actions/runs.ts
  core/src/actions/schedules.ts
  core/src/actions/settings.ts
  core/src/actions/sources.ts
  core/src/actions/teamMembers.ts
  core/src/actions/teams.ts
  core/src/models/ApiKey.ts
  core/src/models/Team.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/exportProcessor.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/profileProperty.ts
  core/src/modules/ops/source.ts
  core/src/modules/plugins.ts
  core/src/tasks/group/updateCalculatedGroups.ts
  core/src/tasks/profile/export.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: bug

#2079 Do not load a plugin if it can't be found
  core/src/utils/pluginDetails.js
Labels: bug

#2080 Remove unused logic for internal Run profile association
  core/src/modules/ops/profile.ts
Labels: internal

#2054 Import Multiple Profile Properties for Multiple Exact Properties at once
  core/__tests__/integration/happyPath.ts
  core/__tests__/models/profileProperty/processPendingProfileProperties.ts
  core/__tests__/models/profileProperty/profileProperty.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/profileProperty/enqueue.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/src/classes/plugin.ts
  core/src/models/Source.ts
  core/src/modules/filterHelper.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/profileProperty.ts
  core/src/modules/ops/source.ts
  core/src/tasks/import/associateProfiles.ts
  core/src/tasks/profileProperty/enqueue.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  plugins/@grouparoo/app-templates/src/source/query/meta.ts
  plugins/@grouparoo/app-templates/src/source/query/options.ts
  plugins/@grouparoo/app-templates/src/source/table/getExamples.ts
  plugins/@grouparoo/app-templates/src/source/table/getFilterOperation.ts
  plugins/@grouparoo/app-templates/src/source/table/meta.ts
  plugins/@grouparoo/app-templates/src/source/table/options.ts
  plugins/@grouparoo/app-templates/src/source/table/pluginMethods.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperties.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profiles.ts
  plugins/@grouparoo/app-templates/src/source/table/propertyOptions.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
  plugins/@grouparoo/app-templates/src/source/table/uniquePropertyBootstrapOptions.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-properties.js
  plugins/@grouparoo/bigquery/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/bigquery/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/csv/__tests__/file-import/profileProperties.ts
  plugins/@grouparoo/csv/__tests__/remote-import/profileProperties.ts
  plugins/@grouparoo/csv/src/initializers/plugin.ts
  plugins/@grouparoo/csv/src/lib/file-import/profileProperties.ts
  plugins/@grouparoo/csv/src/lib/file-import/profileProperty.ts
  plugins/@grouparoo/csv/src/lib/file-import/propertyOptions.ts
  plugins/@grouparoo/csv/src/lib/remote-import/profileProperties.ts
  plugins/@grouparoo/csv/src/lib/remote-import/profileProperty.ts
  plugins/@grouparoo/csv/src/lib/remote-import/propertyOptions.ts
  plugins/@grouparoo/csv/src/lib/shared/parseProfileProperties.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/mongo/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mysql/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-properties.js
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValues.ts
Labels: blocked, enhancement

#2082 Mixpanel destination plugin
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/mixpanel/.npmignore
  plugins/@grouparoo/mixpanel/LICENSE.txt
  plugins/@grouparoo/mixpanel/README.md
  plugins/@grouparoo/mixpanel/__tests__/.env.example
  plugins/@grouparoo/mixpanel/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/mixpanel/__tests__/export/export-profile.ts
  plugins/@grouparoo/mixpanel/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mixpanel/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/mixpanel/__tests__/utils/shared.ts
  plugins/@grouparoo/mixpanel/jest.config.js
  plugins/@grouparoo/mixpanel/jest.setup.js
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mixpanel/public/@grouparoo/mixpanel/mixpanel.svg
  plugins/@grouparoo/mixpanel/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/mixpanel/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/mixpanel/src/initializers/plugin.ts
  plugins/@grouparoo/mixpanel/src/lib/client/ingestion.ts
  plugins/@grouparoo/mixpanel/src/lib/client/mixpanel.ts
  plugins/@grouparoo/mixpanel/src/lib/client/profile.ts
  plugins/@grouparoo/mixpanel/src/lib/client/query.ts
  plugins/@grouparoo/mixpanel/src/lib/connect.ts
  plugins/@grouparoo/mixpanel/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/mixpanel/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/mixpanel/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/mixpanel/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mixpanel/src/lib/test.ts
  plugins/@grouparoo/mixpanel/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#2086 Simpler Source Property Create Page
  core/__tests__/actions/sources.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/source/source.ts
  core/__tests__/modules/configWriter.ts
  core/__tests__/modules/tableSpeculation.ts
  core/src/actions/properties.ts
  core/src/actions/sources.ts
  core/src/config/routes.ts
  core/src/index.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/source.ts
  core/src/modules/tableSpeculation.ts
  plugins/@grouparoo/app-templates/src/source/table/propertyOptions.ts
  plugins/@grouparoo/app-templates/src/source/table/templates.ts
  plugins/@grouparoo/csv/src/lib/file-import/propertyOptions.ts
  plugins/@grouparoo/csv/src/lib/remote-import/propertyOptions.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/propertyOptions.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/property.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-components/components/tabs/source.tsx
  ui/ui-components/pages/property/[id]/edit.tsx
  ui/ui-components/pages/source/[id]/overview.tsx
  ui/ui-components/pages/source/[id]/properties.tsx
  ui/ui-components/pages/source/[id]/schedule.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-components/utils/generateId.ts
  ui/ui-config/pages/source/[id]/properties.tsx
  ui/ui-enterprise/pages/source/[id]/properties.tsx
Labels: enhancement

#2088 Add schema to Sequelize config object.
  core/src/config/sequelize.ts
Labels: enhancement, internal
