Repository grouparoo/grouparoo, pull requests merged in 2021-05, with the labels that each got.

#1728 Rescue stuck Groups who lost their runs
  core/__tests__/tasks/group/updateCalculatedGroups.ts
  core/src/tasks/group/updateCalculatedGroups.ts
Labels: enhancement

#1729 Support SSL redis (redis v6)
  core/src/config/redis.ts
Labels: enhancement

#1726 Set all options when creating bootstrappedProperty
  core/__tests__/models/source.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/ops/source.ts
Labels: bug

#1734 Do not process Run if group is deleted
  core/src/tasks/group/run.ts
Labels: bug

#1735 Add more uniqueness to mock APIKey names
  plugins/@grouparoo/spec-helper/src/lib/factories/apiKey.ts
Labels: internal

#1736 Fix NaN check no dashboard
  ui/ui-components/components/visualizations/homepageWidgets.tsx
Labels: bug

#1723 Add sync modes to Iterable plugin.
  plugins/@grouparoo/iterable/__tests__/export/export-profile.ts
  plugins/@grouparoo/iterable/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/iterable/jest.config.js
  plugins/@grouparoo/iterable/src/initializers/plugin.ts
  plugins/@grouparoo/iterable/src/lib/export/exportProfile.ts
  plugins/@grouparoo/iterable/src/migrations/000001-plugin-iterable-syncMode.ts
Labels: enhancement, plugin

#1739 Update Dependencies
  clients/@grouparoo/web/package.json
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1740 Re-registering a setting with the same default value won't be an update
  core/__tests__/models/setting.ts
  core/src/modules/plugin.ts
Labels: bug

#1730 Telemetry errors should log and not throw
  core/__tests__/modules/telemetry.ts
  core/src/modules/telemetry.ts
  core/src/tasks/system/telemetry/adHoc.ts
  core/src/tasks/system/telemetry/telemetry.ts
Labels: enhancement

#1742 Protect SERVER_TOKEN in UI stack trace
  core/__tests__/actions/navigation.ts
  core/src/actions/navigation.ts
  ui/ui-components/components/alerts/hydrationError.tsx
  ui/ui-components/pages/_app.tsx
Labels: enhancement

#1744 Telemetry errors log to debug level
  core/src/modules/telemetry.ts
Labels: enhancement

#1746 Remove waitForReady on `grouparoo run`
  core/__tests__/bin/run.ts
  core/src/bin/run.ts
Labels: bug

#1747 Fix `updateCalculatedGroups` when there was no `calculatedAt`
  core/__tests__/tasks/group/updateCalculatedGroups.ts
  core/src/tasks/group/updateCalculatedGroups.ts
Labels: bug

#1751 `run` and `start` CLI commands await for process boot
  core/src/bin/run.ts
  core/src/bin/start.ts
  core/src/grouparoo.ts
Labels: enhancement

#1748 Update Next.js and React to latest versions
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1727 Remove `[ run ] starting...` log messages
  core/src/models/Schedule.ts
  core/src/modules/internalRun.ts
  core/src/modules/ops/group.ts
  core/src/tasks/group/destroy.ts
  core/src/tasks/schedule/updateSchedules.ts
Labels: enhancement

#1752 fix: set options before updating property when loading from codeConfig
  core/__tests__/fixtures/codeConfig/changes/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/modules/configLoaders/property.ts
Labels: bug

#1757 Sentry transaction Tag Isolation
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
Labels: enhancement

#1758 Try a longer sleep in UI-Enterprise test
  ui/ui-enterprise/__tests__/integration/happyPath.ts
Labels: internal

#1759 Do not try to sanitize missing headers
  ui/ui-components/pages/_app.tsx
Labels: bug

#1750 Add sync modes to OneSignal destination plugin.
  plugins/@grouparoo/onesignal/__tests__/export/export-profile.ts
  plugins/@grouparoo/onesignal/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/onesignal/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/onesignal/src/initializers/plugin.ts
  plugins/@grouparoo/onesignal/src/lib/export/exportProfile.ts
  plugins/@grouparoo/onesignal/src/migrations/000001-plugin-onesignal-syncMode.ts
Labels: enhancement, plugin

#1743 Make name field important for Zendesk one and cover it on tests.
  plugins/@grouparoo/zendesk/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/zendesk/src/lib/export/destinationMappingOptions.ts
Labels: bug, plugin

#1754 Add error message on `grouparoo run` when there are no schedules
  core/__tests__/bin/run.ts
  core/src/bin/run.ts
  core/src/bin/validate.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/demo.ts
Labels: enhancement

#1761 `grouparoo run` runs all Schedules
  core/__tests__/bin/run.ts
  core/__tests__/tasks/schedule/enqueueRuns.ts
  core/__tests__/tasks/schedule/updateSchedules.ts
  core/src/bin/run.ts
  core/src/tasks/schedule/enqueueRuns.ts
Labels: enhancement

#1760 fix: update tracked group when going back to previously tracked group
  core/__tests__/actions/destinations.ts
  core/src/actions/destinations.ts
  core/src/config/routes.ts
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export-id.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-export.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-table-import.ts
  ui/ui-components/utils/apiData.ts
  ui/ui-enterprise/pages/destination/[id]/data.tsx
Labels: bug

#1767 Add missing sync modes entry to destination templates.
  plugins/@grouparoo/iterable/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/onesignal/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/zendesk/public/templates/destination/{{{id}}}.js.template
Labels: enhancement, plugin

#1737 Use `force` to determine if Profiles in the Group should be re-imported fully
  core/__tests__/actions/destinations.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/run/run.ts
  core/__tests__/tasks/destination/destroy.ts
  core/src/actions/destinations.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/runs.ts
Labels: enhancement

#1764 Allow logged models to have id values that are 191 characters in length
  core/__tests__/classes/loggedModel.ts
  core/src/classes/loggedModel.ts
  core/src/migrations/000065-lengthen-id-columns.ts
Labels: enhancement

#1749 Add sync modes to Pardot plugin.
  plugins/@grouparoo/pardot/__tests__/export/export-profiles.ts
  plugins/@grouparoo/pardot/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/pardot/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/pardot/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/pardot/src/initializers/plugin.ts
  plugins/@grouparoo/pardot/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/pardot/src/migrations/000001-plugin-pardot-syncMode.ts
Labels: enhancement, plugin

#1755 177936242 - added CTA to join slack in app nav
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/components/icons.ts
  ui/ui-components/components/navigation.tsx
  ui/ui-components/package.json
  ui/ui-enterprise/__tests__/integration/happyPath.ts
  ui/ui-enterprise/package.json
Labels: enhancement

#1766 Exports State + DB Retry
  core/__tests__/actions/exports.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/exportProfiles.ts
  core/__tests__/models/export.ts
  core/__tests__/models/profile/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/models/profile/snapshot-testing.ts
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/snapshots/snapshot-testing.ts
  core/__tests__/tasks/export/enqueue.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/system/sweeper.ts
  core/src/actions/exports.ts
  core/src/initializers/settings.ts
  core/src/migrations/000066-addExportStatesAndRetry.ts
  core/src/models/Destination.ts
  core/src/models/Export.ts
  core/src/models/Import.ts
  core/src/models/Run.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/export.ts
  core/src/modules/stateMachine.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/export/send.ts
  core/src/tasks/export/sendBatch.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/export.ts
  ui/ui-components/components/badges/stateBadge.tsx
  ui/ui-components/components/export/diff.tsx
  ui/ui-components/components/export/list.tsx
  ui/ui-components/components/import/diff.tsx
  ui/ui-components/components/tabs.tsx
  ui/ui-components/components/tabs/resque.tsx
  ui/ui-components/pages/destinations.tsx
  ui/ui-components/pages/export/[id]/edit.tsx
  ui/ui-components/pages/settings/[tab].tsx
  ui/ui-components/utils/languageHelper.ts
  ui/ui-enterprise/pages/destination/new/[appId].tsx
  ui/ui-enterprise/pages/source/new/[appId].tsx
Labels: enhancement

#1777 Support enabling redis SSL via ENV directly
  core/src/config/redis.ts
Labels: enhancement

#1776 Support batch imports with non-unique primary keys
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperties.ts
  plugins/@grouparoo/bigquery/__tests__/data/accounts.csv
  plugins/@grouparoo/bigquery/__tests__/data/profiles.csv
  plugins/@grouparoo/bigquery/__tests__/data/seed.md
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-properties.js
  plugins/@grouparoo/bigquery/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/bigquery/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/mysql/__tests__/data/accounts.csv
  plugins/@grouparoo/mysql/__tests__/data/profiles.csv
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/mysql/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/mysql/__tests__/utils/data.ts
  plugins/@grouparoo/postgres/__tests__/data/accounts.csv
  plugins/@grouparoo/postgres/__tests__/data/profiles.csv
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/__tests__/utils/data.ts
  plugins/@grouparoo/snowflake/__tests__/data/accounts.csv
  plugins/@grouparoo/snowflake/__tests__/data/profiles.csv
  plugins/@grouparoo/snowflake/__tests__/data/seed.md
  plugins/@grouparoo/snowflake/__tests__/fixtures/cli.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-profile-properties.js
  plugins/@grouparoo/snowflake/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/source.ts
Labels: bug

#1778 If a Profile Property's dependencies are not ready, update `startedAt` try again soon
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/profileProperty/importProfileProperty.ts
  core/src/modules/ops/import.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
Labels: enhancement

#1783 Respond to HEAD requests for status actions
  core/src/config/routes.ts
Labels: bug

#1781 Update bigquery nockHelper
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-get-changed-row-count.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import-properties.js
  plugins/@grouparoo/bigquery/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/bigquery/__tests__/utils/nockHelper.ts
Labels: internal

#1768 Add sync modes to Sendgrid destination plugin.
  plugins/@grouparoo/sendgrid/__tests__/export/export-profile.ts
  plugins/@grouparoo/sendgrid/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/sendgrid/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/sendgrid/src/initializers/plugin.ts
  plugins/@grouparoo/sendgrid/src/lib/export/exportProfile.ts
  plugins/@grouparoo/sendgrid/src/migrations/000001-plugin-sendgrid-syncMode.ts
Labels: enhancement, plugin

#1782 Support pre-loaded properties for `profile.addOrUpdateProperties` and increase Import batch sizes
  bin/timed_run
  core/__tests__/models/profile/profile.ts
  core/__tests__/tasks/group/destroy.ts
  core/__tests__/tasks/group/run.ts
  core/src/initializers/settings.ts
  core/src/models/Profile.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/query-profiles.js
  plugins/@grouparoo/google-sheets/__tests__/integration/google-sheets-import.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-import.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-profiles.js
Labels: enhancement

#1773 enqueue deletion of various models in code config
  core/__tests__/actions/groups.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/tasks/app/destroy.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/group/destroy.ts
  core/__tests__/tasks/property/destroy.ts
  core/__tests__/tasks/source/destroy.ts
  core/__tests__/tasks/system/destroy.ts
  core/src/actions/destinations.ts
  core/src/actions/groups.ts
  core/src/actions/properties.ts
  core/src/config/tasks.ts
  core/src/models/App.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/ops/destination.ts
  core/src/tasks/app/destroy.ts
  core/src/tasks/destination/destroy.ts
  core/src/tasks/group/destroy.ts
  core/src/tasks/group/run.ts
  core/src/tasks/property/destroy.ts
  core/src/tasks/source/destroy.ts
  core/src/tasks/system/destroy.ts
Labels: enhancement

#1787 Cleanup core exports
  core/src/classes/plugin.ts
  core/src/index.ts
  core/src/models/Source.ts
Labels: internal

#1784 New Publishing Workflow
  .circleci/config.yml
  .github/workflows/publish.yml
  bin/publish
  package.json
  tools/merger/data/ci/base.yml.template
  tools/merger/data/ci/publish/core.yml.template
  tools/merger/src/ci_generate.js
Labels: internal

#1788 fix: don't crash on `null` option for bootstrapped property
  core/__tests__/fixtures/codeConfig/initial/config.js
  core/src/modules/configLoaders/source.ts
Labels: bug

#1790 `runs:updateCounts` is resilient to one Run throwing
  core/__tests__/tasks/run/updateCounts.ts
  core/src/tasks/run/updateCounts.ts
Labels: bug

#1792 Display first-time imports with null diff properly
  core/__tests__/tasks/run/internalRun.ts
  ui/ui-components/components/import/diff.tsx
Labels: bug

#1793 Inject APM instrumentation into CLSAction and CLSTask
  core/src/classes/actions/clsAction.ts
  core/src/classes/tasks/clsTask.ts
  core/src/initializers/apm.ts
  core/src/modules/apm.ts
  core/src/modules/plugin.ts
  plugins/@grouparoo/newrelic/src/initializers/newrelic.ts
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
Labels: enhancement

#1791 Optionally preload Properties for `profile.properties`
  core/src/models/Profile.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/profile/completeImport.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  plugins/@grouparoo/app-templates/src/source/table/profileProperty.ts
Labels: enhancement

#1785 Add sync modes to Sailthru destination plugin.
  plugins/@grouparoo/sailthru/__tests__/export/export-profile.ts
  plugins/@grouparoo/sailthru/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/sailthru/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/sailthru/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/lib/client.ts
  plugins/@grouparoo/sailthru/src/lib/export/exportProfile.ts
  plugins/@grouparoo/sailthru/src/migrations/000001-plugin-sailthru-syncMode.ts
Labels: enhancement, plugin

#1797 Swagger API routes based on `WEB_URL`
  core/src/actions/swagger.ts
Labels: bug

#1798 `properties:list` action does not always include examples
  core/__tests__/actions/properties.ts
  core/src/actions/properties.ts
  ui/ui-components/pages/properties.tsx
  ui/ui-components/pages/source/[id]/mapping.tsx
Labels: enhancement

#1770 Add sync modes to Customer.io destination plugin.
  plugins/@grouparoo/customerio/__tests__/export/export-profile.ts
  plugins/@grouparoo/customerio/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/customerio/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/customerio/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/customerio/src/initializers/plugin.ts
  plugins/@grouparoo/customerio/src/lib/client.ts
  plugins/@grouparoo/customerio/src/lib/connect.ts
  plugins/@grouparoo/customerio/src/lib/export/exportProfile.ts
  plugins/@grouparoo/customerio/src/lib/test.ts
  plugins/@grouparoo/customerio/src/migrations/000002-plugin-customerio-syncMode-rename-apikey.ts
Labels: enhancement, plugin

#1800 Display proper run percentage when deleting Group members
  core/__tests__/models/run/run.ts
  core/src/modules/ops/runs.ts
Labels: bug

#1795 Write schedules to their source config files
  core/__tests__/modules/configWriter.ts
  core/src/models/Source.ts
  core/src/modules/configWriter.ts
Labels: enhancement

#1803 CLI Sets NEXT_DEVELOPMENT_MODE=false & Better CLI Tests
  cli/__tests__/test.sh
  core/src/bin/apply.ts
  core/src/bin/config.ts
  core/src/bin/console.ts
  core/src/bin/generate.ts
  core/src/bin/reset.ts
  core/src/bin/run.ts
  core/src/bin/start.ts
  core/src/bin/status.ts
  core/src/bin/sync.ts
  core/src/bin/validate.ts
  core/src/modules/cli.ts
Labels: bug

#1805 Do not show destination/data page until ready
  plugins/@grouparoo/mailchimp/src/lib/shared/destinationMappingOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/sqlite/src/lib/export/destinationMappingOptions.ts
  ui/ui-components/components/tabs/destination.tsx
Labels: bug

#1796 Add ability to edit config files
  core/__tests__/modules/configWriter.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/configWriter.ts
Labels: enhancement

#1801 Force delete destinations and groups in config mode
  core/src/models/Destination.ts
  ui/ui-components/pages/destination/[id]/edit.tsx
  ui/ui-components/pages/group/[id]/edit.tsx
Labels: enhancement

#1806 Include no-op `schedule:updateSchedules` task to prevent resque errors
  core/src/tasks/schedule/updateSchedules.ts
Labels: bug

#1807 Webpack artifact improvements
  bin/publish
  package.json
  ui/ui-community/.npmignore
  ui/ui-community/package.json
  ui/ui-components/.npmignore
  ui/ui-config/.npmignore
  ui/ui-config/package.json
  ui/ui-enterprise/.npmignore
  ui/ui-enterprise/package.json
Labels: enhancement

#1808 Update the READMEs for the UI packages
  ui/ui-community/README.md
  ui/ui-config/README.md
Labels: enhancement

#1804 Update to latest `actionhero` and `node-resque`
  core/package.json
  core/src/config/logger.ts
  core/src/grouparoo.ts
  core/src/tasks/system/status.ts
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies, enhancement

#1811 Add sync modes to Postgres SQL destination plugin.
  plugins/@grouparoo/postgres/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/postgres/__tests__/export/export-profile.ts
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/postgres/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/export/exportProfile.ts
  plugins/@grouparoo/postgres/src/migrations/000001-plugin-postgres-syncMode.ts
  plugins/@grouparoo/sqlite/src/lib/export/exportProfile.ts
Labels: enhancement, plugin

#1813 replaced browser.sleep with until(elementLocated)
  ui/ui-enterprise/__tests__/integration/happyPath.ts
Labels: internal

#1810 Filter App.options from logs
  core/__tests__/models/app/app.ts
  core/src/classes/loggedModel.ts
  core/src/config/api.ts
  core/src/config/tasks.ts
  core/src/models/App.ts
  core/src/models/Source.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/bigquery/src/initializers/plugin.ts
  plugins/@grouparoo/bigquery/src/lib/appOptions.ts
  plugins/@grouparoo/customerio/src/initializers/plugin.ts
  plugins/@grouparoo/customerio/src/lib/appOptions.ts
  plugins/@grouparoo/facebook/src/initializers/plugin.ts
  plugins/@grouparoo/facebook/src/lib/appOptions.ts
  plugins/@grouparoo/google-sheets/src/initializers/plugin.ts
  plugins/@grouparoo/google-sheets/src/lib/appOptions.ts
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/appOptions.ts
  plugins/@grouparoo/intercom/src/initializers/plugin.ts
  plugins/@grouparoo/intercom/src/lib/appOptions.ts
  plugins/@grouparoo/iterable/src/initializers/plugin.ts
  plugins/@grouparoo/iterable/src/lib/appOptions.ts
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/lib/appOptions.ts
  plugins/@grouparoo/marketo/src/initializers/plugin.ts
  plugins/@grouparoo/marketo/src/lib/appOptions.ts
  plugins/@grouparoo/mysql/src/initializers/plugin.ts
  plugins/@grouparoo/mysql/src/lib/appOptions.ts
  plugins/@grouparoo/onesignal/src/initializers/plugin.ts
  plugins/@grouparoo/onesignal/src/lib/appOptions.ts
  plugins/@grouparoo/pardot/src/initializers/plugin.ts
  plugins/@grouparoo/pardot/src/lib/appOptions.ts
  plugins/@grouparoo/pipedrive/src/initializers/plugin.ts
  plugins/@grouparoo/pipedrive/src/lib/appOptions.ts
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/appOptions.ts
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/initializers/plugin.ts
  plugins/@grouparoo/sailthru/src/lib/appOptions.ts
  plugins/@grouparoo/salesforce/src/initializers/plugin.ts
  plugins/@grouparoo/salesforce/src/lib/appOptions.ts
  plugins/@grouparoo/sendgrid/src/initializers/plugin.ts
  plugins/@grouparoo/sendgrid/src/lib/appOptions.ts
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/lib/appOptions.ts
  plugins/@grouparoo/zendesk/src/initializers/plugin.ts
  plugins/@grouparoo/zendesk/src/lib/appOptions.ts
Labels: enhancement

#1812 Add sync modes to Redshift destination plugin.
  plugins/@grouparoo/redshift/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/redshift/src/initializers/plugin.ts
  plugins/@grouparoo/redshift/src/migrations/000001-plugin-redshift-syncMode.ts
Labels: enhancement, plugin

#1815 Update apt before install pacakges in CI
  .circleci/config.yml
  tools/merger/data/ci/apps/job.yml.template
  tools/merger/data/ci/client/job.yml.template
  tools/merger/data/ci/core/job.yml.template
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/setup_steps.yml.template
  tools/merger/data/ci/ui/job.yml.template
Labels: internal

#1814 Be more defensive when reading StatusMetrics from redis
  core/__tests__/modules/status.ts
  core/src/modules/status.ts
Labels: bug

#1817 Update sentry dependencies
  plugins/@grouparoo/sentry/package.json
  pnpm-lock.yaml
Labels: dependencies

#1820 Reset settings in telemetry test
  core/__tests__/modules/telemetry.ts
Labels: internal

#1802 Asynchronous Exports
  core/__tests__/actions/exportProcessors.ts
  core/__tests__/actions/exports.ts
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/processExportedProfiles.ts
  core/__tests__/models/exportProcessor.ts
  core/__tests__/models/profile/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/modules/codeConfig/__snapshots__/snapshotTest.ts.snap
  core/__tests__/snapshots/__snapshots__/snapshot-testing.ts.snap
  core/__tests__/tasks/export/enqueueProcessors.ts
  core/__tests__/tasks/export/process.ts
  core/__tests__/tasks/system/sweeper.ts
  core/src/actions/exportProcessors.ts
  core/src/actions/exports.ts
  core/src/actions/navigation.ts
  core/src/classes/plugin.ts
  core/src/config/routes.ts
  core/src/index.ts
  core/src/initializers/settings.ts
  core/src/migrations/000067-addExportProcessors.ts
  core/src/models/Destination.ts
  core/src/models/Export.ts
  core/src/models/ExportProcessor.ts
  core/src/modules/errors.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/exportProcessor.ts
  core/src/modules/plugin.ts
  core/src/tasks/export/enqueueProcessors.ts
  core/src/tasks/export/process.ts
  core/src/tasks/system/sweeper.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/exportProcessor.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-community/pages/exportProcessor/[id]/edit.tsx
  ui/ui-community/pages/exportProcessor/[id]/exports.tsx
  ui/ui-community/pages/exportProcessors.tsx
  ui/ui-components/components/export/list.tsx
  ui/ui-components/components/tabs/exportProcessor.tsx
  ui/ui-components/pages/export/[id]/edit.tsx
  ui/ui-components/pages/exportProcessor/[id]/edit.tsx
  ui/ui-components/pages/exportProcessor/[id]/exports.tsx
  ui/ui-components/pages/exportProcessors.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-enterprise/pages/exportProcessor/[id]/edit.tsx
  ui/ui-enterprise/pages/exportProcessor/[id]/exports.tsx
  ui/ui-enterprise/pages/exportProcessors.tsx
Labels: enhancement

#1822 Upgrade to Actionhero v26.0.3
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1818 `plugin.createImports()` to create imports in bulk
  core/__tests__/modules/plugin.ts
  core/src/models/Import.ts
  core/src/modules/plugin.ts
  plugins/@grouparoo/app-templates/src/source/query/profiles.ts
  plugins/@grouparoo/app-templates/src/source/table/profiles.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/query-profiles.js
  plugins/@grouparoo/bigquery/__tests__/query-import/profiles.ts
  plugins/@grouparoo/bigquery/__tests__/table-import/profiles.ts
  plugins/@grouparoo/csv/__tests__/file-import/profiles.ts
  plugins/@grouparoo/csv/__tests__/remote-import/profiles.ts
  plugins/@grouparoo/csv/src/lib/shared/parseProfiles.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/profiles.ts
  plugins/@grouparoo/mailchimp/__tests__/import/profiles.ts
  plugins/@grouparoo/mailchimp/src/lib/import/profiles.ts
  plugins/@grouparoo/mongo/__tests__/query-import/profiles.ts
  plugins/@grouparoo/mongo/__tests__/table-import/profiles.ts
  plugins/@grouparoo/mysql/__tests__/query-import/profiles.ts
  plugins/@grouparoo/mysql/__tests__/table-import/profiles.ts
  plugins/@grouparoo/postgres/__tests__/query-import/profiles.ts
  plugins/@grouparoo/postgres/__tests__/table-import/profiles.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-profiles.js
  plugins/@grouparoo/snowflake/__tests__/query-import/profiles.ts
  plugins/@grouparoo/snowflake/__tests__/table-import/profiles.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/profiles.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/profiles.ts
Labels: enhancement

#1821 Bump next to 10.2.2
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#1819 Speed up `profile:checkReady` with a custom query
  .circleci/config.yml
  core/__tests__/tasks/import/associateProfile.ts
  core/__tests__/tasks/profile/checkReady.ts
  core/__tests__/tasks/profile/completeImport.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/schedule/run.ts
  core/src/modules/ops/profile.ts
  plugins/@grouparoo/spec-helper/src/lib/workflows/import.ts
  tools/merger/src/ci_generate.js
Labels: bug

#1816 Speed up `imports:associateProfile` task
  core/src/classes/loggedModel.ts
  core/src/migrations/000067-profilePropertiesRawValueIndex.ts
  core/src/models/Export.ts
  core/src/models/Log.ts
  core/src/modules/ops/export.ts
  core/src/modules/ops/import.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/profileProperty.ts
  core/src/tasks/event/associateProfile.ts
  core/src/tasks/import/associateProfile.ts
  core/src/tasks/system/status.ts
Labels: enhancement

#1825 Adding/Removing Group Members happens in bulk
  core/src/models/Group.ts
  core/src/models/Profile.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/profile.ts
Labels: enhancement

#1827 Speed up `profile:completeImport` with eager loading
  core/src/models/Group.ts
  core/src/models/Profile.ts
  core/src/tasks/profile/completeImport.ts
Labels: enhancement

#1824 remove csv:file from roo generate list
  plugins/@grouparoo/csv/public/templates/source/file/{{{id}}}.js.template
  plugins/@grouparoo/csv/src/initializers/plugin.ts
Labels: enhancement

#1830 Actionhero v26.0.4
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#1826 bring back deleted models in code config
  core/__tests__/bin/apply.ts
  core/__tests__/bin/validate.ts
  core/__tests__/fixtures/codeConfig/bootstrapped-property-in-source/config.js
  core/__tests__/fixtures/codeConfig/initial/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/codeConfig/validate.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/source.ts
Labels: enhancement

#1836 `buildNullProperties` defaults to Profile Properties in the 'pending' state
  core/__tests__/actions/profiles.ts
  core/__tests__/models/event.ts
  core/__tests__/models/export.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/tasks/profileProperty/enqueue.ts
  core/__tests__/tasks/system/status.ts
  core/src/models/Profile.ts
  core/src/modules/ops/profile.ts
Labels: bug

#1837 Add an index to `*.startedAt`
  core/src/migrations/000069-startedAtIndex.ts
Labels: enhancement

#1828 Allow date strings in group rules for code config
  core/__tests__/fixtures/codeConfig/group-rule-with-date/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/modules/configLoaders/group.ts
Labels: enhancement

#1840 Internal runs create/update Profile Properties in bulk
  core/__tests__/integration/runs/internalRun.ts
  core/__tests__/tasks/run/internalRun.ts
  core/src/models/Profile.ts
  core/src/modules/internalRun.ts
  core/src/modules/ops/profile.ts
  core/src/tasks/run/internalRun.ts
Labels: enhancement

#1829 Make plugin installation part of the new app process in Config UI
  .circleci/config.yml
  apps/staging-config/.env.example
  apps/staging-config/LICENSE.txt
  apps/staging-config/package.json
  core/__tests__/actions/plugins.ts
  core/__tests__/fixtures/actions/plugins.ts
  core/src/actions/plugins.ts
  core/src/config/plugins.ts
  core/src/modules/plugins.ts
  pnpm-lock.yaml
  ui/ui-components/components/appSelectorList.tsx
  ui/ui-components/components/selector.tsx
  ui/ui-components/pages/app/new.tsx
  ui/ui-config/package.json
  ui/ui-config/pages/app/new.tsx
  ui/ui-config/pages/plugins.tsx
  ui/ui-enterprise/pages/app/new.tsx
Labels: enhancement

#1846 Use latest `pnpm` version again
  package.json
Labels: internal
