Repository grouparoo/grouparoo, pull requests merged in 2021-08, with the labels that each got.

#2116 update `actionhero` and `ws`
  core/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/files-local/package.json
  plugins/@grouparoo/files-s3/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2117 ApiKey values can be set via codeConfig
  core/__tests__/fixtures/codeConfig/bootstrapped-property-in-source/config.js
  core/__tests__/fixtures/codeConfig/changes/config.js
  core/__tests__/fixtures/codeConfig/error-changed-type-missing/config.js
  core/__tests__/fixtures/codeConfig/initial/config.js
  core/__tests__/fixtures/codeConfig/multiple-sources/config.js
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/classes/codeConfig.ts
  core/src/modules/configLoaders/apiKey.ts
Labels: enhancement

#2087 delete profiles when they are no longer present in the source
  core/__tests__/actions/properties.ts
  core/__tests__/actions/schedules.ts
  core/__tests__/fixtures/codeConfig/bootstrapped-property-in-source/config.js
  core/__tests__/fixtures/codeConfig/initial/config.js
  core/__tests__/models/destination/plugins/exportProfile.ts
  core/__tests__/models/destination/plugins/exportProfiles.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/configWriter.ts
  core/__tests__/modules/plugin.ts
  core/__tests__/modules/status.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/import/associateProfile.ts
  core/__tests__/tasks/profile/checkReady.ts
  core/__tests__/tasks/profile/confirm.ts
  core/__tests__/tasks/profile/export.ts
  core/__tests__/tasks/profile/sweep.ts
  core/__tests__/tasks/profileProperty/enqueue.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/__tests__/tasks/profileProperty/importProfileProperty.ts
  core/__tests__/tasks/system/status/status.ts
  core/src/actions/properties.ts
  core/src/actions/schedules.ts
  core/src/classes/codeConfig.ts
  core/src/initializers/settings.ts
  core/src/migrations/000077-addScheduleConfirmProfiles.ts
  core/src/migrations/000078-propertyKeepValueIfNotFound.ts
  core/src/models/Profile.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/profile.ts
  core/src/modules/status.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/import/associateProfile.ts
  core/src/tasks/profile/confirm.ts
  core/src/tasks/profile/sweep.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  core/src/tasks/profileProperty/importProfileProperty.ts
  core/src/tasks/system/status/status.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/profile.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-components/pages/import/[id]/edit.tsx
  ui/ui-components/pages/property/[id]/edit.tsx
  ui/ui-components/pages/source/[id]/schedule.tsx
Labels: enhancement

#2118 Remove SyncTable & Refactor CodeConfig Types
  core/__tests__/classes/codeConfig.ts
  core/__tests__/fixtures/codeConfig/sync-table/initial/config.js
  core/__tests__/modules/codeConfig/syncTable.ts
  core/__tests__/modules/configWriter.ts
  core/__tests__/modules/mustacheUtils.ts
  core/src/bin/validate.ts
  core/src/classes/codeConfig.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Group.ts
  core/src/models/Profile.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Setting.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/apiKey.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/profile.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/setting.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/configLoaders/syncTable.ts
  core/src/modules/configLoaders/team.ts
  core/src/modules/configLoaders/teamMember.ts
  core/src/modules/configWriter.ts
  core/src/modules/mustacheUtils.ts
  plugins/@grouparoo/app-templates/src/source/table/meta.ts
Labels: enhancement

#2120 Update MongoDB version to 4.0.1.
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/demo/src/connections/mongo.ts
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mongo/src/lib/connect.ts
  pnpm-lock.yaml
Labels: dependencies, plugin

#2124 Fix Property Option `ownerType`
  core/src/migrations/000056-propertiesModel.ts
  core/src/migrations/000079-fixPropertyOwnerType.ts
Labels: bug

#2132 Update `customerio-node` to v3.0.2
  plugins/@grouparoo/customerio/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/customerio/__tests__/export/export-profile.ts
  plugins/@grouparoo/customerio/__tests__/fixtures/destination-mapping-options.js
  plugins/@grouparoo/customerio/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/customerio/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/customerio/src/lib/client.ts
  pnpm-lock.yaml
Labels: dependencies

#2134 Retry the publish command with NPM if Lerna publish fails
  bin/publish
Labels: internal

#2135 Speed up Profile Deletion checks
  core/__tests__/tasks/profile/sweep.ts
  core/src/modules/ops/profile.ts
Labels: enhancement

#2136 Destinations can share the same App and Options if they track different Groups
  core/__tests__/actions/destinations.ts
  core/__tests__/models/destination/destination.ts
  core/src/models/Destination.ts
Labels: enhancement

#2140 fix: dont crash on confirmProfiles if the schedule has no runs
  core/__tests__/tasks/profile/confirm.ts
  core/src/tasks/profile/confirm.ts
Labels: bug

#2142 Adapt migration to handle custom schema.
  core/bin/migrator
  core/package.json
  core/src/config/sequelize.ts
  pnpm-lock.yaml
Labels: enhancement, internal

#2143 Database name update issue.
  plugins/@grouparoo/mongo/__tests__/utils/data.ts
  plugins/@grouparoo/mongo/src/lib/connect.ts
  plugins/@grouparoo/mongo/src/lib/disconnect.ts
  plugins/@grouparoo/mongo/src/lib/query-import/executeQuery.ts
  plugins/@grouparoo/mongo/src/lib/query-import/getChangedRows.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getChangedRowCount.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getChangedRows.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getColumns.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getSampleRows.ts
  plugins/@grouparoo/mongo/src/lib/table-import/getTables.ts
  plugins/@grouparoo/mongo/src/lib/table-import/util.ts
  plugins/@grouparoo/mongo/src/lib/test.ts
Labels: bug, plugin

#2145 fix: keepValueIfNotFound is applied when importing synchronously (Import and Export button)
  core/__tests__/fixtures/codeConfig/changes/config.js
  core/__tests__/models/profile/profile.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/ops/profile.ts
Labels: bug

#2119 Sources can map via non-unique mapping
  core/__tests__/data/translations.csv
  core/__tests__/models/property/property.ts
  core/__tests__/models/source/source.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/src/models/Property.ts
  core/src/models/Source.ts
  core/src/modules/mappingHelper.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/source.ts
  core/src/tasks/profileProperty/importProfileProperties.ts
  ui/ui-components/components/visualizations/homepageWidgets.tsx
  ui/ui-components/pages/source/[id]/mapping.tsx
  ui/ui-components/pages/source/[id]/overview.tsx
Labels: enhancement

#2147 Schdule options and filters can be changed
  core/__tests__/models/schedule.ts
  core/src/models/Schedule.ts
  core/src/modules/reset.ts
  ui/ui-components/pages/source/[id]/schedule.tsx
Labels: enhancement

#2173 Use unique Profiles IDs when processing `preparePropertyImports`
  core/__tests__/models/profileProperty/processPendingProfileProperties.ts
  core/__tests__/tasks/profileProperty/importProfileProperties.ts
  core/src/modules/ops/profileProperty.ts
Labels: bug

#2174 Sort Profile Properties for Mapping with Unique first
  ui/ui-community/next-env.d.ts
  ui/ui-components/pages/source/[id]/mapping.tsx
  ui/ui-config/next-env.d.ts
  ui/ui-enterprise/next-env.d.ts
Labels: enhancement

#2177 Use Sequelize query builder directly for better types
  core/src/actions/profiles.ts
  core/src/actions/teams.ts
  core/src/actions/totals.ts
  core/src/index.ts
  core/src/models/Export.ts
  core/src/models/ExportProcessor.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/models/Run.ts
  core/src/modules/cli.ts
  core/src/modules/mustacheUtils.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/profile.ts
  core/src/modules/ops/source.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/run/updateCounts.ts
  plugins/@grouparoo/demo/src/bin/grouparoo/demo/demo.ts
Labels: enhancement

#2182 Do not consider null responses when mapping non-unique value property responses
  core/src/modules/ops/source.ts
Labels: bug

#2179 Provide types to Property Options via `PluginOptionType`
  core/__tests__/models/app/app.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/source/source.ts
  core/src/classes/plugin.ts
  core/src/index.ts
  core/src/models/App.ts
  core/src/models/Property.ts
  core/src/modules/ops/property.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/app-templates/src/source/query/meta.ts
  plugins/@grouparoo/app-templates/src/source/table/pluginMethods.ts
  plugins/@grouparoo/app-templates/src/source/table/sourceOptions.ts
  plugins/@grouparoo/csv/src/lib/remote-import/sourceOptions.ts
  plugins/@grouparoo/mailchimp/src/lib/shared/connectionOptions.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/destination/[id]/edit.tsx
  ui/ui-components/pages/property/[id]/edit.tsx
  ui/ui-components/pages/source/[id]/edit.tsx
Labels: internal

#2191 resolve pending properties before sync-importing dependent source
  core/__tests__/models/profile/profile.ts
  core/src/modules/ops/profile.ts
Labels: bug

#2195 Add missing API formatter and remove un-used import
  core/src/actions/profiles.ts
  core/src/models/Export.ts
Labels: internal

#2189 Mixpanel batch and single export hybrid integration
  plugins/@grouparoo/mixpanel/__tests__/export/export-profile.ts
  plugins/@grouparoo/mixpanel/__tests__/export/export-profiles.ts
  plugins/@grouparoo/mixpanel/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mixpanel/__tests__/fixtures/export-profiles.js
  plugins/@grouparoo/mixpanel/src/initializers/plugin.ts
  plugins/@grouparoo/mixpanel/src/lib/client/profile.ts
  plugins/@grouparoo/mixpanel/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mixpanel/src/lib/export/exportProfiles.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement, plugin

#2205 `schedules:run` action to run all Schedules
  core/__tests__/actions/schedules.ts
  core/__tests__/integration/happyPath.ts
  core/src/actions/schedules.ts
  core/src/config/routes.ts
  core/src/models/Schedule.ts
  plugins/@grouparoo/csv/__tests__/integration/csv-file.ts
  plugins/@grouparoo/csv/__tests__/integration/csv-remote.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/google-sheets-import.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimp-import.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysql-table-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-table-import.ts
  ui/ui-components/pages/sources.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-enterprise/pages/source/[id]/runs.tsx
Labels: enhancement

#2206 Stricter types for Authentication
  core/src/actions/session.ts
  core/src/classes/actions/clsAction.ts
  core/src/models/ApiKey.ts
  core/src/models/Permission.ts
  core/src/models/Team.ts
  core/src/modules/middleware/authentication.ts
Labels: internal

#2209 Remove `import:create` Action
  core/__tests__/actions/imports.ts
  core/src/actions/imports.ts
  core/src/config/routes.ts
  core/src/models/Import.ts
  ui/ui-components/utils/apiData.ts
Labels: internal

#2207 SessionCreate is a write transaction
  core/src/actions/session.ts
Labels: internal

#2192 Prevent data in Secondary Sources from Creating Profiles that do not exist in the Primary Sources
  core/__tests__/actions/imports.ts
  core/__tests__/models/profile/profile.ts
  core/__tests__/models/profile/snapshot-testing.ts
  core/__tests__/snapshots/snapshot-testing.ts
  core/__tests__/tasks/import/associateProfile.ts
  core/__tests__/tasks/profile/checkReady.ts
  core/__tests__/tasks/profile/export.ts
  core/__tests__/tasks/profileProperty/enqueue.ts
  core/src/actions/imports.ts
  core/src/config/routes.ts
  core/src/models/Import.ts
  core/src/models/Profile.ts
  core/src/models/Run.ts
  core/src/modules/ops/import.ts
  core/src/modules/ops/profile.ts
  plugins/@grouparoo/csv/src/lib/shared/parseProfiles.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqlite-table-import.ts
  ui/ui-components/utils/apiData.ts
Labels: enhancement

#2212 Log Sequelize query execution time
  core/src/config/sequelize.ts
Labels: enhancement

#2224 Fix Mailjet logo extersion
  plugins/@grouparoo/mailjet/src/initializers/plugin.ts
Labels: bug, plugin

#2223 Batch checkErrors issue
  plugins/@grouparoo/app-templates/src/destination/shared/batch.ts
  plugins/@grouparoo/facebook/__tests__/integration/export-profiles-custom.ts
  plugins/@grouparoo/marketo/__tests__/integration/export-profiles.ts
  plugins/@grouparoo/mixpanel/__tests__/export/export-profiles.ts
  plugins/@grouparoo/pardot/__tests__/export/export-profiles.ts
  plugins/@grouparoo/salesforce/__tests__/export-objects/export-profiles-additive.ts
  plugins/@grouparoo/salesforce/__tests__/export-objects/export-profiles-enrich.ts
Labels: bug, plugin

#2230 Add objectCache to Mailjet listMethods
  plugins/@grouparoo/mailjet/__tests__/fixtures/export-profile.js
  plugins/@grouparoo/mailjet/src/lib/export/exportProfile.ts
  plugins/@grouparoo/mailjet/src/lib/export/listMethods.ts
Labels: bug, plugin

#2188 Prometheus plugin
  .circleci/config.yml
  apps/staging-community/package.json
  core/__tests__/modules/status.ts
  core/src/index.ts
  core/src/modules/status.ts
  plugins/@grouparoo/prometheus/README.md
  plugins/@grouparoo/prometheus/__tests__/action/metrics_test.ts
  plugins/@grouparoo/prometheus/__tests__/initializers/plugin.ts
  plugins/@grouparoo/prometheus/jest.config.js
  plugins/@grouparoo/prometheus/jest.setup.js
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/prometheus/src/actions/metrics.ts
  plugins/@grouparoo/prometheus/src/initializers/plugin.ts
  plugins/@grouparoo/prometheus/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#2234 faster publish docs by skipping build step
  .github/workflows/publish-docs.yml
Labels: internal

#2235 sleep before notifying omnibus
  .github/workflows/publish.yml
Labels: internal
