Repository grouparoo/grouparoo, pull requests merged in 2022-02, with the labels that each got.

#2884 validate compatible app and connection types
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/source/source.ts
  core/src/models/Destination.ts
  core/src/models/Source.ts
  plugins/@grouparoo/salesforce/__tests__/export-account/destination-mapping-options-enrich.ts
  plugins/@grouparoo/salesforce/__tests__/export-account/destination-mapping-options.ts
  plugins/@grouparoo/salesforce/__tests__/export-contacts/destination-mapping-options-enrich.ts
  plugins/@grouparoo/salesforce/__tests__/export-contacts/destination-mapping-options.ts
  plugins/@grouparoo/salesforce/__tests__/export-objects/destination-mapping-options-enrich.ts
  plugins/@grouparoo/salesforce/__tests__/export-objects/destination-mapping-options.ts
Labels: enhancement

#2875 Add Grouparoo model global context
  ui/ui-components/__tests__/components/tabs.tsx
  ui/ui-components/components/lib/entity/EntityList.tsx
  ui/ui-components/components/model/overview/ModelOverviewDestinations.tsx
  ui/ui-components/components/model/overview/ModelOverviewGroups.tsx
  ui/ui-components/components/model/overview/ModelOverviewPrimarySource.tsx
  ui/ui-components/components/model/overview/ModelOverviewSchedules.tsx
  ui/ui-components/components/model/overview/ModelOverviewSecondarySources.tsx
  ui/ui-components/components/record/List.tsx
  ui/ui-components/components/tabs/Destination.tsx
  ui/ui-components/components/tabs/Group.tsx
  ui/ui-components/components/tabs/Property.tsx
  ui/ui-components/components/tabs/Record.tsx
  ui/ui-components/components/tabs/Source.tsx
  ui/ui-components/contexts/grouparooModel.tsx
  ui/ui-components/pages/_app.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/exports.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/retry.tsx
  ui/ui-components/pages/model/[modelId]/destination/new/[appId].tsx
  ui/ui-components/pages/model/[modelId]/destination/new/index.tsx
  ui/ui-components/pages/model/[modelId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/group/[groupId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/group/[groupId]/members.tsx
  ui/ui-components/pages/model/[modelId]/group/[groupId]/rules.tsx
  ui/ui-components/pages/model/[modelId]/group/new.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/exports.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/imports.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/logs.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
  ui/ui-components/pages/model/[modelId]/source/new/[appId].tsx
  ui/ui-components/pages/model/[modelId]/source/new/index.tsx
  ui/ui-components/utils/contextHelper.tsx
  ui/ui-enterprise/pages/model/[modelId]/group/[groupId]/destinations.tsx
  ui/ui-enterprise/pages/model/[modelId]/group/[groupId]/logs.tsx
  ui/ui-enterprise/pages/model/[modelId]/group/[groupId]/runs.tsx
  ui/ui-enterprise/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/groups.tsx
  ui/ui-enterprise/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/logs.tsx
  ui/ui-enterprise/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/records.tsx
  ui/ui-enterprise/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/runs.tsx
  ui/ui-enterprise/pages/model/[modelId]/source/[sourceId]/runs.tsx
Labels: internal

#2913 Bump sentry versions (v6.17.3) in tandem
  plugins/@grouparoo/sentry/package.json
  pnpm-lock.yaml
Labels: dependencies

#2912 replace `faker` with `@faker-js/faker`
  core/__tests__/modules/configWriter.ts
  core/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/spec-helper/src/lib/factories/apiKey.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/app.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/destination.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/group.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/record.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/schedule.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/source.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/team.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/teamMember.ts
  pnpm-lock.yaml
Labels: internal, dependencies

#2858 Improve how queries get built in SQLite plugin
  plugins/@grouparoo/sqlite/__tests__/data/records.csv
  plugins/@grouparoo/sqlite/__tests__/export/exportRecord.ts
  plugins/@grouparoo/sqlite/__tests__/integration/logChecking.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqliteTableImport.ts
  plugins/@grouparoo/sqlite/__tests__/query-import/importProperty.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/importProperties.ts
  plugins/@grouparoo/sqlite/__tests__/table-import/importProperty.ts
  plugins/@grouparoo/sqlite/__tests__/utils/data.ts
  plugins/@grouparoo/sqlite/src/lib/connect.ts
  plugins/@grouparoo/sqlite/src/lib/export/exportRecord.ts
  plugins/@grouparoo/sqlite/src/lib/queryBuilder.ts
  plugins/@grouparoo/sqlite/src/lib/sqlite.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getRowCount.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/getRows.ts
  plugins/@grouparoo/sqlite/src/lib/table-import/util.ts
  plugins/@grouparoo/sqlite/src/lib/util.ts
Labels: bug, enhancement

#2930 Update `sequelize` and `ioredis-mock` to latest versions
  core/__tests__/actions/totals.ts
  core/package.json
  core/src/actions/totals.ts
  core/src/config/redis.ts
  core/src/config/routes.ts
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/klaviyo/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/vero/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-components/utils/apiData.ts
Labels: dependencies

#2932 update to `commander@9.0.0`, remove negated cli param defaults
  cli/package.json
  core/src/bin/run.ts
  core/src/bin/sync.ts
Labels: dependencies

#2936 Choose db=0 when redis database not provided in REDIS_URL
  core/src/config/redis.ts
Labels: bug

#2935 Update Readme intro
  core/README.md
Labels: documentation

#2933 Fix error handling issues in UI Client
  ui/ui-components/client/client.ts
  ui/ui-components/components/Navigation.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/edit.tsx
  ui/ui-components/utils/appContext.ts
  ui/ui-components/utils/getRedirectFromErrorCode.ts
  ui/ui-components/utils/withServerErrorHandler.ts
Labels: bug

#2927 Source creation works smoother, added save success messaging
  ui/ui-components/components/record/AddSampleRecordForm.tsx
  ui/ui-components/components/schedule/Add.tsx
  ui/ui-components/components/source/FormMappingSelector.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/retry.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug, enhancement

#2863 Add anchor tags to `ManagedCard` component, update "Add new Destination" button to scroll user to "Destinations" card
  core/__tests__/actions/setupSteps.ts
  core/src/modules/ops/setupSteps.ts
  ui/ui-components/__tests__/components/__snapshots__/managedCard.tsx.snap
  ui/ui-components/__tests__/components/managedCard.tsx
  ui/ui-components/__tests__/components/record/__snapshots__/SampleRecordCard.tsx.snap
  ui/ui-components/components/Tabs.tsx
  ui/ui-components/components/lib/ManagedCard.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
Labels: enhancement

#2886 Remove unused Import metadata and start `record:export` sooner
  core/__tests__/actions/records/records.ts
  core/__tests__/integration/runs/internalRun.ts
  core/__tests__/models/group/calculations.ts
  core/__tests__/models/run/run.ts
  core/__tests__/modules/plugin.ts
  core/__tests__/modules/reset.ts
  core/__tests__/tasks/group/run.ts
  core/__tests__/tasks/grouparooModel/run.ts
  core/__tests__/tasks/import/associateRecord.ts
  core/__tests__/tasks/record/checkReady/checkReady.ts
  core/__tests__/tasks/record/checkReady/smallerBatchSize.ts
  core/__tests__/tasks/record/enqueueExports/enqueueExports.ts
  core/__tests__/tasks/record/enqueueExports/smallerBatchSize.ts
  core/__tests__/tasks/record/export.ts
  core/__tests__/tasks/record/makeExports/makeExports.ts
  core/__tests__/tasks/record/makeExports/smallerBatchSize.ts
  core/__tests__/tasks/record/reEnqueueStuckExportingRecords.ts
  core/src/migrations/000100-removeImportData.ts
  core/src/models/GrouparooRecord.ts
  core/src/models/Import.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/import.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/runs.ts
  core/src/tasks/record/enqueueExports.ts
  core/src/tasks/record/export.ts
  core/src/tasks/record/makeExports.ts
  core/src/tasks/record/reEnqueueStuckExportingRecords.ts
  plugins/@grouparoo/clickhouse/__tests__/integration/clickhouseTableImport.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysqlTableImport.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgresTableImport.ts
  plugins/@grouparoo/spec-helper/src/lib/workflows/import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqliteTableImport.ts
  ui/ui-components/components/import/Diff.tsx
  ui/ui-components/components/import/List.tsx
  ui/ui-components/pages/import/[id]/edit.tsx
Labels: enhancement, internal

#2937 `/bin/timed_run` also makes exports
  bin/timed_run
Labels: internal

#2944 remove errant `logging`
  core/src/tasks/record/reEnqueueStuckExportingRecords.ts
Labels: bug

#2929 Invalid records cannot be imported
  ui/ui-components/client/client.ts
  ui/ui-components/components/record/List.tsx
  ui/ui-components/pages/model/[modelId]/group/[groupId]/members.tsx
  ui/ui-components/pages/model/[modelId]/records.tsx
  ui/ui-config/pages/model/[modelId]/records.tsx
Labels: bug

#2938 Package.json validation tests
  .circleci/config.yml
  __tests__/packages.ts
  __tests__/schemaGeneric.json
  __tests__/schemaPublic.json
  __tests__/schemaRestricted.json
  __tests__/wordCheck
  cli/__tests__/test
  jest.config.js
  package-lock.json
  package.json
  pnpm-lock.yaml
  tools/license-checker/check
  tools/log-parser/package.json
  tools/merger/data/ci/root/job.yml.template
  tools/merger/data/ci/root/workflow.yml.template
  tools/merger/src/ci_generate.js
  tools/shared/packages.js
  tools/version-checker/check
  tsconfig.json
Labels: internal

#2952 Remove package-lock.json (we use pnpm)
  .gitignore
  package-lock.json
  pnpm-lock.yaml
Labels: internal

#2941 Render sample record card on server side
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
Labels: enhancement

#2946 Fix edit page to use load preview only if available and serverprops hydration error
  ui/ui-components/pages/_app.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug

#2951 Google Sheets Destination: lock other threads while adding new records
  plugins/@grouparoo/google-sheets/__tests__/export/export-records.ts
  plugins/@grouparoo/google-sheets/__tests__/fixtures/export/destination-mapping-options.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/export/export-records.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/integration/googleSheetsImport.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/downloadAndRefreshFile.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/importRecords.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/propertyOptions.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/recordProperties.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/recordProperty.js
  plugins/@grouparoo/google-sheets/src/lib/shared/Spreadsheet.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-export/exportRecords.ts
Labels: bug, plugin

#2939 table sources provide table options as sorted typeahead
  plugins/@grouparoo/app-templates/src/source/table/sourceOptions.ts
  ui/ui-components/__tests__/components/__snapshots__/typeahead.tsx.snap
  ui/ui-components/__tests__/components/typeahead.tsx
  ui/ui-components/components/Typeahead.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: enhancement

#2954 fix: add missing await in test
  core/__tests__/models/recordProperty/recordProperty.ts
Labels: internal

#2947 Hubspot contact and company association
  plugins/@grouparoo/hubspot/__tests__/export-contacts/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-contacts/destination-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-contacts/export-record.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/destination-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/export-record.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/integration/hubspot-export.js
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/src/lib/client/objects.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationMappingOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/exportRecord.ts
  plugins/@grouparoo/hubspot/src/lib/export/options.ts
Labels: enhancement, plugin

#2948 Cleanup client error handling
  pnpm-lock.yaml
  ui/ui-components/client/client.ts
  ui/ui-components/client/clientCache.ts
  ui/ui-components/components/schedule/RunAllSchedulesButton.tsx
  ui/ui-components/package.json
  ui/ui-components/pages/_app.tsx
  ui/ui-components/pages/about.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
  ui/ui-config/pages/app/new/index.tsx
  ui/ui-config/pages/index.tsx
  ui/ui-config/pages/session/sign-in.tsx
Labels: internal

#2949 Complete Exports in Batches
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/export.ts
  core/__tests__/modules/status.ts
  core/src/models/Export.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/export.ts
Labels: enhancement

#2956 update jest
  apps/staging-community/package.json
  apps/staging-config/package.json
  apps/staging-enterprise/package.json
  core/package.json
  package.json
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/klaviyo/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/rollbar/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/vero/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-components/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2962 fix: `incremental` default on sources depends on plugin support
  core/__tests__/models/schedule.ts
  core/src/models/Schedule.ts
Labels: bug

#2958 Sample record consistently shows groups, destinations
  ui/ui-components/__tests__/components/record/SampleRecordCard.tsx
  ui/ui-components/__tests__/components/record/__snapshots__/SampleRecordCard.tsx.snap
  ui/ui-components/components/destination/DestinationSampleRecord.tsx
  ui/ui-components/components/record/AddSampleRecordForm.tsx
  ui/ui-components/components/record/AddSampleRecordModal.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/edit.tsx
  ui/ui-config/pages/model/[modelId]/records.tsx
Labels: bug

#2961 Source creation form state
  ui/ui-components/components/source/FormMappingSelector.tsx
  ui/ui-components/hooks/useDebouncedCallback.ts
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug

#2965 Fixing a typo in snowflake's migration folder
  plugins/@grouparoo/snowflake/src/migrations/000001-plugin-snowflake-import-name.ts
Labels: bug

#2967 Do not store HighWaterMark for non-incremental Schedules
  core/__tests__/models/schedule.ts
  core/src/modules/ops/schedule.ts
  plugins/@grouparoo/app-templates/src/source/table/records.ts
Labels: bug, enhancement

#2953 Add subnav items under each model
  core/src/actions/navigation.ts
  ui/ui-components/__tests__/components/__snapshots__/navigation.tsx.snap
  ui/ui-components/__tests__/components/navigation.tsx
  ui/ui-components/components/Icons.ts
  ui/ui-components/components/Navigation.tsx
  ui/ui-components/components/navigation/HighlightingNavLink.tsx
Labels: enhancement

#2974 Ensure that all client requests specify a response type
  ui/ui-components/client/client.ts
  ui/ui-components/pages/app/[id]/refresh.tsx
  ui/ui-components/pages/object/[id].tsx
  ui/ui-components/pages/resque/delayed.tsx
  ui/ui-components/pages/resque/failed.tsx
  ui/ui-components/pages/resque/locks.tsx
  ui/ui-components/pages/resque/overview.tsx
  ui/ui-components/pages/resque/queue/[queue].tsx
  ui/ui-components/pages/resque/queue/index.tsx
  ui/ui-components/pages/resque/redis.tsx
  ui/ui-config/pages/index.tsx
Labels: internal

#2972 signal telemetry on config mode start
  core/__tests__/modules/configUser.ts
  core/__tests__/modules/telemetry.ts
  core/src/actions/navigation.ts
  core/src/initializers/telemetry.ts
  core/src/modules/configUser.ts
  core/src/modules/middleware/authentication.ts
  core/src/modules/telemetry.ts
Labels: enhancement

#2976 Catch overview page hydration errors from bad record ids
  ui/ui-components/pages/model/[modelId]/overview.tsx
Labels: bug

#2979 array properties can be mapped through non-unique properties
  core/__tests__/models/property/property.ts
  core/__tests__/models/source/source.ts
  core/src/models/Property.ts
Labels: bug

#2971 Improve email and phone number formatting
  core/__tests__/models/destination/plugins/exportRecord.ts
  core/__tests__/models/destination/plugins/exportRecords.ts
  core/__tests__/models/recordProperty/recordProperty.ts
  core/package.json
  core/src/modules/ops/recordProperty.ts
  core/src/modules/validators/isEmail.ts
  plugins/@grouparoo/app-templates/src/source/table/recordProperty.ts
  plugins/@grouparoo/demo/src/connections/snowflake.ts
  plugins/@grouparoo/demo/src/util/config.ts
  plugins/@grouparoo/demo/src/util/database.ts
  plugins/@grouparoo/demo/src/util/env.ts
  plugins/@grouparoo/demo/src/util/sample_data.ts
  plugins/@grouparoo/snowflake/__tests__/data/profiles.csv
  plugins/@grouparoo/snowflake/__tests__/table-import/importProperty.ts
  plugins/@grouparoo/snowflake/src/lib/connect.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValues.ts
  pnpm-lock.yaml
Labels: enhancement

#2970 Add Hubspot oAuth based app
  core/__tests__/modules/oAuth.ts
  core/src/modules/oAuth.ts
  core/src/modules/plugin.ts
  plugins/@grouparoo/hubspot/__tests__/.env.example
  plugins/@grouparoo/hubspot/__tests__/export-contacts/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-contacts/destination-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-contacts/export-record.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/destination-mapping-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/destination-options.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/export-records-companies.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/export-records-contact.ts
  plugins/@grouparoo/hubspot/__tests__/export-objects/export-records-custom-object.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/destination-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/export-record.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/destination-mapping-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/destination-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/export-records-companies.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/export-records-contact.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-objects/export-records-custom-object.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/test.js
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/__tests__/test.ts
  plugins/@grouparoo/hubspot/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/client/client.ts
  plugins/@grouparoo/hubspot/src/lib/client/objects.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/exportRecord.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/listMethods.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/exportRecords.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: enhancement

#2980 fix mapping to non-unique properties in the UI, hide array properties
  ui/ui-components/components/source/FormMappingSelector.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug

#2973 Add new postgres query sources to `demo` command
  plugins/@grouparoo/demo/__tests__/bin/accounts.ts
  plugins/@grouparoo/demo/__tests__/bin/users.ts
  plugins/@grouparoo/demo/config/postgres/accounts/demo_accounts_queries.json
  plugins/@grouparoo/demo/config/postgres/accounts/plan_name.json
  plugins/@grouparoo/demo/config/postgres/users/demo_users_queries.json
  plugins/@grouparoo/demo/config/postgres/users/ip_address.json
  plugins/@grouparoo/demo/src/util/configFiles.ts
Labels: enhancement

#2985 Fix flaky `modelCache` tests
  core/__tests__/models/app/modelCache.ts
  core/__tests__/models/destination/modelCache.ts
  core/__tests__/models/model/modelCache.ts
  core/__tests__/models/property/modelCache.ts
  core/__tests__/models/source/modelCache.ts
Labels: internal

#2991 Accounts generates schedule with incremental: false
  plugins/@grouparoo/demo/config/accounts/sources/demo_accounts.json
Labels: internal

#2993 Update strings with "Hubspot" to "HubSpot" as it is properly named
  plugins/@grouparoo/hubspot/README.md
  plugins/@grouparoo/hubspot/__tests__/.env.example
  plugins/@grouparoo/hubspot/__tests__/export-contacts/export-record.ts
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/public/templates/destination/objects/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/src/initializers/plugin.ts
  plugins/@grouparoo/hubspot/src/lib/client/client.ts
  plugins/@grouparoo/hubspot/src/lib/client/objects.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationMappingOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/connection.ts
  plugins/@grouparoo/hubspot/src/lib/export-objects/destinationMappingOptions.ts
Labels: bug

#2987 Disabled Dropdown -> Disabled Input
  ui/ui-components/components/badges/TypeBadge.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/edit.tsx
Labels: internal

#2984 OAuth and test connection improvements in App edit page
  ui/ui-components/pages/app/[id]/edit.tsx
Labels: enhancement

#2983 ContextProvider testing component added, with sane defaults
  ui/ui-components/__tests__/__utils__/TestContextProvider.tsx
  ui/ui-components/__tests__/__utils__/renderWithContext.tsx
  ui/ui-components/__tests__/components/navigation.tsx
  ui/ui-components/__tests__/components/record/SampleRecordCard.tsx
  ui/ui-components/__tests__/components/setupSteps/setupStepCard.tsx
  ui/ui-components/__tests__/components/setupStepsNavProgressBar.tsx
  ui/ui-components/__tests__/components/tabs.tsx
  ui/ui-components/__tests__/pages/about.tsx
Labels: internal

#2995 Events model type
  core/__tests__/actions/models.ts
  core/src/models/GrouparooModel.ts
  ui/ui-components/components/Icons.ts
Labels: enhancement

#2969 No default values for source mapping
  ui/ui-components/components/source/FormMappingSelector.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: enhancement

#2978 Snowflake destination
  plugins/@grouparoo/snowflake/__tests__/export/destination-options.ts
  plugins/@grouparoo/snowflake/__tests__/export/destinationMappingOptions.ts
  plugins/@grouparoo/snowflake/__tests__/export/export-records.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/export/destination-options.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/export/destinationMappingOptions.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/export/export-records.js
  plugins/@grouparoo/snowflake/__tests__/utils/data.ts
  plugins/@grouparoo/snowflake/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/snowflake/src/initializers/plugin.ts
  plugins/@grouparoo/snowflake/src/lib/connect.ts
  plugins/@grouparoo/snowflake/src/lib/export/connection.ts
  plugins/@grouparoo/snowflake/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/snowflake/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/snowflake/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/snowflake/src/lib/export/exportRecords.ts
  plugins/@grouparoo/snowflake/src/lib/shared/util.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getRowCount.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getRows.ts
  plugins/@grouparoo/snowflake/src/lib/table-import/getSampleRows.ts
Labels: plugin

#2986 Can use mapped fields if destination field is gone
  ui/ui-components/__tests__/pages/model/[modelId]/destination/[destinationId]/__snapshots__/data.tsx.snap
  ui/ui-components/__tests__/pages/model/[modelId]/destination/[destinationId]/data.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
Labels: bug

#2994 remove templates from old `grouparoo generate` command
  plugins/@grouparoo/hubspot/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/public/templates/destination/contacts/{{{id}}}.js.template
  plugins/@grouparoo/hubspot/public/templates/destination/objects/{{{id}}}.js.template
  plugins/@grouparoo/logger/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/logger/public/templates/destination/{{{id}}}.js.template
Labels: internal

#3001 Increment primary keys by 1 in `demo` command
  plugins/@grouparoo/demo/src/util/sample_data.ts
Labels: bug

#2990 Update source overview to only show mapping info for manual mapping
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/overview.tsx
Labels: bug

#2999 Fix flakey `modelCache` tests
  core/__tests__/models/app/modelCache.ts
  core/__tests__/models/destination/modelCache.ts
  core/__tests__/models/model/modelCache.ts
  core/__tests__/models/property/modelCache.ts
  core/__tests__/models/source/modelCache.ts
  core/src/modules/caches/appsCache.ts
  core/src/modules/caches/destinationsCache.ts
  core/src/modules/caches/modelsCache.ts
  core/src/modules/caches/propertiesCache.ts
  core/src/modules/caches/sourcesCache.ts
  core/src/modules/modelCache.ts
Labels: internal

#3003 Cleaning up old mappings now happens more aggressively
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
Labels: bug

#3004 Put email regex back to old, fixed tests
  core/__tests__/models/recordProperty/recordProperty.ts
  core/src/modules/validators/isEmail.ts
Labels: internal

#3002 chore: replace list by typeahead.
  plugins/@grouparoo/hubspot/__tests__/export-contacts/destination-options.ts
  plugins/@grouparoo/hubspot/__tests__/fixtures/export-contacts/destination-options.js
  plugins/@grouparoo/hubspot/__tests__/fixtures/integration/hubspot-export.js
  plugins/@grouparoo/hubspot/__tests__/integration/hubspot-export.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export/options.ts
Labels: bug, plugin

#2988 Validate source mappings and option values for lists / typeaheads
  core/__tests__/actions/appRefreshQuery.ts
  core/__tests__/actions/apps.ts
  core/__tests__/actions/destinations.ts
  core/__tests__/actions/properties.ts
  core/__tests__/actions/runs.ts
  core/__tests__/actions/schedules.ts
  core/__tests__/actions/sources/sources.ts
  core/__tests__/integration/happyPath.ts
  core/__tests__/integration/multipleModels.ts
  core/__tests__/integration/runs/internalRun.ts
  core/__tests__/models/app/app.ts
  core/__tests__/models/destination/destination.ts
  core/__tests__/models/destination/modelCache.ts
  core/__tests__/models/destination/plugins/destinationMappingOptions.ts
  core/__tests__/models/destination/plugins/exportRecord.ts
  core/__tests__/models/destination/plugins/exportRecords.ts
  core/__tests__/models/destination/plugins/processExportedProfiles.ts
  core/__tests__/models/mapping.ts
  core/__tests__/models/option.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/record/record.ts
  core/__tests__/models/recordProperty/recordProperty.ts
  core/__tests__/models/run/run.ts
  core/__tests__/models/schedule.ts
  core/__tests__/models/source/modelCache.ts
  core/__tests__/models/source/source.ts
  core/__tests__/modules/configWriter.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/record/export.ts
  core/__tests__/tasks/schedule/run.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Source.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/mappingHelper.ts
  core/src/modules/ops/source.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/getRowCount.js
  plugins/@grouparoo/bigquery/__tests__/fixtures/table-import/importRecords.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/importRecords.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/import/importRecords.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/integration/mailchimpExportContacts.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/integration/mailchimpExportContactsById.js
  plugins/@grouparoo/mailchimp/__tests__/fixtures/integration/mailchimpImport.js
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimpImport.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/query-import/importRecords.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/getRowCount.js
  plugins/@grouparoo/snowflake/__tests__/fixtures/table-import/importRecords.js
  plugins/@grouparoo/snowflake/__tests__/table-import/getRowCount.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/properties.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/schedule.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  plugins/@grouparoo/spec-helper/src/lib/testPluginData.ts
Labels: enhancement

#3000 Can Export Preview Record
  core/src/actions/destinations.ts
  ui/ui-components/__tests__/components/record/SampleRecordCard.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/pages/model/[modelId]/record/[recordId]/edit.tsx
  ui/ui-components/utils/apiData.ts
Labels: bug, enhancement

#3011 fix(hubspot): don't modify the options object when getting destination options
  core/__tests__/models/option.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/hubspot/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/hubspot/src/lib/export/options.ts
Labels: bug

#3007 `recordProperties:enqueue` does not need to sort
  core/__tests__/tasks/recordProperty/enqueue/grouppedAggregations.ts
  core/src/modules/ops/recordProperty.ts
Labels: enhancement

#2959 Create Freshdesk plugin with destinations for contacts and companies
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/freshdesk/.npmignore
  plugins/@grouparoo/freshdesk/LICENSE.txt
  plugins/@grouparoo/freshdesk/README.md
  plugins/@grouparoo/freshdesk/__tests__/.env.example
  plugins/@grouparoo/freshdesk/__tests__/export-companies/destination-mapping-options.ts
  plugins/@grouparoo/freshdesk/__tests__/export-companies/export-record.ts
  plugins/@grouparoo/freshdesk/__tests__/export-contacts/destination-mapping-options.ts
  plugins/@grouparoo/freshdesk/__tests__/export-contacts/export-record.ts
  plugins/@grouparoo/freshdesk/__tests__/fixtures/export-companies/destination-mapping-options.js
  plugins/@grouparoo/freshdesk/__tests__/fixtures/export-companies/export-record.js
  plugins/@grouparoo/freshdesk/__tests__/fixtures/export-contacts/destination-mapping-options.js
  plugins/@grouparoo/freshdesk/__tests__/fixtures/export-contacts/export-record.js
  plugins/@grouparoo/freshdesk/__tests__/utils/companyUtils.ts
  plugins/@grouparoo/freshdesk/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/freshdesk/__tests__/utils/shared.ts
  plugins/@grouparoo/freshdesk/jest.config.js
  plugins/@grouparoo/freshdesk/jest.setup.js
  plugins/@grouparoo/freshdesk/package.json
  plugins/@grouparoo/freshdesk/public/@grouparoo/freshdesk/freshdesk.png
  plugins/@grouparoo/freshdesk/src/initializers/plugin.ts
  plugins/@grouparoo/freshdesk/src/lib/client.ts
  plugins/@grouparoo/freshdesk/src/lib/common/destinationMappingOptions.ts
  plugins/@grouparoo/freshdesk/src/lib/common/exportArrayProperties.ts
  plugins/@grouparoo/freshdesk/src/lib/common/exportRecord.ts
  plugins/@grouparoo/freshdesk/src/lib/connect.ts
  plugins/@grouparoo/freshdesk/src/lib/disconnect.ts
  plugins/@grouparoo/freshdesk/src/lib/export-companies/destinationMappingOptions.ts
  plugins/@grouparoo/freshdesk/src/lib/export-companies/destinationOptions.ts
  plugins/@grouparoo/freshdesk/src/lib/export-companies/exportRecord.ts
  plugins/@grouparoo/freshdesk/src/lib/export-contacts/companyMethods.ts
  plugins/@grouparoo/freshdesk/src/lib/export-contacts/destinationMappingOptions.ts
  plugins/@grouparoo/freshdesk/src/lib/export-contacts/destinationOptions.ts
  plugins/@grouparoo/freshdesk/src/lib/export-contacts/exportRecord.ts
  plugins/@grouparoo/freshdesk/src/lib/test.ts
  plugins/@grouparoo/freshdesk/tsconfig.json
Labels: plugin
