Repository grouparoo/grouparoo, pull requests merged in 2022-03, with the labels that each got.

#3057 `axios` version in `@grouparoo/freshdesk` needs to match
  plugins/@grouparoo/freshdesk/package.json
Labels: dependencies

#3063 update `sequelize` and `sequelize-typescript`
  core/package.json
  core/src/modules/ops/export.ts
  core/src/modules/ops/exportProcessor.ts
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/closeio/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/freshdesk/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/klaviyo/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/vero/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: dependencies

#3069 Fix column overlap on Multiple Properties page
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
Labels: bug

#2968 Associate Import and Create Exports in Batches
  core/__tests__/actions/records/records.ts
  core/__tests__/initializers/resque.ts
  core/__tests__/integration/runs/internalRun.ts
  core/__tests__/models/destination/plugins/exportRecord.ts
  core/__tests__/models/import.ts
  core/__tests__/models/record/record.ts
  core/__tests__/models/record/snapshot-testing.ts
  core/__tests__/modules/plugin.ts
  core/__tests__/modules/reset.ts
  core/__tests__/tasks/destination/destroy.ts
  core/__tests__/tasks/export/send.ts
  core/__tests__/tasks/export/sendBatch.ts
  core/__tests__/tasks/import/associateRecord.ts
  core/__tests__/tasks/import/associateRecords.ts
  core/__tests__/tasks/record/export.ts
  core/__tests__/tasks/record/makeExports/makeExports.ts
  core/__tests__/tasks/record/makeReady/makeReady.ts
  core/__tests__/tasks/record/makeReady/smallerBatchSize.ts
  core/__tests__/tasks/record/reEnqueueStuckExportingRecords.ts
  core/__tests__/tasks/recordProperty/enqueue/enqueue.ts
  core/__tests__/tasks/recordProperty/enqueue/smallerBatchSize.ts
  core/__tests__/tasks/recordProperty/importRecordProperty.ts
  core/src/config/sequelize.ts
  core/src/index.ts
  core/src/models/Destination.ts
  core/src/models/GrouparooRecord.ts
  core/src/models/Import.ts
  core/src/models/Run.ts
  core/src/modules/ops/destination.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/import.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/recordProperty.ts
  core/src/modules/plugin.ts
  core/src/tasks/import/associateRecord.ts
  core/src/tasks/import/associateRecords.ts
  core/src/tasks/record/export.ts
  core/src/tasks/record/makeReady.ts
  core/src/tasks/record/reEnqueueStuckExportingRecords.ts
  plugins/@grouparoo/clickhouse/__tests__/integration/clickhouseTableImport.ts
  plugins/@grouparoo/csv/__tests__/integration/csvRemote.ts
  plugins/@grouparoo/google-sheets/__tests__/integration/googleSheetsImport.ts
  plugins/@grouparoo/mailchimp/__tests__/integration/mailchimpImport.ts
  plugins/@grouparoo/mysql/__tests__/integration/mysqlTableImport.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgresTableImport.ts
  plugins/@grouparoo/redshift/__tests__/integration/redshiftTableImport.ts
  plugins/@grouparoo/sentry/src/initializers/sentry.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/properties.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/record.ts
  plugins/@grouparoo/spec-helper/src/lib/workflows/import.ts
  plugins/@grouparoo/sqlite/__tests__/integration/sqliteTableImport.ts
Labels: enhancement

#3070 [FIX] Assigning Record to Export upon send
  core/src/modules/ops/destination.ts
  plugins/@grouparoo/logger/__tests__/integration/exportRecords.ts
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/logger/src/lib/export/exportRecords.ts
  pnpm-lock.yaml
Labels: bug

#3012 Consolidated unique key/name method
  core/__tests__/integration/errors.ts
  core/__tests__/models/apiKey.ts
  core/__tests__/models/group/group.ts
  core/__tests__/models/mapping.ts
  core/__tests__/models/model/grouparooModel.ts
  core/__tests__/models/team.ts
  core/__tests__/modules/mappingHelper.ts
  core/bin/dev
  core/src/classes/commonModel.ts
  core/src/config/errors.ts
  core/src/models/App.ts
  core/src/models/Destination.ts
  core/src/models/DestinationGroupMembership.ts
  core/src/models/Filter.ts
  core/src/models/Group.ts
  core/src/models/GroupMember.ts
  core/src/models/Mapping.ts
  core/src/models/Option.ts
  core/src/models/Permission.ts
  core/src/models/Property.ts
  core/src/models/Schedule.ts
  core/src/models/Setting.ts
  core/src/models/Source.ts
  core/src/modules/errors.ts
  core/src/modules/ops/source.ts
Labels: enhancement, internal

#3078 Improve CI so PR's build. Fix build.
  core/src/classes/commonModel.ts
  core/src/utils/types.ts
  tools/merger/lockfile
Labels: bug, enhancement

#3058 Replace text by binds on all queries
  plugins/@grouparoo/snowflake/__tests__/export/export-records.ts
  plugins/@grouparoo/snowflake/__tests__/fixtures/export/export-records.js
  plugins/@grouparoo/snowflake/__tests__/utils/data.ts
  plugins/@grouparoo/snowflake/src/lib/export/exportRecords.ts
Labels: bug, plugin

#3071 Destination Sample Record Card exports and updates precisely
  core/src/actions/destinations.ts
  ui/ui-components/__tests__/components/record/SampleRecordCard.tsx
  ui/ui-components/__tests__/components/record/__snapshots__/SampleRecordCard.tsx.snap
  ui/ui-components/components/destination/DestinationSampleRecord.tsx
  ui/ui-components/components/record/AddSampleRecordForm.tsx
  ui/ui-components/components/record/AddSampleRecordModal.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/data.tsx
Labels: bug

#3086 clear `completedAt` when retrying exports
  core/__tests__/models/export.ts
  core/src/modules/ops/export.ts
Labels: bug

#3085 Source now only uses name for a unique composite key.
  core/__tests__/models/source/source.ts
  core/src/models/Source.ts
Labels: bug, enhancement

#3084 Fix Import association when multiple Models share the same primary key values
  core/__tests__/tasks/import/associateRecords.ts
  core/src/modules/ops/record.ts
Labels: bug

#3091 Fix schedule run value in Source overview and schedule pages
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
Labels: bug

#3090 Disable telemetry and oAuth by default
  core/src/actions/oAuth.ts
  core/src/config/oAuth.ts
  core/src/config/telemetry.ts
  plugins/@grouparoo/spec-helper/src/lib/environment.ts
Labels: enhancement

#3092 Fix source edit page preview so that it always updates when source options change
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug
