Repository grouparoo/grouparoo, pull requests merged in 2022-01, with the labels that each got.

#2745 Next auto generation changes these files
  ui/ui-community/next-env.d.ts
  ui/ui-config/next-env.d.ts
  ui/ui-enterprise/next-env.d.ts
Labels: internal

#2742 Simpler Devcontainer Setup
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/setup.sh
Labels: internal

#2758 Lock `@types/node` to v16.x (also fixes mongo)
  cli/package.json
  core/package.json
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#2757 Replace outdated README url `docs/plugins` with `docs/integrations`
  plugins/@grouparoo/airtable/README.md
  plugins/@grouparoo/bigquery/README.md
  plugins/@grouparoo/braze/README.md
  plugins/@grouparoo/calculated-property/README.md
  plugins/@grouparoo/clickhouse/README.md
  plugins/@grouparoo/cloudwatch/README.md
  plugins/@grouparoo/csv/README.md
  plugins/@grouparoo/customerio/README.md
  plugins/@grouparoo/dbt/README.md
  plugins/@grouparoo/eloqua/README.md
  plugins/@grouparoo/facebook/README.md
  plugins/@grouparoo/google-sheets/README.md
  plugins/@grouparoo/hubspot/README.md
  plugins/@grouparoo/intercom/README.md
  plugins/@grouparoo/iterable/README.md
  plugins/@grouparoo/logger/README.md
  plugins/@grouparoo/mailchimp/README.md
  plugins/@grouparoo/mailjet/README.md
  plugins/@grouparoo/marketo/README.md
  plugins/@grouparoo/mixpanel/README.md
  plugins/@grouparoo/mongo/README.md
  plugins/@grouparoo/mysql/README.md
  plugins/@grouparoo/newrelic/README.md
  plugins/@grouparoo/onesignal/README.md
  plugins/@grouparoo/pardot/README.md
  plugins/@grouparoo/pipedrive/README.md
  plugins/@grouparoo/postgres/README.md
  plugins/@grouparoo/prometheus/README.md
  plugins/@grouparoo/redshift/README.md
  plugins/@grouparoo/sailthru/README.md
  plugins/@grouparoo/salesforce/README.md
  plugins/@grouparoo/sendgrid/README.md
  plugins/@grouparoo/sentry/README.md
  plugins/@grouparoo/snowflake/README.md
  plugins/@grouparoo/sqlite/README.md
  plugins/@grouparoo/zendesk/README.md
  ui/ui-community/README.md
  ui/ui-config/README.md
  ui/ui-enterprise/README.md
Labels: bug, documentation

#2751 Add states to Imports
  core/__tests__/actions/imports.ts
  core/__tests__/models/import.ts
  core/__tests__/models/run/run.ts
  core/__tests__/modules/status.ts
  core/__tests__/tasks/import/associateRecord.ts
  core/__tests__/tasks/import/associateRecords.ts
  core/__tests__/tasks/record/checkReady/checkReady.ts
  core/__tests__/tasks/record/confirm/confirm.ts
  core/__tests__/tasks/record/enqueueExports/enqueueExports.ts
  core/__tests__/tasks/record/enqueueExports/smallerBatchSize.ts
  core/__tests__/tasks/record/export.ts
  core/__tests__/tasks/system/status/status.ts
  core/src/actions/imports.ts
  core/src/migrations/000097-addStateToImports.ts
  core/src/models/Import.ts
  core/src/modules/ops/group.ts
  core/src/modules/ops/import.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/runs.ts
  core/src/modules/statusReporters.ts
  core/src/tasks/group/run.ts
  core/src/tasks/grouparooModel/run.ts
  core/src/tasks/record/confirm.ts
  core/src/tasks/record/enqueueExports.ts
  core/src/tasks/record/export.ts
  core/src/tasks/run/internalRun.ts
  plugins/@grouparoo/spec-helper/src/lib/factories/import.ts
  ui/ui-components/components/import/Diff.tsx
  ui/ui-components/components/import/List.tsx
  ui/ui-components/pages/import/[id]/edit.tsx
Labels: enhancement

#2752 Fixing Snowflake Connection Missing Error w/ Multiple Workers
  .circleci/config.yml
  core/__tests__/ops/app.ts
  core/src/initializers/plugins.ts
  core/src/modules/ops/app.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
Labels: bug

#2760 add ui edition to preview record localstorage token
  ui/ui-components/components/record/SampleRecordCard.tsx
Labels: bug

#2762 Schedule Filters UI cleanup
  ui/ui-components/pages/model/[modelId]/property/[propertyId]/edit.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
Labels: bug

#2765 Add plugin to support Rollbar error reporting
  plugins/@grouparoo/rollbar/.npmignore
  plugins/@grouparoo/rollbar/LICENSE.txt
  plugins/@grouparoo/rollbar/README.md
  plugins/@grouparoo/rollbar/jest.config.js
  plugins/@grouparoo/rollbar/jest.setup.js
  plugins/@grouparoo/rollbar/package.json
  plugins/@grouparoo/rollbar/src/initializers/rollbar.ts
  plugins/@grouparoo/rollbar/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, plugin

#2768 Check & Fix package versions with Syncpack
  .circleci/config.yml
  .syncpackrc.json
  package.json
  plugins/@grouparoo/airtable/package.json
  pnpm-lock.yaml
  tools/merger/src/ci_generate.js
  tools/version-checker/check
  tools/version-checker/fix
Labels: internal

#2773 Model-centric Setup Steps
  core/__tests__/actions/setupSteps.ts
  core/__tests__/models/setupStep.ts
  core/bin/dev
  core/src/initializers/setupSteps.ts
  core/src/models/SetupStep.ts
  core/src/modules/ops/setupSteps.ts
Labels: enhancement

#2774 Rename Import `exporting` state to `processing`
  core/__tests__/models/run/run.ts
  core/__tests__/tasks/record/checkReady/checkReady.ts
  core/__tests__/tasks/record/enqueueExports/enqueueExports.ts
  core/__tests__/tasks/record/enqueueExports/smallerBatchSize.ts
  core/__tests__/tasks/record/export.ts
  core/__tests__/tasks/system/status/status.ts
  core/src/migrations/000098-renameImportStateExportingToProcessing.ts
  core/src/models/Import.ts
  core/src/modules/ops/record.ts
  core/src/modules/ops/runs.ts
  core/src/tasks/record/enqueueExports.ts
  core/src/tasks/record/export.ts
  ui/ui-components/components/import/List.tsx
  ui/ui-components/pages/import/[id]/edit.tsx
Labels: enhancement

#2769 Set Google-Sheets reading rows limits
  plugins/@grouparoo/google-sheets/__tests__/fixtures/integration/google-sheets-import.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/downloadAndRefreshFile.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/propertyOptions.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/recordProperties.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/recordProperty.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/records.js
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/Spreadsheet.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/downloadAndRefreshFile.ts
Labels: bug, plugin

#2665 Create Klaviyo Plugin
  .circleci/config.yml
  apps/staging-community/package.json
  apps/staging-enterprise/package.json
  plugins/@grouparoo/klaviyo/.npmignore
  plugins/@grouparoo/klaviyo/LICENSE.txt
  plugins/@grouparoo/klaviyo/README.md
  plugins/@grouparoo/klaviyo/__tests__/.env.example
  plugins/@grouparoo/klaviyo/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/klaviyo/__tests__/export/export-record.ts
  plugins/@grouparoo/klaviyo/__tests__/fixtures/export/destination-mapping-options.js
  plugins/@grouparoo/klaviyo/__tests__/fixtures/export/export-record.js
  plugins/@grouparoo/klaviyo/__tests__/integration/cli-generate-validate.ts
  plugins/@grouparoo/klaviyo/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/klaviyo/__tests__/utils/shared.ts
  plugins/@grouparoo/klaviyo/jest.config.js
  plugins/@grouparoo/klaviyo/jest.setup.js
  plugins/@grouparoo/klaviyo/package.json
  plugins/@grouparoo/klaviyo/public/@grouparoo/klaviyo/klaviyo.png
  plugins/@grouparoo/klaviyo/public/templates/app/{{{id}}}.js.template
  plugins/@grouparoo/klaviyo/public/templates/destination/{{{id}}}.js.template
  plugins/@grouparoo/klaviyo/src/initializers/plugin.ts
  plugins/@grouparoo/klaviyo/src/lib/client.ts
  plugins/@grouparoo/klaviyo/src/lib/connect.ts
  plugins/@grouparoo/klaviyo/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/klaviyo/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/klaviyo/src/lib/export/exportArrayProperties.ts
  plugins/@grouparoo/klaviyo/src/lib/export/exportRecord.ts
  plugins/@grouparoo/klaviyo/src/lib/export/listMethods.ts
  plugins/@grouparoo/klaviyo/src/lib/test.ts
  plugins/@grouparoo/klaviyo/tsconfig.json
Labels: enhancement

#2776 Add Bluebird to UI-Config to fix plugin-install crashing issue
  pnpm-lock.yaml
  ui/ui-config/package.json
Labels: bug

#2775 Config UI Plugin Install Fixed
  core/package.json
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/rollbar/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/vero/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: bug, dependencies

#2766 Mark records and recordProps as `pending` when a property type changes
  core/__tests__/models/property/property.ts
  core/src/models/Property.ts
Labels: enhancement

#2780 `main` Merge Fixes
  core/src/actions/sources.ts
  plugins/@grouparoo/klaviyo/package.json
  pnpm-lock.yaml
Labels: bug

#2761 Include non required fields into known when in enrich mode.
  plugins/@grouparoo/salesforce/__tests__/export-account/destination-mapping-options-enrich.ts
  plugins/@grouparoo/salesforce/__tests__/export-account/destination-mapping-options.ts
  plugins/@grouparoo/salesforce/__tests__/export-contacts/destination-mapping-options-enrich.ts
  plugins/@grouparoo/salesforce/__tests__/export-objects/destination-mapping-options-enrich.ts
  plugins/@grouparoo/salesforce/__tests__/fixtures/export-account/destination-mapping-options-enrich.js
  plugins/@grouparoo/salesforce/__tests__/fixtures/export-account/destination-mapping-options.js
  plugins/@grouparoo/salesforce/__tests__/fixtures/export-contacts/destination-mapping-options-enrich.js
  plugins/@grouparoo/salesforce/__tests__/fixtures/export-objects/destination-mapping-options-enrich.js
  plugins/@grouparoo/salesforce/jest.config.js
  plugins/@grouparoo/salesforce/src/lib/export/mapping.ts
Labels: bug, plugin

#2782 Order SetupSteps so Apps > Models
  core/__tests__/models/setupStep.ts
  core/src/modules/ops/setupSteps.ts
Labels: enhancement

#2779 Generate Sample Records when the primary Source goes ready in ui-config
  core/__tests__/actions/sources/generateSampleRecords.ts
  core/__tests__/actions/sources/sources.ts
  core/__tests__/actions/status.ts
  core/src/actions/sources.ts
  core/src/config/routes.ts
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
  ui/ui-components/utils/apiData.ts
Labels: enhancement

#2786 Update logos for Klaviyo and Vero
  plugins/@grouparoo/klaviyo/README.md
  plugins/@grouparoo/klaviyo/public/@grouparoo/klaviyo/klaviyo.png
  plugins/@grouparoo/vero/README.md
  plugins/@grouparoo/vero/public/@grouparoo/vero/vero.png
Labels: enhancement

#2787 Fix sample record generation bug and bootstrap issue in non-boostrappable sources in source edit page
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug

#2770 Primary Source creation UI bug fixes
  ui/ui-components/components/source/FormMappingSelector.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug

#2781 Update `uzmug`, `ah-sequelize-plugin` and `sequelize-typescript` packages
  core/package.json
  core/src/models/Property.ts
  pnpm-lock.yaml
Labels: dependencies

#2790 Group Rules page bug fix
  ui/ui-components/pages/model/[modelId]/group/[groupId]/rules.tsx
Labels: bug

#2791 Model Summary View Updates
  ui/ui-components/__tests__/components/record/SampleRecordCard.tsx
  ui/ui-components/__tests__/components/record/__snapshots__/SampleRecordCard.tsx.snap
  ui/ui-components/components/record/SampleRecordCard.tsx
Labels: enhancement

#2794 Add prefix to always download a new file
  plugins/@grouparoo/google-sheets/__tests__/fixtures/integration/google-sheets-import.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/downloadAndRefreshFile.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/propertyOptions.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/recordProperties.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/recordProperty.js
  plugins/@grouparoo/google-sheets/__tests__/fixtures/remote-import/records.js
  plugins/@grouparoo/google-sheets/__tests__/remote-import/downloadAndRefreshFile.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/Spreadsheet.ts
  plugins/@grouparoo/google-sheets/src/lib/sheet-import/downloadAndRefreshFile.ts
Labels: bug, plugin

#2795 Fix klaviyo fields, names and rate limiting issues
  plugins/@grouparoo/klaviyo/src/initializers/plugin.ts
  plugins/@grouparoo/klaviyo/src/lib/client.ts
  plugins/@grouparoo/klaviyo/src/lib/export/destinationMappingOptions.ts
  plugins/@grouparoo/klaviyo/src/lib/export/exportRecord.ts
Labels: enhancement

#2803 Only run redshift tests when using repo directly (no forks)
  .circleci/config.yml
  tools/merger/data/ci/plugin/job.yml.template
  tools/merger/data/ci/plugin/redshift/test.yml.template
Labels: internal

#2797 add button on model overview page schedules to "Run Now"
  ui/ui-components/components/model/overview/ModelOverviewSchedules.tsx
Labels: enhancement

#2805 GROUPAROO_RUN_MODE Bugs
  cli/src/utils/loadLocalCommands.ts
  core/__tests__/actions/config.ts
  core/__tests__/actions/navigation.ts
  core/__tests__/actions/sources/generateSampleRecords.ts
  core/__tests__/actions/status.ts
  core/__tests__/initializers/environment.ts
  core/__tests__/models/group/calculations.ts
  core/__tests__/models/group/group.ts
  core/__tests__/models/property/property.ts
  core/__tests__/models/setupStep.ts
  core/__tests__/modules/codeConfig/codeConfig.ts
  core/__tests__/modules/configUser.ts
  core/__tests__/modules/configWriter.ts
  core/__tests__/modules/status.ts
  core/__tests__/modules/telemetry.ts
  core/__tests__/tasks/system/status/status.ts
  core/src/actions/config.ts
  core/src/actions/navigation.ts
  core/src/actions/sources.ts
  core/src/bin/run.ts
  core/src/config/api.ts
  core/src/initializers/codeConfig.ts
  core/src/initializers/plugins.ts
  core/src/initializers/telemetry.ts
  core/src/models/Group.ts
  core/src/models/Property.ts
  core/src/modules/configLoaders/record.ts
  core/src/modules/configUser.ts
  core/src/modules/configWriter.ts
  core/src/modules/middleware/authentication.ts
  core/src/modules/ops/property.ts
  core/src/modules/ops/runs.ts
  core/src/modules/ops/setupSteps.ts
  core/src/modules/runMode.ts
  core/src/tasks/appRefreshQuery/check.ts
  core/src/tasks/group/updateCalculatedGroups.ts
  core/src/tasks/run/recurringInternalRun.ts
  core/src/tasks/schedule/enqueueRuns.ts
  core/src/tasks/system/status/status.ts
  core/src/tasks/system/telemetry/telemetry.ts
  ui/ui-config/dist/bin/config.js
Labels: bug

#2789 Mailchimp OAuth App
  core/__tests__/actions/apps.ts
  core/__tests__/actions/oAuth.ts
  core/__tests__/fixtures/actions/oAuth.js
  core/__tests__/models/app/app.ts
  core/__tests__/models/option.ts
  core/src/actions/oAuth.ts
  core/src/classes/plugin.ts
  core/src/config/tasks.ts
  core/src/models/App.ts
  core/src/models/OAuthRequest.ts
  core/src/modules/ops/app.ts
  core/src/modules/optionHelper.ts
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/mailchimp/__tests__/.env.example
  plugins/@grouparoo/mailchimp/__tests__/fixtures/test.js
  plugins/@grouparoo/mailchimp/__tests__/test.ts
  plugins/@grouparoo/mailchimp/__tests__/utils/nockHelper.ts
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailchimp/src/initializers/plugin.ts
  plugins/@grouparoo/mailchimp/src/lib/connect.ts
  plugins/@grouparoo/mailchimp/src/lib/export-id/connection.ts
  plugins/@grouparoo/mailchimp/src/lib/export/connection.ts
  plugins/@grouparoo/mailchimp/src/lib/import/connection.ts
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  pnpm-lock.yaml
  ui/ui-components/components/session/SignIn.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/oauth/callback.tsx
Labels: enhancement

#2809 Update ah-sequelize-plugin (fix migraton name bugs)
  core/bin/migrator
  core/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#2801 Create an InternalRun when Property Type changes
  core/__tests__/models/property/property.ts
  core/__tests__/tasks/run/internalRun.ts
  core/src/models/Property.ts
  core/src/modules/internalRun.ts
  core/src/modules/ops/property.ts
  core/src/tasks/run/internalRun.ts
Labels: enhancement

#2807 Mailchimp OAuth works in config mode
  plugins/@grouparoo/mailchimp/src/lib/connect.ts
  ui/ui-components/pages/app/[id]/edit.tsx
  ui/ui-components/pages/oauth/callback.tsx
  ui/ui-config/pages/oauth/callback.tsx
Labels: bug

#2811 fix: debounce loading destination options on change
  ui/ui-components/hooks/useDebouncedCallback.ts
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/edit.tsx
Labels: bug

#2808 After group deletion, redirect to the model overview page
  ui/ui-components/pages/model/[modelId]/group/[groupId]/edit.tsx
Labels: bug

#2812 Fix method signature for trackAnonymous in customer.io plugin
  plugins/@grouparoo/customerio/__tests__/fixtures/test.js
  plugins/@grouparoo/customerio/__tests__/test.ts
  plugins/@grouparoo/customerio/src/lib/client.ts
  plugins/@grouparoo/customerio/src/lib/test.ts
Labels: bug

#2813 Ensure that schedule created from UI is set to recurring
  ui/ui-components/components/schedule/Add.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: enhancement

#2814 fix: disconnect app after options changed
  core/__tests__/models/app/app.ts
  core/src/models/App.ts
  core/src/modules/optionHelper.ts
Labels: bug

#2816 bump options debounce to 1000ms
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/edit.tsx
Labels: bug

#2815 Nav Item Highlighting
  ui/ui-components/__tests__/components/navigation.tsx
  ui/ui-components/components/Navigation.tsx
  ui/ui-components/components/navigation/HighlightingNavLink.tsx
Labels: bug

#2711 Improve patterns on accessing web app props and event handlers
  ui/ui-community/pages/account.tsx
  ui/ui-community/pages/apps.tsx
  ui/ui-community/pages/models.tsx
  ui/ui-components/__tests__/components/navigation.tsx
  ui/ui-components/components/ComponentInjection.tsx
  ui/ui-components/components/Navigation.tsx
  ui/ui-components/components/layouts/Main.tsx
  ui/ui-components/components/model/overview/ModelOverviewSchedules.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
  ui/ui-components/components/schedule/RunAllSchedulesButton.tsx
  ui/ui-components/contexts/webApp.tsx
  ui/ui-components/eventHandlers/index.ts
  ui/ui-components/hooks/useApi.ts
  ui/ui-components/pages/_app.tsx
  ui/ui-components/pages/account.tsx
  ui/ui-components/pages/apps.tsx
  ui/ui-components/pages/models.tsx
  ui/ui-components/utils/contextHelper.tsx
  ui/ui-components/utils/eventHandlers.ts
  ui/ui-components/utils/pageHelper.ts
  ui/ui-config/pages/apps.tsx
  ui/ui-config/pages/models.tsx
  ui/ui-enterprise/pages/account.tsx
  ui/ui-enterprise/pages/apps.tsx
  ui/ui-enterprise/pages/models.tsx
Labels: internal

#2820 `@grouparoo/core` should not be a dependency of airtable
  plugins/@grouparoo/airtable/package.json
  pnpm-lock.yaml
Labels: bug, internal

#2798 Suggest an available key on the multiple props page
  core/__tests__/actions/sources/sources.ts
  core/src/actions/sources.ts
  core/src/modules/tableSpeculation.ts
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
Labels: enhancement

#2817 Use `GROUPAROO_INTERNAL_BATCH_SIZE` to configure `config.batchSize.recordProperties`
  core/__tests__/tasks/recordProperty/enqueue/smallerBatchSize.ts
  core/src/config/batchSize.ts
  documents/environment-variables.md
Labels: enhancement

#2824 Navbar updates on model name edit
  ui/ui-components/pages/model/[modelId]/edit.tsx
Labels: enhancement

#2829 destination handler import fix
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/edit.tsx
Labels: bug

#2822 Remove records count in model overview for config UI
  ui/ui-components/components/model/overview/ModelOverviewGroups.tsx
Labels: bug

#2823 Ensure that source edit page is not updated when redirecting to the schedule page
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
Labels: bug

#2828 Fix issues with updating recurring schedule
  core/__tests__/actions/schedules.ts
  core/src/actions/schedules.ts
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
  ui/ui-components/utils/makeLocal.ts
Labels: bug

#2837 Navigation Link Styling
  ui/ui-components/components/Navigation.tsx
Labels: bug

#2830 fix: generate unique ids when creating properties
  core/__tests__/models/source/source.ts
  core/__tests__/tasks/system/destroy.ts
  core/src/modules/ops/source.ts
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
Labels: bug

#2833 Setup Steps Text Cleaned Up
  core/src/modules/ops/setupSteps.ts
Labels: documentation

#2838 Ensure that property keys are unique regardless of case
  core/__tests__/models/property/property.ts
  core/src/models/Property.ts
Labels: bug

#2835 Breadcrumbs update as expected when renaming things
  ui/ui-components/components/Tabs.tsx
Labels: bug

#2844 Enable `noImplicitAny` for `@grouparoo/dbt`
  plugins/@grouparoo/dbt/__tests__/settings/parse.ts
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/dbt/src/settings/command.ts
  plugins/@grouparoo/dbt/src/settings/parse.ts
  plugins/@grouparoo/dbt/src/utils/exec.ts
  plugins/@grouparoo/dbt/tsconfig.json
  pnpm-lock.yaml
Labels: internal

#2834 View All Records button specifies how many records
  ui/ui-components/__tests__/components/record/__snapshots__/SampleRecordCard.tsx.snap
  ui/ui-components/components/record/SampleRecordCard.tsx
Labels: enhancement

#2836 update app header on name change
  ui/ui-components/components/tabs/App.tsx
  ui/ui-components/pages/app/[id]/edit.tsx
Labels: bug

#2847 Test fix - now use GROUPAROO_RECORDS_BATCH_SIZE
  core/__tests__/tasks/recordProperty/enqueue/grouppedAggregations.ts
Labels: internal

#2839 fix: only do one redirect after schedule creation
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/schedule.tsx
Labels: bug

#2845 Fix missing await and imports
  core/src/index.ts
  core/src/models/Schedule.ts
  core/src/modules/configLoaders/apiKey.ts
  core/src/modules/configLoaders/app.ts
  core/src/modules/configLoaders/destination.ts
  core/src/modules/configLoaders/group.ts
  core/src/modules/configLoaders/index.ts
  core/src/modules/configLoaders/model.ts
  core/src/modules/configLoaders/property.ts
  core/src/modules/configLoaders/record.ts
  core/src/modules/configLoaders/schedule.ts
  core/src/modules/configLoaders/setting.ts
  core/src/modules/configLoaders/source.ts
  core/src/modules/configLoaders/team.ts
  core/src/modules/configLoaders/teamMember.ts
Labels: bug

#2851 Loads record count on page load or model switch
  ui/ui-components/__tests__/components/record/__snapshots__/SampleRecordCard.tsx.snap
  ui/ui-components/components/record/SampleRecordCard.tsx
Labels: bug

#2832 Destination can fetch random record
  ui/ui-components/components/destination/DestinationSampleRecord.tsx
  ui/ui-components/components/record/SampleRecordCard.tsx
Labels: bug

#2848 SQLite Sample Rows no longer `ORDER BY RANDOM()`
  plugins/@grouparoo/sqlite/src/lib/table-import/getSampleRows.ts
Labels: bug, internal

#2849 Add missing await in recordProperty test
  core/__tests__/models/recordProperty/recordProperty.ts
Labels: internal

#2855 Upgrade to node-resque@9.1.4
  core/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#2825 Retry failed exports within a time range
  core/__tests__/models/export.ts
  core/src/actions/exports.ts
  core/src/config/routes.ts
  core/src/models/Export.ts
  core/src/modules/ops/export.ts
  ui/ui-community/pages/model/[modelId]/destination/[destinationId]/retry.tsx
  ui/ui-components/components/tabs/Destination.tsx
  ui/ui-components/pages/model/[modelId]/destination/[destinationId]/retry.tsx
  ui/ui-components/utils/apiData.ts
  ui/ui-enterprise/pages/model/[modelId]/destination/[destinationId]/retry.tsx
Labels: enhancement

#2854 Fix key input on multiple properties page
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/multipleProperties.tsx
Labels: bug

#2857 feat: `grouparoo run` can target specific schedules
  core/__tests__/tasks/schedule/enqueueRuns.ts
  core/src/bin/run.ts
  core/src/tasks/schedule/enqueueRuns.ts
Labels: enhancement

#2852 Fix recurring and refreshEnabled schedule update
  core/__tests__/actions/schedules.ts
  core/src/actions/schedules.ts
Labels: bug

#2850 Authentication via `Authorization` header
  core/__tests__/actions/session.ts
  core/src/modules/middleware/authentication.ts
Labels: enhancement

#2859 fix: apply group rules match type at the right level
  core/__tests__/models/group/calculations.ts
  core/src/models/Group.ts
Labels: bug

#2861 Add missing style to navigation link
  ui/ui-components/components/Navigation.tsx
  ui/ui-components/components/navigation/HighlightingNavLink.tsx
Labels: bug

#2867 Update `grouparoo init` success message
  cli/src/lib/initialize.ts
Labels: enhancement

#2862 `scheduleIds` param validation for `grouparoo run`
  core/__tests__/bin/run.ts
  core/__tests__/tasks/schedule/enqueueRuns.ts
  core/src/bin/run.ts
  core/src/tasks/schedule/enqueueRuns.ts
Labels: enhancement, breaking change

#2647 Add eslint and noImplicitAny to Postgres Plugin
  core/package.json
  core/src/classes/plugin.ts
  core/src/index.ts
  plugins/@grouparoo/app-templates/src/source/query/records.ts
  plugins/@grouparoo/app-templates/src/source/table/getFilterOperation.ts
  plugins/@grouparoo/app-templates/src/source/table/recordProperty.ts
  plugins/@grouparoo/postgres/.eslintrc.js
  plugins/@grouparoo/postgres/__tests__/export/destination-mapping-options.ts
  plugins/@grouparoo/postgres/__tests__/export/export-records.ts
  plugins/@grouparoo/postgres/__tests__/integration/app-refresh-query.ts
  plugins/@grouparoo/postgres/__tests__/integration/cli-generate-from.ts
  plugins/@grouparoo/postgres/__tests__/integration/log-checking.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-query-import.ts
  plugins/@grouparoo/postgres/__tests__/integration/postgres-table-import.ts
  plugins/@grouparoo/postgres/__tests__/query-import/getChangedRows.ts
  plugins/@grouparoo/postgres/__tests__/query-import/import-property.ts
  plugins/@grouparoo/postgres/__tests__/query-import/records.ts
  plugins/@grouparoo/postgres/__tests__/table-import/get-changed-row-count.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-properties.ts
  plugins/@grouparoo/postgres/__tests__/table-import/import-property.ts
  plugins/@grouparoo/postgres/__tests__/table-import/record-property-rule-options.ts
  plugins/@grouparoo/postgres/__tests__/table-import/records.ts
  plugins/@grouparoo/postgres/__tests__/table-import/schedule-options.ts
  plugins/@grouparoo/postgres/__tests__/table-import/source-filters.ts
  plugins/@grouparoo/postgres/__tests__/table-import/source-options.ts
  plugins/@grouparoo/postgres/__tests__/table-import/source-preview.ts
  plugins/@grouparoo/postgres/__tests__/utils/data.ts
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/postgres/src/initializers/plugin.ts
  plugins/@grouparoo/postgres/src/lib/connect.ts
  plugins/@grouparoo/postgres/src/lib/export/destinationOptions.ts
  plugins/@grouparoo/postgres/src/lib/export/exportRecord.ts
  plugins/@grouparoo/postgres/src/lib/query-import/executeQuery.ts
  plugins/@grouparoo/postgres/src/lib/query-import/getChangedRows.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getChangedRowCount.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getChangedRows.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getPropertyValue.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getPropertyValues.ts
  plugins/@grouparoo/postgres/src/lib/table-import/getSampleRows.ts
  plugins/@grouparoo/postgres/src/lib/table-import/util.ts
  plugins/@grouparoo/postgres/tsconfig.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
  pnpm-lock.yaml
Labels: enhancement, internal

#2874 Select from multiple apps after installing plugin from config UI
  ui/ui-config/pages/app/new/index.tsx
Labels: bug

#2869 Ensure that Property model is unique when it's also primary key
  core/__tests__/models/property/property.ts
  core/src/models/Property.ts
Labels: bug

#2872 Fix: UI Error Handling and Redirects
  core/src/modules/errors.ts
  ui/ui-community/pages/dashboard.tsx
  ui/ui-community/pages/setup.tsx
  ui/ui-components/client/client.ts
  ui/ui-components/components/navigation/SetupStepsNavProgressBar.tsx
  ui/ui-components/eventHandlers/index.ts
  ui/ui-components/eventHandlers/setupStepsHandler.ts
  ui/ui-components/pages/account.tsx
  ui/ui-components/pages/apps.tsx
  ui/ui-components/pages/dashboard.tsx
  ui/ui-components/pages/model/[modelId]/overview.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/edit.tsx
  ui/ui-components/pages/models.tsx
  ui/ui-components/pages/setup.tsx
  ui/ui-components/utils/withServerErrorHandler.ts
  ui/ui-config/pages/setup.tsx
  ui/ui-enterprise/pages/dashboard.tsx
  ui/ui-enterprise/pages/setup.tsx
Labels: bug

#2877 Fix disabled state for Unique checkbox in property editor
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/edit.tsx
Labels: bug

#2876 Display sign in link for older `getInitialProps` pages on auth error
  core/__tests__/actions/session.ts
  core/src/modules/middleware/authentication.ts
  ui/ui-components/components/alerts/HydrationError.tsx
  ui/ui-components/hooks/useRealtimeStream.ts
Labels: bug

#2879 fix: use `generateClient` in `getInitialProps`
  ui/ui-components/pages/model/[modelId]/group/new.tsx
  ui/ui-components/pages/model/[modelId]/source/[sourceId]/overview.tsx
  ui/ui-components/pages/notification/[id]/edit.tsx
  ui/ui-enterprise/pages/model/[modelId]/group/[groupId]/[plugin].tsx
  ui/ui-enterprise/pages/model/[modelId]/source/[sourceId]/property/[propertyId]/records.tsx
Labels: bug

#2878 update actionhero to `v28.1.7`
  core/package.json
  plugins/@grouparoo/airtable/package.json
  plugins/@grouparoo/app-templates/package.json
  plugins/@grouparoo/bigquery/package.json
  plugins/@grouparoo/braze/package.json
  plugins/@grouparoo/calculated-property/package.json
  plugins/@grouparoo/clickhouse/package.json
  plugins/@grouparoo/cloudwatch/package.json
  plugins/@grouparoo/csv/package.json
  plugins/@grouparoo/customerio/package.json
  plugins/@grouparoo/dbt/package.json
  plugins/@grouparoo/demo/package.json
  plugins/@grouparoo/eloqua/package.json
  plugins/@grouparoo/facebook/package.json
  plugins/@grouparoo/google-sheets/package.json
  plugins/@grouparoo/hubspot/package.json
  plugins/@grouparoo/intercom/package.json
  plugins/@grouparoo/iterable/package.json
  plugins/@grouparoo/klaviyo/package.json
  plugins/@grouparoo/logger/package.json
  plugins/@grouparoo/mailchimp/package.json
  plugins/@grouparoo/mailjet/package.json
  plugins/@grouparoo/marketo/package.json
  plugins/@grouparoo/mixpanel/package.json
  plugins/@grouparoo/mongo/package.json
  plugins/@grouparoo/mysql/package.json
  plugins/@grouparoo/newrelic/package.json
  plugins/@grouparoo/onesignal/package.json
  plugins/@grouparoo/pardot/package.json
  plugins/@grouparoo/pipedrive/package.json
  plugins/@grouparoo/postgres/package.json
  plugins/@grouparoo/prometheus/package.json
  plugins/@grouparoo/redshift/package.json
  plugins/@grouparoo/rollbar/package.json
  plugins/@grouparoo/sailthru/package.json
  plugins/@grouparoo/salesforce/package.json
  plugins/@grouparoo/sendgrid/package.json
  plugins/@grouparoo/sentry/package.json
  plugins/@grouparoo/snowflake/package.json
  plugins/@grouparoo/spec-helper/package.json
  plugins/@grouparoo/sqlite/package.json
  plugins/@grouparoo/vero/package.json
  plugins/@grouparoo/zendesk/package.json
  pnpm-lock.yaml
  ui/ui-community/package.json
  ui/ui-config/package.json
  ui/ui-enterprise/package.json
Labels: dependencies

#2868 Add `retryExports` CLI command
  cli/src/utils/loadLocalCommands.ts
  core/__tests__/bin/retryExports.ts
  core/__tests__/bin/run.ts
  core/__tests__/modules/apiData.ts
  core/__tests__/modules/status.ts
  core/src/bin/retryExports.ts
  core/src/bin/run.ts
  core/src/modules/apiData.ts
  core/src/modules/statusReporters.ts
Labels: enhancement

#2881 default secondary source mapping to nothing
  ui/ui-components/components/source/FormMappingSelector.tsx
Labels: enhancement
